/* Persistent farming and fishing. Every reward is settled once in world state. */
(function(root,factory){const api=factory(root.WitchSeasons||(typeof require==='function'?require('./seasons.js'):null));if(typeof module==='object'&&module.exports)module.exports=api;root.WitchCountry=api;})(globalThis,function(D){
 'use strict';const {CROPS,FISH}=D,empty=()=>({crop:null,sownAt:0,lastAt:0,workMs:0,waterUntil:0}),zeros=o=>Object.fromEntries(Object.keys(o).map(k=>[k,0]));
 function fresh(){return{version:2,coins:30,rod:0,bait:5,seeds:{...zeros(CROPS),radish:3,herbs:2,berries:1},bag:zeros(CROPS),fish:zeros(FISH),caught:zeros(FISH),harvested:zeros(CROPS),best:zeros(FISH),plots:Array.from({length:12},empty),unlocked:6,farmingXp:0,fishingXp:0,hemisphere:'north',fishingPlace:'river',harvests:0,casts:0,visits:0,jobs:0,lastJobAt:0,session:null};}
 function int(v,min=0,max=1000000){if(!Number.isInteger(v)||v<min||v>max)throw Error('田地记录数值不正确');return v;}
 const stamp=v=>int(v,0,8640000000000000);
 function clean(x){if(!x)return fresh();const r=fresh(),old=x.version===undefined;if(!old&&x.version!==2)throw Error('农事存档版本不正确');for(const k of ['coins','bait','harvests','casts','visits'])r[k]=int(x[k]);r.rod=int(x.rod,0,2);
  for(const key of ['seeds','bag','fish','caught','harvested','best'])for(const k of Object.keys(r[key]))r[key][k]=int(x[key]?.[k]??0);
  for(const k of ['farmingXp','fishingXp','jobs'])r[k]=int(x[k]??0);r.lastJobAt=stamp(x.lastJobAt??0);r.unlocked=old?6:int(x.unlocked,6,12);if(![6,9,12].includes(r.unlocked))throw Error('田地数量不正确');r.hemisphere=x.hemisphere==='south'?'south':'north';r.fishingPlace=x.fishingPlace==='pond'?'pond':'river';
  if(!Array.isArray(x.plots)||x.plots.length!==(old?6:12))throw Error('田地数量不正确');x.plots.forEach((p,i)=>{if(p.crop!==null&&!Object.hasOwn(CROPS,p.crop))throw Error('未知作物');if(i>=r.unlocked&&p.crop)throw Error('未开垦土地不能种植');r.plots[i]={crop:p.crop,sownAt:stamp(p.sownAt),lastAt:stamp(p.lastAt),workMs:int(p.workMs,0,p.crop?CROPS[p.crop].minutes*60000:0),waterUntil:stamp(p.waterUntil)};});
  if(x.session){const f=x.session;if(!/^fishing-\d{1,10}$/.test(f.id)||!Object.hasOwn(FISH,f.species)||!['waiting','hooked','caught','escaped'].includes(f.stage))throw Error('钓鱼记录不正确');r.session={id:f.id,species:f.species,stage:f.stage,biteAt:stamp(f.biteAt),distance:int(f.distance,0,120),tension:int(f.tension,0,100),turns:int(f.turns,0,24),rng:int(f.rng,1,4294967295),weather:String(f.weather).slice(0,10),hour:int(f.hour,0,23),collected:f.collected===true,habitat:f.habitat==='pond'?'pond':'river',length:int(f.length??20,1,200),season:D.ALL.includes(f.season)?f.season:'spring'};if(r.session.collected&&r.session.stage!=='caught')throw Error('钓鱼结算不一致');}return r;
 }
 function grow(s,now,weatherAt){for(const p of s.country.plots){if(!p.crop)continue;const max=CROPS[p.crop].minutes*60000;let cursor=p.lastAt;while(cursor<now&&p.workMs<max){const boundary=(Math.floor(cursor/21600000)+1)*21600000,end=Math.min(now,boundary,p.waterUntil>cursor?p.waterUntil:Infinity),boost=weatherAt(s,cursor)==='小雨'||p.waterUntil>cursor?2:1;p.workMs=Math.min(max,p.workMs+(end-cursor)*boost);cursor=end;}p.lastAt=Math.max(p.lastAt,now);}}
 const ripe=p=>p.crop!==null&&p.workMs>=CROPS[p.crop].minutes*60000,stock=(s,k)=>['herbs','berries'].includes(k)?s.home.pantry[k]:s.country.bag[k]||0;
 function addStock(s,k,n){if(['herbs','berries'].includes(k))s.home.pantry[k]=Math.min(24,s.home.pantry[k]+n);else s.country.bag[k]=Math.min(1000000,(s.country.bag[k]||0)+n);}
 function spend(c,n){if(c.coins<n)throw Error('星砂不够，可以先收菜、卖渔获或帮邻居做点事。');c.coins-=n;}
 function canPlant(s,k,at){return CROPS[k]?.seasons.includes(D.season(s,at))&&D.level(s.country.farmingXp)>=CROPS[k].level;}
 const yieldFor=(s,k)=>CROPS[k].yield+(D.level(s.country.farmingXp)>=5?1:0);
 function plotAt(c,i){int(i,0,11);if(i>=c.unlocked)throw Error('先开垦这块田地');return c.plots[i];}
 function random(s){let x=s.rng;x^=x<<13;x^=x>>>17;x^=x<<5;s.rng=x>>>0||1;return s.rng/4294967296;}
 function chooseFish(s,at,f,habitat){const pool=D.fishPool(s,at,habitat);let n=random(f)*pool.reduce((a,p)=>a+p.weight,0);for(const p of pool){n-=p.weight;if(n<=0)return p.id;}return pool.at(-1)?.id||'minnow';}
 function collectFish(s,species,length=20){const c=s.country;c.fish[species]=Math.min(1000000,c.fish[species]+1);c.caught[species]=Math.min(1000000,c.caught[species]+1);c.best[species]=Math.max(c.best[species],length);c.fishingXp=Math.min(1000000,c.fishingXp+3+FISH[species].level);}
 function action(s,kind,data={},now){const c=s.country;
  if(kind==='hemisphere'){if(!['north','south'].includes(data.value))throw Error('请选择半球');c.hemisphere=data.value;return '季节已按'+(data.value==='north'?'北':'南')+'半球日期同步。已种下的作物继续生长。';}
  if(kind==='fishingPlace'){if(!['river','pond'].includes(data.value))throw Error('没有这个钓点');if(c.session&&['waiting','hooked'].includes(c.session.stage))throw Error('请先收好这一竿，再换钓点');c.fishingPlace=data.value;return '这次在'+(data.value==='pond'?'林间池塘':'木栈桥')+'下竿。';}
  if(kind==='expand'){const next=c.unlocked===6?{level:2,cost:30}:c.unlocked===9?{level:4,cost:60}:null;if(!next)throw Error('十二块小田都已开垦');if(D.level(c.farmingXp)<next.level)throw Error('种植熟练度达到 '+next.level+' 级后可以扩田');spend(c,next.cost);c.unlocked+=3;return '又整理出三块小田，现在一共有 '+c.unlocked+' 块。';}
  if(kind==='batch'){if(!['plant','water','harvest'].includes(data.tool))throw Error('请选择农具');const messages=[];for(let i=0;i<c.unlocked;i++){const p=c.plots[i];if(data.tool==='plant'&&p.crop||data.tool==='water'&&(!p.crop||ripe(p)||p.waterUntil>now)||data.tool==='harvest'&&!ripe(p))continue;try{messages.push(action(s,data.tool,{plot:i,crop:data.crop},now));}catch(e){if(!messages.length)throw e;break;}}return messages.length?'一共照料了 '+messages.length+' 块田。'+messages.at(-1):'田里暂时没有需要这项操作的地块。';}
  if(kind==='plant'){const i=data.plot,p=plotAt(c,i),crop=data.crop;if(!Object.hasOwn(CROPS,crop))throw Error('没有这种种子');if(p.crop)throw Error('这块地已经种东西了');if(!canPlant(s,crop,now))throw Error('这份种子需要 '+CROPS[crop].seasons.map(x=>D.NAMES[x]).join(' / ')+'季，种植等级 '+CROPS[crop].level+'；可以留到合适的时候。');if(!c.seeds[crop])throw Error('种子用完了，去商店补充一点吧');c.seeds[crop]--;c.plots[i]={crop,sownAt:now,lastAt:now,workMs:0,waterUntil:0};return '把'+CROPS[crop].name+'种进第 '+(i+1)+' 块地。';}
  if(kind==='water'){const p=plotAt(c,data.plot);if(!p.crop)throw Error('先种下一颗种子吧');if(ripe(p))throw Error('作物成熟了，可以收获');if(p.waterUntil>now)return '这块地还湿润着。';p.waterUntil=now+7200000;return '添好了水，两小时内生长加快。';}
  if(kind==='harvest'){const i=data.plot,p=plotAt(c,i);if(!ripe(p))throw Error('还没有成熟，先让它慢慢长');const k=p.crop,d=CROPS[k],amount=yieldFor(s,k);if(['herbs','berries'].includes(k)&&stock(s,k)+amount>24)throw Error('材料盒装不下这一批，先使用或出售一点；作物会留在地里');addStock(s,k,amount);c.harvests++;c.harvested[k]=Math.min(1000000,c.harvested[k]+amount);c.farmingXp=Math.min(1000000,c.farmingXp+4+d.level);c.plots[i]=empty();return '收下 '+amount+' 份'+d.name+'，种植熟练度 +'+(4+d.level)+'。';}
  if(kind==='buySeed'){const k=data.crop,q=int(data.quantity??1,1,99);if(!Object.hasOwn(CROPS,k))throw Error('没有这种商品');if(!canPlant(s,k,now))throw Error('这份种子当前还没有上架，图鉴里可以查看季节和等级');if(c.seeds[k]+q>1000000)throw Error('种子盒已经很满了');spend(c,CROPS[k].seedPrice*q);c.seeds[k]+=q;return '买到 '+q+' 颗'+CROPS[k].name+'种子。';}
  if(kind==='buyRod'){if(c.rod>=2)throw Error('已经有轻巧的好鱼竿啦');spend(c,c.rod?50:12);c.rod++;return c.rod===1?'带上鱼竿，可以去河流和林间池塘看看。':'轻巧鱼竿收线时更稳。';}
  if(kind==='buyBait'){const q=int(data.quantity??1,1,99);if(c.bait+5*q>1000000)throw Error('鱼饵盒满了');spend(c,3*q);c.bait+=5*q;return '买到 '+(5*q)+' 份鱼饵。';}
  if(kind==='sell'){const k=data.item,fish=Object.hasOwn(FISH,k),d=fish?FISH[k]:CROPS[k],q=int(data.quantity??1,1,1000000);if(!d)throw Error('这种东西不能出售');const available=fish?c.fish[k]:stock(s,k);if(available<q)throw Error('库存不足，先调整数量');if(fish)c.fish[k]-=q;else addStock(s,k,-q);const price=(fish?d.price:d.sell)*q;c.coins=Math.min(1000000,c.coins+price);return '卖出 '+q+' 份'+d.name+'，收到 '+price+' 星砂。';}
  if(kind==='visit'){c.visits++;return '阿栗把'+D.NAMES[D.season(s,now)]+'季的种子摆在店前，旁边是鱼竿和鱼饵。';}
  if(kind==='cast'){if(!c.rod)throw Error('先去商店买一根鱼竿吧');if(!c.bait)throw Error('鱼饵用完了');if(c.session&&['waiting','hooked'].includes(c.session.stage))throw Error('这一竿还没收好');c.bait--;c.casts++;const f={id:'fishing-'+c.casts,rng:(now+c.casts*7919)>>>0||1,distance:100,tension:20,turns:0,stage:'waiting',biteAt:now+2200,species:'minnow',weather:s.world.weather,hour:s.world.hour,collected:false,habitat:c.fishingPlace,season:D.season(s,now),length:20};f.species=chooseFish(s,now,f,f.habitat);f.length=10+Math.floor(random(f)*(20+FISH[f.species].level*12));c.session=f;return '浮标放好了。鱼咬钩后，点浮标起竿。';}
  if(kind==='abandon'){if(!c.session||!['waiting','hooked'].includes(c.session.stage))throw Error('没有正在进行的这一竿');c.session.stage='escaped';return '收好了鱼线，之后还可以再来。';}
  if(['reel','relax','steady'].includes(kind)){const f=c.session;if(!f||!['waiting','hooked'].includes(f.stage))throw Error('先抛一竿吧');if(now<f.biteAt)throw Error('浮标还很安静，再等一会儿');f.stage='hooked';const tug=4+Math.floor(random(f)*9)+Math.max(0,FISH[f.species].level-2),skill=Math.min(5,D.level(c.fishingXp)-1);if(kind==='reel'){f.distance=Math.max(0,f.distance-18-Math.floor(random(f)*8));f.tension+=tug+(c.rod===2?12:19)-skill;}if(kind==='relax'){f.distance=Math.min(120,f.distance+7);f.tension=Math.max(0,f.tension-32+tug);}if(kind==='steady'){f.distance=Math.max(0,f.distance-5);f.tension=Math.max(0,f.tension-13+tug-skill);}f.turns++;if(f.tension>=100||f.turns>=24&&f.distance>0){f.tension=Math.min(100,f.tension);f.stage='escaped';return '鱼线绷得太紧，小鱼游走了。下一竿试试交替收线和松线。';}if(f.distance===0){f.stage='caught';if(!f.collected){f.collected=true;collectFish(s,f.species,f.length);}return '钓到了 '+FISH[f.species].name+' · '+f.length+' 厘米！已经记进鱼类图鉴。';}return kind==='reel'?'鱼靠近了一点，留意张力。':kind==='relax'?'松一点线，张力降下来了。':'稳住鱼竿，慢慢带近。';}
  throw Error('未知田地操作');
 }
 function task(s,at=s.lastAdvancedAt){const c=s.country,plots=c.plots.slice(0,c.unlocked);let i=plots.findIndex(p=>ripe(p)&&(!['herbs','berries'].includes(p.crop)||stock(s,p.crop)+yieldFor(s,p.crop)<=24));if(i>=0)return{type:'harvest',plot:i,crop:plots[i].crop};i=plots.findIndex(p=>!p.crop);if(i>=0){const k=Object.keys(CROPS).find(k=>c.seeds[k]>0&&canPlant(s,k,at));if(k)return{type:'plant',plot:i,crop:k};}i=plots.findIndex(p=>p.crop&&!ripe(p)&&p.waterUntil<=at);return i>=0?{type:'water',plot:i,crop:plots[i].crop}:null;}
 function finishGarden(s,a,now){const job=a.gardenJob;if(!job)return null;try{if(job.type!=='plant'&&s.country.plots[job.plot].crop!==job.crop)throw Error('作物变化');return action(s,job.type,job,now);}catch{return '她检查了浇水壶和种子盒，这块地已经照料好了。';}}
 function beginAutoFish(s,now){if(!s.country.rod||!s.country.bait)throw Error('鱼竿或鱼饵不足');s.country.bait--;s.country.casts++;const f={rng:(now+s.country.casts*7919)>>>0||1};return chooseFish(s,now,f,s.country.fishingPlace);}
 function finishAutoFish(s,species){collectFish(s,species,12+FISH[species].level*7);return '她钓到一条'+FISH[species].name+'，收进鱼篓，也记下了它的样子。';}
 return{beginAutoFish,finishAutoFish,CROPS,FISH,fresh,clean,grow,ripe,stock,action,task,finishGarden,canPlant,yieldFor,season:D.season,level:D.level,fishHint:D.fishHint};
});
