/* Garden, fishing and the tiny market share the same local economy. */
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.WitchCountry=api;})(globalThis,function(){
 'use strict';const CROPS={radish:{name:'小萝卜',minutes:5,yield:3,seedPrice:3,sell:3,token:3},herbs:{name:'香草',minutes:12,yield:2,seedPrice:4,sell:4,token:4},berries:{name:'浆果',minutes:20,yield:3,seedPrice:6,sell:5,token:3},moonflower:{name:'月见花',minutes:30,yield:2,seedPrice:9,sell:8,token:1}};
 const FISH={minnow:{name:'溪流小银鱼',price:4,color:'#b7c7bd'},perch:{name:'苔纹鲈鱼',price:7,color:'#88a17a'},carp:{name:'暖金鲤鱼',price:10,color:'#ceaa69'},rainfish:{name:'雨点鳟鱼',price:13,color:'#7bafbd'},moonfish:{name:'月尾鱼',price:16,color:'#b1a3c8'}};
 function fresh(){return{coins:30,rod:0,bait:5,seeds:{radish:3,herbs:2,berries:1,moonflower:0},bag:{radish:0,moonflower:0},fish:Object.fromEntries(Object.keys(FISH).map(k=>[k,0])),caught:Object.fromEntries(Object.keys(FISH).map(k=>[k,0])),plots:Array.from({length:6},()=>({crop:null,sownAt:0,lastAt:0,workMs:0,waterUntil:0})),harvests:0,casts:0,visits:0,session:null};}
 function int(v,min=0,max=1000000){if(!Number.isInteger(v)||v<min||v>max)throw Error('田地记录数值不正确');return v;}
 function stamp(v){return int(v,0,8640000000000000);}
 function clean(x){if(!x)return fresh();const r=fresh();for(const k of ['coins','bait','harvests','casts','visits'])r[k]=int(x[k]);r.rod=int(x.rod,0,2);for(const key of ['seeds','bag','fish','caught'])for(const k of Object.keys(r[key]))r[key][k]=int(x[key]?.[k]);if(x.plots?.length!==6)throw Error('田地数量不正确');r.plots=x.plots.map(p=>{if(p.crop!==null&&!Object.hasOwn(CROPS,p.crop))throw Error('未知作物');return{crop:p.crop,sownAt:stamp(p.sownAt),lastAt:stamp(p.lastAt),workMs:int(p.workMs,0,p.crop?CROPS[p.crop].minutes*60000:0),waterUntil:stamp(p.waterUntil)};});if(x.session){const f=x.session;if(!/^fishing-\d{1,10}$/.test(f.id)||!Object.hasOwn(FISH,f.species)||!['waiting','hooked','caught','escaped'].includes(f.stage))throw Error('钓鱼记录不正确');r.session={id:f.id,species:f.species,stage:f.stage,biteAt:stamp(f.biteAt),distance:int(f.distance,0,120),tension:int(f.tension,0,100),turns:int(f.turns,0,24),rng:int(f.rng,1,4294967295),weather:String(f.weather).slice(0,10),hour:int(f.hour,0,23),collected:f.collected===true};if(r.session.collected&&r.session.stage!=='caught')throw Error('钓鱼结算不一致');}return r;}
 function grow(s,now,weatherAt){for(const p of s.country.plots){if(!p.crop)continue;const max=CROPS[p.crop].minutes*60000;let cursor=p.lastAt;while(cursor<now&&p.workMs<max){const boundary=(Math.floor(cursor/21600000)+1)*21600000,end=Math.min(now,boundary,p.waterUntil>cursor?p.waterUntil:Infinity),boost=weatherAt(s,cursor)==='小雨'||p.waterUntil>cursor?2:1;p.workMs=Math.min(max,p.workMs+(end-cursor)*boost);cursor=end;}p.lastAt=Math.max(p.lastAt,now);}}
 const ripe=p=>p.crop!==null&&p.workMs>=CROPS[p.crop].minutes*60000;
 const stock=(s,k)=>['herbs','berries'].includes(k)?s.home.pantry[k]:s.country.bag[k];
 function addStock(s,k,n){if(['herbs','berries'].includes(k))s.home.pantry[k]=Math.min(24,s.home.pantry[k]+n);else s.country.bag[k]=Math.min(1000000,s.country.bag[k]+n);}
 function spend(c,n){if(c.coins<n)throw Error('星砂不够，可以先收菜或卖一点渔获。');c.coins-=n;}
 function action(s,kind,data,now){const c=s.country;data=data||{};
  if(kind==='plant'){const i=int(data.plot,0,5),crop=data.crop,p=c.plots[i];if(!Object.hasOwn(CROPS,crop))throw Error('没有这种种子');if(p.crop)throw Error('这块地已经种东西了');if(!c.seeds[crop])throw Error('种子用完了，可以去小商店看看');c.seeds[crop]--;c.plots[i]={crop,sownAt:now,lastAt:now,workMs:0,waterUntil:0};return '把一颗'+CROPS[crop].name+'种子种进第 '+(i+1)+' 块地。';}
  if(kind==='water'){const p=c.plots[int(data.plot,0,5)];if(!p.crop)throw Error('先种下一颗种子吧');p.waterUntil=now+7200000;return '土壤湿润了，两小时内生长速度加倍；雨天也有同样的帮助。';}
  if(kind==='harvest'){const i=int(data.plot,0,5),p=c.plots[i];if(!ripe(p))throw Error('还没有成熟，先让它慢慢长');const d=CROPS[p.crop],amount=d.yield;if(['herbs','berries'].includes(p.crop)&&stock(s,p.crop)+amount>24)throw Error('材料盒装不下这一批，先使用或出售一点；作物会好好留在地里');if(!amount)throw Error('材料盒满了，先做点东西或卖一点，再来收菜');addStock(s,p.crop,amount);c.harvests++;c.plots[i]={crop:null,sownAt:0,lastAt:0,workMs:0,waterUntil:0};return '收下 '+amount+' 份'+d.name+'，它们可以做材料或换成星砂。';}
  if(kind==='buySeed'){if(!Object.hasOwn(CROPS,data.crop))throw Error('没有这种商品');if(c.seeds[data.crop]>=999999)throw Error('种子盒已经很满了');spend(c,CROPS[data.crop].seedPrice);c.seeds[data.crop]++;return '买到一颗'+CROPS[data.crop].name+'种子。';}
  if(kind==='buyRod'){if(c.rod>=2)throw Error('已经有轻巧的好鱼竿啦');spend(c,c.rod?50:12);c.rod++;return c.rod===1?'有鱼竿了，可以去木栈桥试试钓鱼。':'换成轻巧鱼竿，收线时张力增长会小一点。';}
  if(kind==='buyBait'){spend(c,3);c.bait=Math.min(1000000,c.bait+5);return '买到五份鱼饵。';}
  if(kind==='sell'){const k=data.item;let price;if(Object.hasOwn(FISH,k)){if(!c.fish[k])throw Error('鱼篓里没有这种鱼');c.fish[k]--;price=FISH[k].price;}else if(Object.hasOwn(CROPS,k)){if(!stock(s,k))throw Error('没有可以卖出的这一份');addStock(s,k,-1);price=CROPS[k].sell;}else throw Error('这种东西不能在这里出售');c.coins=Math.min(1000000,c.coins+price);return '卖出一份，收到 '+price+' 星砂。';}
  if(kind==='visit'){c.visits++;return '小商店一直开着。种子、鱼竿和鱼饵都在这里，收获也可以换成星砂。';}
  if(kind==='cast'){if(!c.rod)throw Error('先去小商店买一根鱼竿吧');if(!c.bait)throw Error('鱼饵用完了，商店里可以买到');if(c.session&&['waiting','hooked'].includes(c.session.stage))throw Error('这一竿还没收好');c.bait--;c.casts++;const seed=(now+c.casts*7919)>>>0||1,f={id:'fishing-'+c.casts,rng:seed,distance:100,tension:20,turns:0,stage:'waiting',biteAt:now+3000,species:'minnow',weather:s.world.weather,hour:s.world.hour,collected:false};const list=['minnow','minnow','perch','perch','carp',...(s.world.weather==='小雨'?['rainfish','rainfish']:[]),...(s.world.hour>=19||s.world.hour<6?['moonfish']:[])];f.species=list[Math.floor(random(f)*list.length)];c.session=f;return '浮标放好了。等它动起来，随时可以收线，不会因为你走开而错过。';}
  if(kind==='abandon'){if(!c.session||!['waiting','hooked'].includes(c.session.stage))throw Error('没有正在进行的这一竿');c.session.stage='escaped';return '把这一竿收好。已用的鱼饵不退回，之后还可以再来。';}
  if(['reel','relax','steady'].includes(kind)){const f=c.session;if(!f||!['waiting','hooked'].includes(f.stage))throw Error('先抛一竿吧');if(now<f.biteAt)throw Error('浮标还很安静，再等一会儿');f.stage='hooked';const tug=4+Math.floor(random(f)*9);if(kind==='reel'){f.distance=Math.max(0,f.distance-18-Math.floor(random(f)*8));f.tension+=tug+(c.rod===2?12:19);}if(kind==='relax'){f.distance=Math.min(120,f.distance+7);f.tension=Math.max(0,f.tension-32+tug);}if(kind==='steady'){f.distance=Math.max(0,f.distance-5);f.tension=Math.max(0,f.tension-13+tug);}f.turns++;if(f.tension>=100||f.turns>=24&&f.distance>0){f.tension=Math.min(100,f.tension);f.stage='escaped';return '鱼线太紧或拉锯太久，小鱼游走了。下一次试着交替收线和放松。';}if(f.distance===0){f.stage='caught';if(!f.collected){f.collected=true;c.fish[f.species]++;c.caught[f.species]++;}return '钓到了'+FISH[f.species].name+'！鱼篓和图鉴都记下了这一条。';}return kind==='reel'?'慢慢收近了一段，留意鱼线张力。':kind==='relax'?'松一点线，让张力降下来。':'稳住鱼竿，慢慢把鱼带近。';}
  throw Error('未知田地操作');
 }
 function random(s){let x=s.rng;x^=x<<13;x^=x>>>17;x^=x<<5;s.rng=x>>>0||1;return s.rng/4294967296;}
 function task(s,at=s.lastAdvancedAt){const c=s.country;let i=c.plots.findIndex(p=>ripe(p)&&(!['herbs','berries'].includes(p.crop)||stock(s,p.crop)+CROPS[p.crop].yield<=24));if(i>=0){const k=c.plots[i].crop;if(!['herbs','berries'].includes(k)||stock(s,k)<24)return{type:'harvest',plot:i,crop:k};}i=c.plots.findIndex(p=>!p.crop);if(i>=0){const k=Object.keys(CROPS).find(k=>c.seeds[k]>0);if(k)return{type:'plant',plot:i,crop:k};}i=c.plots.findIndex(p=>p.crop&&!ripe(p)&&p.waterUntil<=at);return i>=0?{type:'water',plot:i,crop:c.plots[i].crop}:null;}
 function finishGarden(s,a,now){const job=a.gardenJob;if(!job)return null;try{if(job.type!=='plant'&&s.country.plots[job.plot].crop!==job.crop)throw Error('田里已经换了一种作物');return action(s,job.type,job,now);}catch{return '你已经照顾过这块地，她检查了种子盒和浇水壶，没有重复收取作物。';}}
 function beginAutoFish(s,now){if(!s.country.rod||!s.country.bait)throw Error('鱼竿或鱼饵不足');s.country.bait--;const f={rng:(now+s.country.casts*7919)>>>0||1};s.country.casts++;const pool=['minnow','perch','carp',...(s.world.weather==='小雨'?['rainfish']:[]),...(s.world.hour>=19||s.world.hour<6?['moonfish']:[])];return pool[Math.floor(random(f)*pool.length)];}
 function finishAutoFish(s,species){s.country.fish[species]++;s.country.caught[species]++;return '她用出门前带的一份鱼饵，钓到一条'+FISH[species].name+'，已经放进鱼篓。';}
 return{beginAutoFish,finishAutoFish,CROPS,FISH,fresh,clean,grow,ripe,stock,action,task,finishGarden};
});
