(function(r){'use strict';const E=r.WitchCountry,C=r.WitchCompanions,el=(t,text,c)=>{const e=document.createElement(t);if(text!==undefined)e.textContent=text;if(c)e.className=c;return e;},btn=(t,f,c='soft-button')=>{const b=el('button',t,c);b.type='button';b.onclick=f;return b;};
 function country(host,{state,tab='farm',act,onInvite,onTab,onExit}){const body=el('div'),message=el('p','','game-message');message.setAttribute('role','status');host.replaceChildren(body);function run(k,d){try{const text=act(k,d);render();message.textContent=text;}catch(e){message.textContent=e.message;}}
 function render(){body.replaceChildren();body.append(el('p',`星砂 ${state.country.coins} · 鱼饵 ${state.country.bait} · ${['还没有鱼竿','木鱼竿','轻巧鱼竿'][state.country.rod]}`,'stock-line'));const tabs=el('div',undefined,'game-toolbar');for(const[k,t]of[['farm','六块小田'],['shop','河畔小店'],['fishing','木栈桥']])tabs.append(btn(t,()=>onTab(k)));body.append(tabs,message);
 if(tab==='farm'){body.append(el('p','没有枯萎和错过收获。雨天或浇水让生长加快，作物会等你回来。伙伴也会在白天照料田地。','thought'));const grid=el('div',undefined,'farm-grid');state.country.plots.forEach((p,i)=>{const card=el('article',undefined,'farm-plot');card.append(el('h3','第 '+(i+1)+' 块小田'));if(!p.crop){card.append(el('p','松软的空田'));const select=el('select');select.setAttribute('aria-label','第 '+(i+1)+' 块田要种什么');for(const[k,d]of Object.entries(E.CROPS)){const o=el('option',d.name+' · 种子 '+state.country.seeds[k]);o.value=k;o.disabled=!state.country.seeds[k];select.append(o);}const available=Object.keys(E.CROPS).find(k=>state.country.seeds[k]>0);if(available)select.value=available;select.style.maxWidth='100%';const plant=btn('种下',()=>run('plant',{plot:i,crop:select.value}));plant.disabled=!available;card.append(select,plant);}else{const d=E.CROPS[p.crop],bar=el('progress');bar.max=d.minutes*60000;bar.value=p.workMs;const wet=state.world.weather==='小雨'||p.waterUntil>Date.now();card.append(el('p',d.name+' · '+Math.floor(p.workMs/bar.max*100)+'%'),bar,el('p',E.ripe(p)?'长好了，等你来收。':(wet?'土壤湿润 · ':'慢慢生长 · ')+Math.ceil((bar.max-p.workMs)/(wet?120000:60000))+' 分钟左右成熟'));card.append(btn(E.ripe(p)?'收获':'浇一点水',()=>run(E.ripe(p)?'harvest':'water',{plot:i})));}grid.append(card);});body.append(grid,btn('邀她一起照料小田',()=>onInvite('garden'),'primary'),btn('看看最新生长进度',()=>{act('refresh',{});render();}));}
 if(tab==='shop'){body.append(el('p','种一点、收一点，再换想要的种子和渔具。花费和收获都来自你们自己的世界。','thought'));for(const[k,d]of Object.entries(E.CROPS)){const c=el('article',undefined,'shop-row');c.append(el('h3',d.name),el('p',`种子 ${d.seedPrice} 星砂 · 基础生长 ${d.minutes} 分钟 · 收获 ${d.yield} 份 · 已有种子 ${state.country.seeds[k]}`),btn('买一颗种子',()=>run('buySeed',{crop:k})));body.append(c);}const rod=el('article',undefined,'shop-row');rod.append(el('h3','渔具与鱼饵'),el('p','鱼饵 3 星砂 / 5 份。轻巧鱼竿收线时更稳。'),btn(state.country.rod===0?'木鱼竿 · 12 星砂':state.country.rod===1?'升级鱼竿 · 50 星砂':'已有轻巧鱼竿',()=>run('buyRod',{})),btn('买五份鱼饵',()=>run('buyBait',{})));body.append(rod,el('h3','把收获换成星砂'));for(const[k,d]of [...Object.entries(E.CROPS),...Object.entries(E.FISH)]){const amount=E.FISH[k]?state.country.fish[k]:E.stock(state,k);if(amount)body.append(btn(`${d.name} ×${amount} · 卖一份 +${d.sell||d.price}`,()=>run('sell',{item:k})));}}
 body.append(el('h3','河畔小图鉴'));for(const[k,d]of Object.entries(E.FISH))body.append(el('p',`${state.country.caught[k]?'✓ '+d.name:'？ 尚未遇到'} · ${k==='rainfish'?'雨天来试试':k==='moonfish'?'夜里来试试':'河里常见的小鱼'}${state.country.caught[k]?' · 共遇到 '+state.country.caught[k]+' 条':''}`));body.append(btn('回去看看',onExit));}render();let lastPlots=JSON.stringify(state.country.plots.map(p=>[p.crop,p.sownAt]));const timer=setInterval(()=>{if(!body.isConnected){clearInterval(timer);return;}if(tab!=='farm')return;const nextPlots=JSON.stringify(state.country.plots.map(p=>[p.crop,p.sownAt]));if(lastPlots!==nextPlots){lastPlots=nextPlots;render();return;}body.querySelectorAll('.farm-plot').forEach((card,i)=>{const p=state.country.plots[i];if(!p.crop)return;const d=E.CROPS[p.crop],bar=card.querySelector('progress'),lines=card.querySelectorAll('p'),wet=state.world.weather==='小雨'||p.waterUntil>Date.now();bar.value=p.workMs;lines[0].textContent=d.name+' · '+Math.floor(p.workMs/bar.max*100)+'%';lines[1].textContent=E.ripe(p)?'长好了，等你来收。':(wet?'土壤湿润 · ':'慢慢生长 · ')+Math.ceil((bar.max-p.workMs)/(wet?120000:60000))+' 分钟左右成熟';card.querySelector('button').textContent=E.ripe(p)?'收获':'浇一点水';});},1000);return{destroy(){clearInterval(timer);host.replaceChildren();}};
 }
 function fishing(host,{state,act,onExit,onShop}){
  let alive=true,raf=0,held=false,repeat=false,lastPull=0,lastTime=0,shownDistance=state.country.session?.distance||100,shownTension=state.country.session?.tension||20;
  const body=el('div',undefined,'mini-game fishing-game'),status=el('p','','game-message'),description=el('p','','game-progress'),water=el('canvas',undefined,'fishing-water fishing-canvas'),meters=el('div',undefined,'fishing-meters'),distance=el('progress'),tension=el('progress'),bar=el('div',undefined,'game-toolbar');water.width=900;water.height=440;water.setAttribute('aria-label','河面与浮标，鱼上钩后点击浮标起竿');water.setAttribute('role','button');water.tabIndex=0;distance.max=120;tension.max=100;tension.className='danger';const d=el('label','离岸距离'),t=el('label','鱼线张力');d.append(distance);t.append(tension);meters.append(d,t);status.setAttribute('role','status');
  const main=el('div',undefined,'fishing-main'),side=el('div',undefined,'fishing-controls');main.append(water,description,status);side.append(meters,bar);body.append(main,side);host.replaceChildren(body);host.closest('.sheet')?.classList.add('fishing-session');
  function run(k){try{status.textContent=act(k,{});update();}catch(e){status.textContent=e.message;}}
  const cast=btn('抛一竿 · 用 1 鱼饵',()=>run('cast'),'primary'),reel=btn('收线',e=>{if(!repeat||e.detail===0)run('reel');repeat=false;},'primary'),relax=btn('松线',()=>run('relax')),steady=btn('稳住',()=>run('steady')),abandon=btn('收起这一竿',()=>{const q=el('div',undefined,'game-confirm');q.append(el('p','收竿放走这条鱼？'),btn('确认收竿',()=>{q.remove();run('abandon');}),btn('继续钓',()=>q.remove()));side.querySelector('.game-confirm')?.remove();side.append(q);});bar.append(cast,reel,relax,steady,abandon,btn('去商店',onShop),btn('先收好，下次继续',onExit));
  reel.addEventListener('pointerdown',e=>{if(reel.disabled)return;held=true;repeat=false;lastPull=performance.now();reel.setPointerCapture(e.pointerId);});const release=()=>{held=false;};reel.addEventListener('pointerup',release);reel.addEventListener('pointercancel',release);reel.addEventListener('lostpointercapture',release);window.addEventListener('blur',release);document.addEventListener('visibilitychange',release);
  const strike=()=>{const f=state.country.session;if(f&&['waiting','hooked'].includes(f.stage)&&Date.now()>=f.biteAt)run('reel');};water.addEventListener('click',strike);water.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();strike();}});
  function update(){if(!alive)return;const f=state.country.session,live=f&&['waiting','hooked'].includes(f.stage),bite=f&&Date.now()>=f.biteAt;description.textContent=`鱼饵 ${state.country.bait} · `+(!f?'选好位置，抛一竿吧。':f.stage==='caught'?'钓到了 '+E.FISH[f.species].name:f.stage==='escaped'?'鱼游走了。':!bite?'等浮标动起来…':f.tension>75?'鱼线绷紧了，松一松！':'点浮标起竿 · 按住收线，松线降张力');distance.value=f?.distance||0;tension.value=f?.tension||0;cast.disabled=!!live||!state.country.bait||!state.country.rod;[reel,relax,steady].forEach(b=>b.disabled=!live||!bite);abandon.disabled=!live;meters.hidden=!live;cast.hidden=!!live;reel.hidden=relax.hidden=steady.hidden=!live;if(!live)held=false;}
  function paint(time){if(!alive)return;const dt=Math.min(50,time-lastTime||16);lastTime=time;const f=state.country.session,live=f&&['waiting','hooked'].includes(f.stage),bite=f&&Date.now()>=f.biteAt;
   if(held&&!reel.disabled&&time-lastPull>650){lastPull=time;repeat=true;run('reel');}
   shownDistance+=((f?.distance??100)-shownDistance)*Math.min(1,dt/150);shownTension+=((f?.tension??0)-shownTension)*Math.min(1,dt/120);
   const c=water.getContext('2d');c.setTransform(2,0,0,2,0,0);c.clearRect(0,0,450,220);const g=c.createLinearGradient(0,0,0,220);g.addColorStop(0,'#467577');g.addColorStop(1,'#739688');c.fillStyle=g;c.fillRect(0,0,450,220);
   c.strokeStyle='#b4d0b255';c.lineWidth=1;for(let i=0;i<18;i++){const x=(i*61+time*.007)%410+40,y=26+(i*43)%170;c.beginPath();c.moveTo(x,y);c.quadraticCurveTo(x+9,y+Math.sin(time/1300+i)*3,x+20,y);c.stroke();}
   c.fillStyle='#665539';c.fillRect(0,150,88,70);for(let y=150;y<220;y+=12){c.fillStyle='#b6996c';c.fillRect(0,y,83,9);}c.strokeStyle='#664832';c.lineWidth=4;c.beginPath();c.moveTo(30,188);c.quadraticCurveTo(40,82,110,58+shownTension*.16);c.stroke();
   if(f){const x=82+shownDistance*2.5,y=110+Math.sin(time/800)*2,high=f.tension>75;const pull=live&&bite?Math.sin(time/85)*Math.min(3,f.tension/25):0;c.strokeStyle=high?'#ecc089':'#ecedca';c.lineWidth=high?1.5:1;c.beginPath();c.moveTo(110,58+shownTension*.16);c.quadraticCurveTo((110+x)/2,130-shownTension*.4,x+pull,y);c.stroke();
    if(live){c.strokeStyle='#dfecd2aa';c.lineWidth=1;for(let n=0;n<3;n++){const phase=(time/900+n/3)%1;c.globalAlpha=1-phase;c.beginPath();c.ellipse(x,y+5,8+phase*24,3+phase*9,0,0,Math.PI*2);c.stroke();}c.globalAlpha=1;c.save();c.translate(x+pull,y);c.rotate(bite?Math.sin(time/130)*.18:.08);c.fillStyle='#ecd9a7';c.fillRect(-3,-9,6,20);c.fillStyle='#b55f43';c.fillRect(-3,-12,6,12);c.restore();if(bite){c.fillStyle='#294f4c88';c.beginPath();c.ellipse(x-12,y+20,14,5,Math.sin(time/600)*.4,0,Math.PI*2);c.fill();c.fillStyle='#fff1b5';c.font='bold 18px sans-serif';c.fillText('!',x-3,y-25);}}
    if(f.stage==='caught'){c.fillStyle='#e7ce94';c.beginPath();c.ellipse(93,137,20,8,-.2,0,Math.PI*2);c.fill();c.beginPath();c.moveTo(75,138);c.lineTo(62,128);c.lineTo(63,146);c.closePath();c.fill();c.fillStyle='#314d45';c.fillRect(101,133,3,3);}
   }raf=requestAnimationFrame(paint);
  }
  update();raf=requestAnimationFrame(paint);const timer=setInterval(update,250);return{getState:()=>null,destroy(){alive=false;held=false;clearInterval(timer);cancelAnimationFrame(raf);window.removeEventListener('blur',release);document.removeEventListener('visibilitychange',release);host.closest('.sheet')?.classList.remove('fishing-session');host.replaceChildren();}};
 }
 function profile(host,{state,onSave,onExit}){let portrait=state.avatar.portrait||null,portraitImage=null;const oldSprite=new Image();oldSprite.src='assets/witch-walk-v1.png';oldSprite.onload=()=>paint();const body=el('div',undefined,'profile-form'),msg=el('p','','game-message'),preview=el('canvas');preview.width=180;preview.height=220;msg.setAttribute('role','status');const original=state.avatar.kind==='original';body.append(el('p',original?'小罗和现在的世界都在。这里可以另选外形、导入设定或上传立绘；选择“保留原形象”可只调名字和性格，梦种和进度都会保留。':'给这段生活找一个属于你的伙伴。名字、外形和性格之后都能调整。','thought'));host.replaceChildren(body);
 const name=el('input');name.maxLength=16;name.value=state.avatar.kind==='unbound'?'':state.preferences.name;name.placeholder='伙伴的名字';const form=el('select');if(original){const o=el('option','保留我的小罗原形象');o.value='original';form.append(o);}for(const[k,v]of Object.entries(C.FORMS)){const o=el('option',v);o.value=k;form.append(o);}form.value=original?'original':state.avatar.form;const palette=el('select');for(const[k,v]of Object.entries(C.PALETTES)){const o=el('option',({moss:'苔藓绿',plum:'雾莓紫',river:'河水蓝',amber:'蜂蜜金'})[k]);o.value=k;palette.append(o);}let bodyColor=state.avatar.body,accent=state.avatar.accent;const bio=el('textarea');bio.maxLength=400;bio.value=state.avatar.bio;bio.placeholder='喜欢什么、哪里来的、有一点什么小习惯……（设定记在这里，尚未逐句变成行为规则）';function field(text,input){const label=el('label',text);label.append(input);body.append(label);}field('名字',name);field('魔法生灵外形',form);field('配色',palette);const box=el('div',undefined,'profile-preview');box.append(preview,el('p','内置生灵会随步子轻轻摆动。上传图片以整张立绘移动，不会自动生成多方向动画。'));body.append(box);const sliders={};for(const[k,t]of Object.entries({curiosity:'好奇心',bookish:'爱读书',quiet:'喜欢安静'})){const input=el('input');input.type='range';input.min=0;input.max=100;input.value=Math.round(state.preferences[k]*100);sliders[k]=input;field(t,input);}field('角色的小设定',bio);
 const file=el('input');file.type='file';file.accept='image/png,image/jpeg,image/webp';field('上传自己的角色图片（PNG / JPG / WebP）',file);body.append(el('small','图片缩至最长 320 像素后放进本机存档；不会上传 GitHub 或发送给 AI。透明 PNG 可保留透明背景。'),btn('移除上传图片，使用内置生灵',()=>{portrait=null;portraitImage=null;paint();}));
 async function loadPortrait(){if(!portrait){paint();return;}const im=new Image();im.src=portrait;await im.decode();portraitImage=im;paint();}function paint(){const c=preview.getContext('2d');c.clearRect(0,0,180,220);if(form.value==='original'&&!portrait&&oldSprite.complete&&oldSprite.naturalWidth){c.imageSmoothingEnabled=false;c.drawImage(oldSprite,105,28,349,482,29,26,123,170);return;}C.draw(c,{kind:portrait?'portrait':'creature',form:form.value,body:bodyColor,accent},90,204,170,0,false,false,portraitImage);}form.onchange=paint;palette.onchange=()=>{[bodyColor,accent]=C.PALETTES[palette.value];paint();};
 file.onchange=async()=>{const f=file.files[0];if(!f)return;try{if(!['image/png','image/jpeg','image/webp'].includes(f.type)||f.size>8000000)throw Error('请选择 8 MB 以内的 PNG、JPG 或 WebP');const url=URL.createObjectURL(f),im=new Image();try{im.src=url;await im.decode();if(im.naturalWidth*im.naturalHeight>40000000)throw Error('图片尺寸太大，请先缩小');const scale=Math.min(1,320/Math.max(im.naturalWidth,im.naturalHeight)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(im.naturalWidth*scale));c.height=Math.max(1,Math.round(im.naturalHeight*scale));c.getContext('2d').drawImage(im,0,0,c.width,c.height);portrait=c.toDataURL('image/png');C.clean({...state.avatar,kind:'portrait',portrait});await loadPortrait();msg.textContent='图片准备好了，点击保存后才会带入世界。';}finally{URL.revokeObjectURL(url);}}catch(e){msg.textContent=e.message;}};
 const prompt='请帮我设计一个魔法生灵，只返回 JSON，不要代码块。格式：{"name":"16字以内","form":"sprout 或 fox 或 moth","body":"#86a576","accent":"#e7c78d","bio":"400字以内角色设定","personality":{"curiosity":0.7,"bookish":0.4,"quiet":0.6}}。性格数值为0到1。不要输出脚本、存档、道具或奖励。';const details=el('details'),summary=el('summary','用自己的 AI 写角色设定'),source=el('textarea'),json=el('textarea');source.value=prompt;source.readOnly=true;source.setAttribute('aria-label','角色创作提示词');json.maxLength=5000;json.placeholder='把 AI 返回的 JSON 粘贴在这里';json.setAttribute('aria-label','导入角色 JSON');details.append(summary,el('p','复制提示词给你自己的 AI。游戏只读取名字、外形、配色、性格和文字设定。'),source,btn('复制角色提示词',async()=>{try{await navigator.clipboard.writeText(prompt);msg.textContent='已复制。';}catch{source.select();msg.textContent='请复制已选中的提示词。';}}),json,btn('检查并填入设定',()=>{try{const p=C.proposal(JSON.parse(json.value.trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'')));name.value=p.name;form.value=p.avatar.form;bodyColor=p.avatar.body;accent=p.avatar.accent;bio.value=p.avatar.bio;for(const k in sliders)sliders[k].value=Math.round(p.personality[k]*100);paint();msg.textContent='设定已填入，检查后保存；已选图片会保留。';}catch(e){msg.textContent=e.message;}}));body.append(details,msg,btn(original?'保存这次角色调整':'让伙伴住进来',()=>{try{onSave({name:name.value,form:form.value,body:bodyColor,accent,bio:bio.value,personality:Object.fromEntries(Object.entries(sliders).map(([k,v])=>[k,Number(v.value)/100])),portrait});}catch(e){msg.textContent=e.message;}},'primary'),btn(original?'保留小罗，不更改':'先看看这个世界',onExit));loadPortrait().catch(e=>msg.textContent=e.message);return{destroy(){host.replaceChildren();}};
 }
 function paintCrops(ctx,state){state.country.plots.forEach((p,i)=>{if(!p.crop)return;const x=[135,272,411][i%3],y=i<3?710:830,f=Math.min(1,p.workMs/(E.CROPS[p.crop].minutes*60000));ctx.save();ctx.translate(x,y);ctx.fillStyle='#557350';ctx.fillRect(-3,-8-f*45,6,30+f*15);ctx.beginPath();ctx.ellipse(-15,-5-f*30,19,8,-.5,0,Math.PI*2);ctx.ellipse(15,-18-f*30,18,8,.5,0,Math.PI*2);ctx.fill();if(f>.5){ctx.fillStyle=({radish:'#d5b4a5',herbs:'#a6be80',berries:'#9d526c',moonflower:'#e9ce87'})[p.crop];ctx.beginPath();ctx.arc(0,-22-f*40,12+f*7,0,Math.PI*2);ctx.fill();}if(E.ripe(p)){ctx.fillStyle='#e9d994';ctx.font='20px serif';ctx.fillText('✦',20,-60);}ctx.restore();});}
 r.WitchExpeditionUI={country,fishing,profile,paintCrops};
})(globalThis);
