/* Ten small board games with deterministic replay and independent save slots. */
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.WitchFestival=api;})(globalThis,function(){
 'use strict';
 const CATALOG={mines:['露珠扫雷','数字告诉你周围八格藏着几颗雷。首点安全，点旗标记。',3],sokoban:['松果推箱子','把每只松果箱推上圆形垫子。箱子只能推，支持撤销。',12],slide:['数字滑块','点空格旁的数字移动，排回从小到大的顺序。',3],lights:['点亮星灯','点一盏灯，会翻转它和上下左右的灯。让所有灯亮起来。',3],hanoi:['月环汉诺塔','把左边的月环搬到最右。一次一只，小环必须在大环上。',4],code:['猜猜色珠','猜四颗色珠。实心点表示颜色位置都对，空心点表示颜色对、位置不同。',3],reversi:['林间黑白棋','你执黑，落子夹住白棋就能翻转。最后棋子多的一方获胜。',2],connect:['四子连珠','你执金子，点一列落到底部。横、竖、斜先连成四颗获胜。',3],peg:['月石孔明棋','选一颗月石，跳过相邻月石到空位；被跳过的收走。留下一颗即成功。',1],maze:['寻钥迷宫','走进林间迷宫，收齐三把钥匙，再到星星出口。',5]};
 CATALOG.ludo=['星航飞行棋','你和伙伴各有四架飞机。掷到 6 起飞；同色格跳四格，航线格飞十二格。进入终点需刚好点数，先全部到家获胜。',2];
 CATALOG.trail=['萤灯横版远足','按住左右移动，点跳跃越过空隙和小影团。收集星光，抵达路标；落下会回到最近的落脚点。',8];
 const ids=Object.keys(CATALOG),clone=x=>JSON.parse(JSON.stringify(x));
 function rng(seed){let x=seed>>>0||1;return()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return(x>>>0)/4294967296;};}
 function shuffle(a,r){for(let i=a.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
 const boxes=[['#######','#     #','# . . #','# $ $ #','#  @  #','#     #','#######'],['#######','# .   #','# $ # #','#  @ #','# $ . #','#    ##','#######'],['########','# .    #','# $ ## #','#   @  #','# ## $ #','#    . #','########'],['########','#   .  #','#   $  #','# .@$  #','#      #','#      #','########'],['########','# . .  #','# $    #','##  $  #','#   @  #','#      #','########'],['########','# .  . #','# $  $ #','#  ##  #','#   @  #','#      #','########']];
 function create(kind,seed=Date.now(),level=1){if(!ids.includes(kind)||!Number.isInteger(level)||level<1||level>CATALOG[kind][2])throw Error('游戏或难度不存在');seed=seed>>>0;const r=rng(seed),b={version:1,id:kind+'-'+seed,kind,seed,level,moves:[],won:false,over:false,score:0};
  if(kind==='mines'){b.cols=[7,8,9][level-1];b.rows=b.cols;b.bombs=[7,11,16][level-1];b.cells=Array(b.cols*b.rows).fill(0);b.open=Array(b.cells.length).fill(false);b.flags=Array(b.cells.length).fill(false);b.started=false;}
  if(kind==='sokoban'){let map=boxes[(level-1)%boxes.length];if(level>6)map=map.map(row=>[...row].reverse().join(''));b.cols=map[0].length;b.rows=map.length;b.cells=[...map.join('')].map(ch=>ch==='#'?1:0);b.goals=[];b.crates=[];[...map.join('')].forEach((ch,i)=>{if(ch==='.')b.goals.push(i);if(ch==='$')b.crates.push(i);if(ch==='@')b.player=i;});}
  if(kind==='slide'){b.cols=level===1?3:4;b.rows=b.cols;b.cells=Array.from({length:b.cols*b.rows},(_,i)=>(i+1)%(b.cols*b.rows));let last=-1;for(let i=0;i<80+level*80;i++){const z=b.cells.indexOf(0),ns=adjacent(b,z).filter(n=>n!==last),next=ns[Math.floor(r()*ns.length)];[b.cells[z],b.cells[next]]=[b.cells[next],0];last=z;}if(b.cells.every((v,i)=>v===(i+1)%b.cells.length)){const z=b.cells.indexOf(0),n=adjacent(b,z)[0];[b.cells[z],b.cells[n]]=[b.cells[n],0];}}
  if(kind==='lights'){b.cols=level+3;b.rows=b.cols;b.cells=Array(b.cols*b.rows).fill(1);for(const i of shuffle(b.cells.map((_,i)=>i),r).slice(0,5+level*3))toggle(b,i);if(b.cells.every(Boolean))toggle(b,0);}
  if(kind==='hanoi'){b.cols=3;b.rows=1;b.towers=[Array.from({length:level+2},(_,i)=>level+2-i),[],[]];}
  if(kind==='code'){b.cols=4;b.rows=8;b.colors=level+4;b.secret=Array.from({length:4},()=>Math.floor(r()*b.colors));b.guesses=[];}
  if(kind==='reversi'){b.cols=level===1?6:8;b.rows=b.cols;b.cells=Array(b.cols*b.rows).fill(0);const n=b.cols,m=n/2;b.cells[(m-1)*n+m-1]=2;b.cells[m*n+m]=2;b.cells[(m-1)*n+m]=1;b.cells[m*n+m-1]=1;b.turn=1;}
  if(kind==='connect'){b.cols=7;b.rows=6;b.cells=Array(42).fill(0);b.turn=1;}
  if(kind==='peg'){b.cols=b.rows=7;b.cells=Array.from({length:49},(_,i)=>{const x=i%7,y=Math.floor(i/7);return(x<2||x>4)&&(y<2||y>4)?-1:i===24?0:1;});}
  if(kind==='maze'){const n=9+level*2;b.cols=b.rows=n;b.cells=Array(n*n).fill(1);b.player=n+1;b.cells[b.player]=0;const stack=[b.player];while(stack.length){const i=stack.at(-1),x=i%n,y=Math.floor(i/n),choices=shuffle([[2,0],[-2,0],[0,2],[0,-2]],r).filter(([dx,dy])=>x+dx>0&&x+dx<n-1&&y+dy>0&&y+dy<n-1&&b.cells[i+dy*n+dx]);if(!choices.length){stack.pop();continue;}const[dx,dy]=choices[0],j=i+dy*n+dx;b.cells[i+dy*n/2+dx/2]=b.cells[j]=0;stack.push(j);}b.exit=(n-2)*n+n-2;b.keys=shuffle(b.cells.map((v,i)=>!v&&i!==b.player&&i!==b.exit?i:-1).filter(i=>i>=0),r).slice(0,3).sort((a,c)=>a-c);b.collected=[];}
  if(kind==='ludo'){b.cols=b.rows=14;b.planes=[[-1,-1,-1,-1],[-1,-1,-1,-1]];b.die=0;b.rng=seed||1;b.turn=0;b.last='轮到你掷骰子';}
  if(kind==='trail'){b.cols=16;b.rows=9;b.platforms=[{x:0,y:286,w:230}];let x=230;for(let i=0;i<6+level;i++){x+=48+Math.floor(r()*43);const w=145+Math.floor(r()*80),y=255+Math.floor(r()*55);b.platforms.push({x,y,w});x+=w;}b.width=x+120;b.stars=b.platforms.slice(1).map((p,i)=>({x:p.x+p.w*.5,y:p.y-42,id:i}));b.enemies=level>=3?b.platforms.slice(2,-1).filter((_,i)=>i%2===0).map(p=>({x:p.x+42,y:p.y,from:p.x+24,to:p.x+p.w-24})):[];b.player={x:45,y:286,vx:0,vy:0,ground:true};b.checkpoint=0;b.collected=[];b.lives=3;b.frames=0;b.jumpHeld=false;b.invulnerable=0;}
  return b;
 }
 function adjacent(b,i,diagonal=false){const x=i%b.cols,y=Math.floor(i/b.cols),out=[];for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++)if((dx||dy)&&(diagonal||!dx||!dy)&&x+dx>=0&&x+dx<b.cols&&y+dy>=0&&y+dy<b.rows)out.push(i+dy*b.cols+dx);return out;}
 function toggle(b,i){for(const j of [i,...adjacent(b,i)])b.cells[j]=1-b.cells[j];}
 function direction(b,d){const delta={U:[0,-1],D:[0,1],L:[-1,0],R:[1,0]}[d];if(!delta)return-1;const x=b.player%b.cols+delta[0],y=Math.floor(b.player/b.cols)+delta[1];return x<0||y<0||x>=b.cols||y>=b.rows?-1:y*b.cols+x;}
 function flips(b,i,who){if(b.cells[i])return[];const found=[];for(const[dx,dy]of [[1,0],[-1,0],[0,1],[0,-1],[1,1],[-1,-1],[1,-1],[-1,1]]){const line=[];let x=i%b.cols+dx,y=Math.floor(i/b.cols)+dy;while(x>=0&&y>=0&&x<b.cols&&y<b.rows&&b.cells[y*b.cols+x]===3-who){line.push(y*b.cols+x);x+=dx;y+=dy;}if(line.length&&x>=0&&y>=0&&x<b.cols&&y<b.rows&&b.cells[y*b.cols+x]===who)found.push(...line);}return found;}
 const legal=(b,who)=>b.cells.map((_,i)=>i).filter(i=>flips(b,i,who).length);
 function placeReversi(b,i,who){const f=flips(b,i,who);if(!f.length)return false;b.cells[i]=who;f.forEach(j=>b.cells[j]=who);return true;}
 function lineWin(b,who){for(let i=0;i<b.cells.length;i++)if(b.cells[i]===who)for(const[dx,dy]of [[1,0],[0,1],[1,1],[-1,1]]){let count=1,x=i%b.cols,y=Math.floor(i/b.cols);while(count<4){x+=dx;y+=dy;if(x<0||y<0||x>=b.cols||y>=b.rows||b.cells[y*b.cols+x]!==who)break;count++;}if(count===4)return true;}return false;}
 function drop(b,col,who){for(let y=b.rows-1;y>=0;y--)if(!b.cells[y*b.cols+col]){b.cells[y*b.cols+col]=who;return y*b.cols+col;}return-1;}
 function connectChoice(b){const moves=Array.from({length:7},(_,i)=>i).filter(i=>!b.cells[i]),order=[3,2,4,1,5,0,6].filter(i=>moves.includes(i));function search(depth,who,alpha,beta){if(lineWin(b,2))return 10000+depth;if(lineWin(b,1))return-10000-depth;const cols=order.filter(i=>!b.cells[i]);if(!depth||!cols.length)return b.cells.reduce((n,v,i)=>n+(v===2?1:v===1?-1:0)*(4-Math.abs(i%7-3)),0);let best=who===2?-Infinity:Infinity;for(const col of cols){const i=drop(b,col,who),score=search(depth-1,3-who,alpha,beta);b.cells[i]=0;best=who===2?Math.max(best,score):Math.min(best,score);if(who===2)alpha=Math.max(alpha,best);else beta=Math.min(beta,best);if(beta<=alpha)break;}return best;}let best=-Infinity,pick=order[0];for(const c of order){const i=drop(b,c,2),v=search(b.level,1,-Infinity,Infinity);b.cells[i]=0;if(v>best){best=v;pick=c;}}return pick;}
 function pegMoves(b){const out=[];b.cells.forEach((v,i)=>{if(v!==1)return;for(const d of ['U','D','L','R']){const from={...b,player:i},mid=direction(from,d),to=mid<0?-1:direction({...b,player:mid},d);if(to>=0&&b.cells[mid]===1&&b.cells[to]===0)out.push([i,to]);}});return out;}
 function feedback(secret,guess){let exact=0,total=0;for(let i=0;i<4;i++)if(secret[i]===guess[i])exact++;for(let c=0;c<7;c++)total+=Math.min(secret.filter(x=>x===c).length,guess.filter(x=>x===c).length);return{exact,near:total-exact};}
 function dice(b){b.rng=(Math.imul(b.rng,1664525)+1013904223)>>>0;return 1+Math.floor(b.rng/4294967296*6);}
 function flights(b,who,die){return b.planes[who].map((p,i)=>p<0?die===6?i:-1:p<56&&p+die<=56?i:-1).filter(i=>i>=0);}
 function fly(b,who,i,die){let p=b.planes[who][i];p=p<0?0:p+die;if(p<52&&p>0&&p%4===0)p=Math.min(52,p+4);if(p===18||p===20)p=30;b.planes[who][i]=p;if(p<52){const global=(p+who*26)%52,safe=[0,13,26,39].includes(global);if(!safe)b.planes[1-who].forEach((q,j)=>{if(q>=0&&q<52&&(q+(1-who)*26)%52===global)b.planes[1-who][j]=-1;});}if(b.planes[who].every(p=>p===56)){b.over=true;b.won=who===0;}return p;}
 function opponentFlight(b){let rolls=0;do{const die=dice(b),opts=flights(b,1,die);if(opts.length){opts.sort((a,c)=>b.level===1?a-c:b.planes[1][c]-b.planes[1][a]);fly(b,1,opts[0],die);}b.last='伙伴掷到 '+die+(opts.length?'，移动了一架飞机。':'，暂时没有可走的飞机。');rolls++;if(die!==6)break;}while(!b.over&&rolls<6);b.die=0;b.turn=0;}
 function trailStep(b,a){const p=b.player;for(let f=0;f<a.frames&&!b.over;f++){b.frames++;b.invulnerable=Math.max(0,b.invulnerable-1);if(b.frames>=18000){b.over=true;break;}const oldY=p.y;p.vx=a.dir*3.25;if(a.jump&&!b.jumpHeld&&p.ground){p.vy=-12;p.ground=false;}b.jumpHeld=a.jump;p.x=Math.max(9,Math.min(b.width-9,p.x+p.vx));p.vy=Math.min(12,p.vy+.48);p.y+=p.vy;p.ground=false;for(let i=0;i<b.platforms.length;i++){const platform=b.platforms[i];if(p.vy>=0&&oldY<=platform.y+.1&&p.y>=platform.y&&p.x+9>=platform.x&&p.x-9<=platform.x+platform.w){p.y=platform.y;p.vy=0;p.ground=true;b.checkpoint=i;break;}}for(const star of b.stars)if(!b.collected.includes(star.id)&&Math.hypot(p.x-star.x,p.y-17-star.y)<24)b.collected.push(star.id);let hit=p.y>405;for(const e of b.enemies){const ex=e.from+(Math.sin(b.frames/54+e.x)+1)*.5*(e.to-e.from);if(!b.invulnerable&&Math.abs(ex-p.x)<19&&Math.abs(e.y-12-(p.y-15))<22)hit=true;}if(hit){b.lives--;if(!b.lives){b.over=true;break;}const platform=b.platforms[b.checkpoint];p.x=platform.x+15;p.y=platform.y;p.vy=0;p.ground=true;b.invulnerable=75;}const last=b.platforms.at(-1);if(p.x>=last.x+last.w-36&&p.ground){b.won=b.over=true;}b.score=b.collected.length;}}
 function apply(b,a){if(b.over)return false;const i=a.i,valid=Number.isInteger(i)&&i>=0&&i<(b.cells?.length||0);let changed=false;
  if(b.kind==='ludo'&&a.type==='roll'){if(b.die)return false;b.die=dice(b);b.last='你掷到 '+b.die+'。请选择亮着的飞机。';if(!flights(b,0,b.die).length){b.last='没有可以移动的飞机。';opponentFlight(b);}return true;}
  if(b.kind==='ludo'&&a.type==='plane'){if(!b.die||!flights(b,0,b.die).includes(a.i))return false;const die=b.die;fly(b,0,a.i,die);b.die=0;if(!b.over){if(die!==6)opponentFlight(b);else b.last='掷到 6，可以再掷一次。';}return true;}
  if(b.kind==='trail'&&a.type==='run'){if(![-1,0,1].includes(a.dir)||typeof a.jump!=='boolean'||!Number.isInteger(a.frames)||a.frames<1||a.frames>60||b.frames+a.frames>18000)return false;trailStep(b,a);return true;}
  if(b.kind==='mines'&&valid&&['open','flag'].includes(a.type)){if(a.type==='flag'){if(b.open[i])return false;b.flags[i]=!b.flags[i];return true;}if(b.flags[i]||b.open[i])return false;if(!b.started){const forbidden=[i,...adjacent(b,i,true)],pool=shuffle(b.cells.map((_,j)=>j).filter(j=>!forbidden.includes(j)),rng(b.seed));for(const j of pool.slice(0,b.bombs))b.cells[j]=-1;for(let j=0;j<b.cells.length;j++)if(b.cells[j]!==-1)b.cells[j]=adjacent(b,j,true).filter(k=>b.cells[k]===-1).length;b.started=true;}if(b.cells[i]===-1){b.open[i]=true;b.over=true;return true;}const queue=[i];while(queue.length){const j=queue.pop();if(b.open[j]||b.flags[j])continue;b.open[j]=true;if(b.cells[j]===0)for(const k of adjacent(b,j,true))if(!b.open[k])queue.push(k);}b.won=b.cells.every((v,j)=>v===-1||b.open[j]);b.over=b.won;changed=true;}
  if(b.kind==='slide'&&valid&&a.type==='cell'){const z=b.cells.indexOf(0);if(!adjacent(b,z).includes(i))return false;[b.cells[z],b.cells[i]]=[b.cells[i],0];b.won=b.cells.every((v,j)=>v===(j+1)%b.cells.length);changed=true;}
  if(b.kind==='lights'&&valid&&a.type==='cell'){toggle(b,i);b.won=b.cells.every(Boolean);changed=true;}
  if(['sokoban','maze'].includes(b.kind)&&a.type==='move'){const to=direction(b,a.dir);if(to<0||b.cells[to])return false;if(b.kind==='sokoban'){if(b.crates.includes(to)){const beyond=direction({...b,player:to},a.dir);if(beyond<0||b.cells[beyond]||b.crates.includes(beyond))return false;b.crates[b.crates.indexOf(to)]=beyond;}b.player=to;b.won=b.crates.every(j=>b.goals.includes(j));}else{b.player=to;if(b.keys.includes(to)&&!b.collected.includes(to))b.collected.push(to);b.won=to===b.exit&&b.collected.length===b.keys.length;}changed=true;}
  if(b.kind==='hanoi'&&a.type==='ring'){if(![0,1,2].includes(a.from)||![0,1,2].includes(a.to)||a.from===a.to)return false;const from=b.towers[a.from],to=b.towers[a.to];if(!from.length||to.length&&to.at(-1)<from.at(-1))return false;to.push(from.pop());b.won=b.towers[2].length===b.level+2;changed=true;}
  if(b.kind==='code'&&a.type==='guess'){if(!Array.isArray(a.colors)||a.colors.length!==4||a.colors.some(v=>!Number.isInteger(v)||v<0||v>=b.colors))return false;const score=feedback(b.secret,a.colors);b.guesses.push({colors:[...a.colors],...score});b.won=score.exact===4;b.over=b.won||b.guesses.length>=8;changed=true;}
  if(b.kind==='peg'&&a.type==='jump'){if(!pegMoves(b).some(([from,to])=>from===a.from&&to===a.to))return false;b.cells[a.from]=0;b.cells[(a.from+a.to)/2]=0;b.cells[a.to]=1;b.won=b.cells.filter(v=>v===1).length===1;b.over=b.won||!pegMoves(b).length;changed=true;}
  if(b.kind==='reversi'&&valid&&a.type==='cell'){if(!placeReversi(b,i,1))return false;while(true){const opts=legal(b,2);if(opts.length){opts.sort((x,y)=>{const score=j=>flips(b,j,2).length+([0,b.cols-1,b.cells.length-b.cols,b.cells.length-1].includes(j)?50:0);return score(y)-score(x)||x-y;});placeReversi(b,opts[0],2);}const human=legal(b,1);if(human.length)break;if(!legal(b,2).length){b.over=true;b.won=b.cells.filter(x=>x===1).length>b.cells.filter(x=>x===2).length;b.draw=b.cells.filter(x=>x===1).length===b.cells.filter(x=>x===2).length;break;}}changed=true;}
  if(b.kind==='connect'&&a.type==='column'){if(!Number.isInteger(a.col)||a.col<0||a.col>=7||b.cells[a.col])return false;drop(b,a.col,1);if(lineWin(b,1)){b.won=b.over=true;}else if(b.cells.slice(0,7).every(Boolean)){b.over=true;b.draw=true;}else{drop(b,connectChoice(b),2);if(lineWin(b,2))b.over=true;else if(b.cells.slice(0,7).every(Boolean)){b.over=true;b.draw=true;}}changed=true;}
  if(changed){if(b.won)b.over=true;b.score=b.kind==='maze'?b.collected.length:b.kind==='reversi'?b.cells.filter(v=>v===1).length:b.kind==='mines'?b.open.filter(Boolean).length:0;}return changed;
 }
 function command(b,a){if(b.moves.length>=4000)throw Error('这一局已走了很多步，可以撤销或重新开始');const action=normalize(a);if(!apply(b,action))return false;const last=b.moves.at(-1);if(action.type==='run'&&last?.type==='run'&&last.dir===action.dir&&last.jump===action.jump&&last.frames+action.frames<=60)last.frames+=action.frames;else b.moves.push(action);return true;}
 function normalize(a){if(!a||typeof a!=='object')throw Error('游戏操作格式错误');const out={type:a.type};if(['open','flag','cell','plane'].includes(a.type))out.i=a.i;else if(a.type==='move')out.dir=a.dir;else if(['ring','jump'].includes(a.type)){out.from=a.from;out.to=a.to;}else if(a.type==='guess')out.colors=Array.isArray(a.colors)?a.colors.slice():null;else if(a.type==='column')out.col=a.col;else if(a.type==='run'){out.dir=a.dir;out.jump=a.jump;out.frames=a.frames;}else if(a.type!=='roll')throw Error('未知游戏操作');return out;}
 function replay(kind,seed,level,moves){const b=create(kind,seed,level);for(const a of moves)if(!command(b,a))throw Error('棋局含有无法执行的一步');return b;}
 function clean(x){if(!x||x.version!==1||!Number.isInteger(x.seed)||x.seed<0||x.seed>4294967295||!Array.isArray(x.moves)||x.moves.length>4000)throw Error('小游戏存档格式错误');if(x.kind==='trail'&&x.moves.reduce((n,a)=>n+(Number.isInteger(a.frames)?a.frames:18001),0)>18000)throw Error('远足记录太长');const b=replay(x.kind,x.seed,x.level,x.moves);for(const k of Object.keys(b))if(JSON.stringify(x[k])!==JSON.stringify(b[k]))throw Error('小游戏状态与操作记录不一致：'+k);return b;}
 function undo(b){if(!b.moves.length)return false;const next=replay(b.kind,b.seed,b.level,b.moves.slice(0,-1));for(const k of Object.keys(b))delete b[k];Object.assign(b,next);return true;}
 return{CATALOG,ids,create,command,clean,undo,adjacent,flips,legal,pegMoves,feedback,direction,lineWin,flights};
});
