(function(root){'use strict';const F=root.WitchFestival,colors=['#a65758','#d4ab59','#799267','#739fac','#9784b2','#c58d65','#71948e'],el=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
 function mount(host,{saved,onChange,onExit,onNew,onFinish}){if(saved.kind==='trail')return mountTrail(host,{saved,onChange,onExit,onNew,onFinish});let b=F.clean(saved),selected=null,flag=false,guess=[0,1,2,3],notified=false,start=null,suppressClick=false;const wrap=el('div',undefined,'mini-game festival-game'),board=el('div',undefined,'pocket-board festival-board'),tools=el('div',undefined,'mini-toolbar festival-tools'),status=el('p','','pocket-status'),hint=el('p',F.CATALOG[b.kind][1],'hint');board.tabIndex=0;board.setAttribute('aria-label',F.CATALOG[b.kind][0]+'棋盘');status.setAttribute('role','status');wrap.append(hint,status,board,tools);host.append(wrap);
  const button=(label,fn,cls='')=>{const e=el('button',label,cls);e.type='button';e.onclick=fn;return e;};
  function changed(){onChange(b);if(b.over&&!notified){notified=true;onFinish(b.kind,b);}render();}
  function act(a){try{if(F.command(b,a)){selected=null;changed();}else status.textContent='这一步走不通，换一个位置试试。';}catch(e){status.textContent=e.message;}}
  function move(dir){if(b.kind==='slide'){const i=F.direction({...b,player:b.cells.indexOf(0)},dir);act({type:'cell',i});}else act({type:'move',dir});}
  function dpad(){const pad=el('div',undefined,'direction-pad');for(const[d,glyph,name]of [['U','↑','上'],['L','←','左'],['D','↓','下'],['R','→','右']]){const e=button(glyph,()=>move(d));e.dataset.dir=d;e.setAttribute('aria-label','向'+name+'移动');pad.append(e);}return pad;}
  function render(){board.replaceChildren();tools.replaceChildren();board.className='pocket-board festival-board f-'+b.kind;board.style.setProperty('--cols',b.cols);board.style.setProperty('--rows',b.rows);board.style.aspectRatio=b.cols+'/'+b.rows;const result=b.over?(b.won?'完成啦！':b.draw?'这一盘平局。':'这一盘结束了。可以撤销再想想。'):'';status.textContent=result||('第 '+b.level+' 档 · '+b.moves.length+' 步');
   if(b.kind==='ludo'){board.style.display='block';const cv=el('canvas');cv.width=cv.height=420;cv.style.width='100%';cv.setAttribute('aria-label','金色是你的飞机，蓝色是伙伴的飞机');board.append(cv);const c=cv.getContext('2d'),track=[];for(let x=0;x<14;x++)track.push([x,0]);for(let y=1;y<14;y++)track.push([13,y]);for(let x=12;x>=0;x--)track.push([x,13]);for(let y=12;y>0;y--)track.push([0,y]);c.fillStyle='#e2dac0';c.fillRect(0,0,420,420);track.forEach(([x,y],i)=>{c.fillStyle=['#bc9974','#819b91','#c1b478','#a69cab'][i%4];c.fillRect(x*28+14,y*28+14,25,25);});for(let who=0;who<2;who++)b.planes[who].forEach((p,i)=>{let xy=p<0?[84+i*63,who?252:140]:p>=52?[105+(p-52)*42,who?294:98]:track[(p+who*26)%52].map(n=>n*28+26);c.fillStyle=who?'#739eb0':'#e3b45d';c.beginPath();c.arc(xy[0]+(i%2)*3,xy[1]+Math.floor(i/2)*3,11,0,7);c.fill();c.fillStyle='#253b33';c.font='bold 13px sans-serif';c.textAlign='center';c.fillText(String(i+1),xy[0],xy[1]+5);});c.fillStyle='#455c4d';c.font='20px serif';c.fillText('你的机库',210,184);c.fillText('伙伴的机库',210,230);c.font='16px sans-serif';c.fillText('入港 '+b.planes[0].filter(p=>p===56).length+' / 4',210,60);if(!b.over){const roll=button(b.die?'点数 '+b.die:'掷骰子',()=>act({type:'roll'}));roll.disabled=!!b.die;tools.append(roll);const opts=F.flights(b,0,b.die);for(let i=0;i<4;i++){const go=button('飞机 '+(i+1),()=>act({type:'plane',i}));go.disabled=!b.die||!opts.includes(i);tools.append(go);}}status.textContent=result||b.last;}
   else if(b.kind==='hanoi'){board.style.aspectRatio='1.6';b.towers.forEach((tower,i)=>{const cell=button('',()=>{if(selected===null){if(tower.length)selected=i;render();}else if(selected===i){selected=null;render();}else act({type:'ring',from:selected,to:i});},'hanoi-tower');cell.setAttribute('aria-label',['左','中','右'][i]+'塔，'+tower.length+' 只月环');cell.setAttribute('aria-pressed',String(selected===i));const pole=el('span','','hanoi-pole');cell.append(pole);[...tower].reverse().forEach(size=>{const ring=el('span',String(size),'hanoi-ring');ring.style.width=(24+size*11)+'%';ring.style.background=colors[size%colors.length];cell.append(ring);});board.append(cell);});if(!b.over)status.textContent=(selected===null?'选一座塔，拿起最上面的月环':'再选一座塔，放下月环')+' · '+b.moves.length+' 步';}
   else if(b.kind==='code'){board.style.aspectRatio='auto';b.guesses.forEach((row,i)=>{const line=el('div',undefined,'code-row');line.append(el('small',String(i+1)));row.colors.forEach(c=>{const bead=el('span',String(c+1),'color-bead');bead.style.background=colors[c];line.append(bead);});line.append(el('span','●'.repeat(row.exact)+'○'.repeat(row.near),'code-feedback'));board.append(line);});if(!b.over){const line=el('div',undefined,'code-row current-guess');line.append(el('small','→'));guess.forEach((c,i)=>{const bead=button(String(c+1),()=>{guess[i]=(c+1)%b.colors;render();},'color-bead');bead.style.background=colors[c];bead.setAttribute('aria-label','第 '+(i+1)+' 颗颜色 '+(c+1)+'，点击换色');line.append(bead);});board.append(line);tools.append(button('确认这一组',()=>act({type:'guess',colors:guess})));}else board.append(el('p','这一局的色珠：'+b.secret.map(c=>c+1).join(' · ')));status.textContent=result||('已猜 '+b.guesses.length+' / 8 组 · 可重复颜色');}
   else{const jumpTargets=b.kind==='peg'&&selected!==null?F.pegMoves(b).filter(m=>m[0]===selected).map(m=>m[1]):[],legal=b.kind==='reversi'&&!b.over?F.legal(b,1):[];b.cells.forEach((v,i)=>{let text='',cls='festival-cell',label=`${Math.floor(i/b.cols)+1} 行 ${i%b.cols+1} 列`,action=null;
    if(b.kind==='mines'){cls+=b.open[i]?' opened':'';text=b.flags[i]?'⚑':b.open[i]?v===-1?'✹':v||'':b.over&&v===-1?'✹':'';label+='，'+(b.flags[i]?'已标旗':b.open[i]?v===-1?'雷':v+' 颗相邻雷':'未翻开');action=()=>act({type:flag?'flag':'open',i});}
    if(b.kind==='slide'){text=v||'';cls+=v?'':' blank';label+='，'+(v||'空位');action=()=>act({type:'cell',i});}
    if(b.kind==='lights'){text=v?'✦':'·';cls+=v?' lit':'';label+=v?'，亮灯':'，暗灯';action=()=>act({type:'cell',i});}
    if(b.kind==='sokoban'){text=v?'':b.player===i?'●':b.crates.includes(i)?'▣':b.goals.includes(i)?'◎':'';cls+=v?' wall':b.goals.includes(i)?' goal':'';label+=v?'墙':b.player===i?'伙伴':b.crates.includes(i)?'松果箱':b.goals.includes(i)?'垫子':'空地';action=()=>{const dirs=['U','D','L','R'],dir=dirs.find(d=>F.direction(b,d)===i);if(dir)move(dir);};}
    if(b.kind==='maze'){text=b.player===i?'●':b.exit===i?'★':b.keys.includes(i)&&!b.collected.includes(i)?'⚿':'';cls+=v?' wall':'';}
    if(b.kind==='reversi'){text=v?'●':legal.includes(i)?'·':'';cls+=' disk-'+v;label+=v===1?'黑棋':v===2?'白棋':legal.includes(i)?'可落子':'空格';action=()=>act({type:'cell',i});}
    if(b.kind==='connect'){text='●';cls+=' disk-'+v;label+='，'+(v===1?'你的金子':v===2?'伙伴的蓝子':'空位');action=()=>act({type:'column',col:i%b.cols});}
    if(b.kind==='peg'){text=v===1?'●':v===0?'○':'';cls+=v===-1?' void':jumpTargets.includes(i)?' target':'';label+=v===1?'月石':v===0?'空穴':'空白';action=()=>{if(v===1){selected=selected===i?null:i;render();}else if(v===0&&selected!==null)act({type:'jump',from:selected,to:i});};}
    const cell=action?button(String(text),action,cls):el('span',String(text),cls);cell.setAttribute('aria-label',label);cell.dataset.index=i;if(selected===i)cell.classList.add('selected');if(b.kind==='mines')cell.oncontextmenu=e=>{e.preventDefault();act({type:'flag',i});};if(b.kind==='peg'&&v===-1)cell.disabled=true;board.append(cell);
   });}
   if(b.kind==='mines'){const toggle=button(flag?'⚑ 标旗中':'翻开格子',()=>{flag=!flag;render();});toggle.setAttribute('aria-pressed',String(flag));tools.append(toggle);if(!b.over)status.textContent='雷 '+b.bombs+' · 旗 '+b.flags.filter(Boolean).length+' · 首点安全';}
   if(['sokoban','maze','slide'].includes(b.kind))tools.append(dpad());if(b.kind==='maze'&&!b.over)status.textContent='钥匙 '+b.collected.length+' / 3 · '+b.moves.length+' 步';
   if(b.kind==='peg'&&!b.over)status.textContent='剩余 '+b.cells.filter(v=>v===1).length+' 颗月石';
   if(b.kind==='reversi')status.textContent=(result||'你执黑，点小圆点落子')+' · 黑 '+b.cells.filter(v=>v===1).length+' / 白 '+b.cells.filter(v=>v===2).length;
   const undo=button(b.kind==='reversi'||b.kind==='connect'?'撤销一轮':'撤销一步',()=>{if(F.undo(b)){selected=null;notified=false;changed();}});undo.disabled=!b.moves.length;tools.append(undo,button('换一局 / 难度',onNew),button('收起，稍后继续',onExit));root.WitchPlayLayout?.schedule();
  }
  function key(e){const dir={ArrowUp:'U',ArrowDown:'D',ArrowLeft:'L',ArrowRight:'R',w:'U',s:'D',a:'L',d:'R'}[e.key];if(dir&&['sokoban','maze','slide'].includes(b.kind)){e.preventDefault();e.stopPropagation();move(dir);}}
  wrap.addEventListener('keydown',key);if(['sokoban','maze','slide'].includes(b.kind)){board.addEventListener('click',e=>{if(suppressClick){e.preventDefault();e.stopImmediatePropagation();suppressClick=false;}},true);board.onpointerdown=e=>{suppressClick=false;start=[e.clientX,e.clientY];};board.onpointerup=e=>{if(!start)return;const dx=e.clientX-start[0],dy=e.clientY-start[1];start=null;if(Math.max(Math.abs(dx),Math.abs(dy))<22)return;suppressClick=true;move(Math.abs(dx)>Math.abs(dy)?dx>0?'R':'L':dy>0?'D':'U');};board.onpointercancel=()=>start=null;}
  render();return{getState:()=>b,destroy(){wrap.removeEventListener('keydown',key);host.replaceChildren();}};
 }
 function mountTrail(host,{saved,onChange,onExit,onNew,onFinish}){const b=F.clean(saved),wrap=el('div',undefined,'mini-game festival-game'),board=el('canvas',undefined,'pocket-board festival-board f-trail'),tools=el('div',undefined,'mini-toolbar festival-tools'),status=el('p','','pocket-status'),help=el('p',F.CATALOG.trail[1],'hint');board.width=640;board.height=360;board.style.setProperty('--cols',16);board.style.setProperty('--rows',9);board.style.aspectRatio='16/9';board.tabIndex=0;board.setAttribute('aria-label','横版远足：方向键或屏幕按钮移动，空格跳跃');wrap.append(help,status,board,tools);host.append(wrap);let dir=0,jump=false,paused=true,alive=true,last=0,raf=0,lastSave=0,notified=b.over;const button=(t,fn)=>{const e=el('button',t);e.onclick=fn;return e;},toggle=button('开始 / 继续',()=>{paused=!paused;toggle.textContent=paused?'继续远足':'暂停';board.focus();});
  for(const[d,label]of[[-1,'向左'],[1,'向右'],[0,'跳跃']]){const e=button(label,()=>{});e.className='trail-control';e.onpointerdown=ev=>{ev.preventDefault();e.setPointerCapture(ev.pointerId);if(d)dir=d;else jump=true;};e.onpointerup=e.onpointercancel=()=>{if(d)dir=0;else jump=false;};tools.append(e);}tools.append(toggle,button('重选关卡',onNew),button('收起，稍后继续',onExit));
  function keys(e){if(!['ArrowLeft','ArrowRight','a','d',' ','ArrowUp'].includes(e.key))return;e.preventDefault();const down=e.type==='keydown';if([' ','ArrowUp'].includes(e.key))jump=down;else dir=down?['ArrowLeft','a'].includes(e.key)?-1:1:0;}
  function release(){dir=0;jump=false;paused=true;toggle.textContent='继续远足';}wrap.addEventListener('keydown',keys);wrap.addEventListener('keyup',keys);window.addEventListener('blur',release);document.addEventListener('visibilitychange',release);
  function paint(){const c=board.getContext('2d'),offset=Math.max(0,Math.min(b.width-640,b.player.x-210));c.fillStyle='#aac2a0';c.fillRect(0,0,640,360);c.fillStyle='#708a69';for(let i=0;i<8;i++){c.beginPath();c.arc(i*130-offset*.2%130,340,105+(i%3)*20,Math.PI,0);c.fill();}c.save();c.translate(-offset,0);for(const p of b.platforms){c.fillStyle='#887255';c.fillRect(p.x,p.y,p.w,90);c.fillStyle='#6d925b';c.fillRect(p.x,p.y,p.w,9);c.fillStyle='#b3a37b';for(let i=10;i<p.w;i+=28)c.fillRect(p.x+i,p.y+21+(i%3)*5,10,3);}for(const s of b.stars)if(!b.collected.includes(s.id)){c.fillStyle='#f2d480';c.font='25px serif';c.fillText('✦',s.x-12,s.y+10);}for(const e of b.enemies){const x=e.from+(Math.sin(b.frames/54+e.x)+1)*.5*(e.to-e.from);c.fillStyle='#777685';c.beginPath();c.ellipse(x,e.y-10,15,11,0,0,7);c.fill();c.fillStyle='#eee0bd';c.fillRect(x-6,e.y-14,3,3);c.fillRect(x+4,e.y-14,3,3);}const p=b.player;c.globalAlpha=b.invulnerable&&Math.floor(b.frames/6)%2?.45:1;c.fillStyle='#765039';c.fillRect(p.x-8,p.y-5,6,5);c.fillRect(p.x+3,p.y-5,6,5);c.fillStyle='#a44f43';c.fillRect(p.x-10,p.y-26,20,22);c.fillStyle='#efd6ae';c.fillRect(p.x-7,p.y-38,14,13);c.fillStyle='#465a43';c.fillRect(p.x-14,p.y-40,28,5);c.beginPath();c.moveTo(p.x-10,p.y-40);c.lineTo(p.x+4,p.y-60);c.lineTo(p.x+11,p.y-40);c.fill();c.globalAlpha=1;const end=b.platforms.at(-1);c.fillStyle='#efe1b8';c.fillRect(end.x+end.w-32,end.y-70,3,70);c.fillStyle='#bd895b';c.fillRect(end.x+end.w-29,end.y-70,25,19);c.restore();status.textContent=(b.over?b.won?'到达营地！':'先休息一下，重新选关还能再来。':paused?'已暂停':'远足中')+' · ♥ '+b.lives+' · ✦ '+b.collected.length+' / '+b.stars.length;}
  function tick(t){if(!alive)return;raf=requestAnimationFrame(tick);if(!paused&&!document.hidden&&!b.over&&t-last>=15){const frames=Math.min(18000-b.frames,3,Math.max(1,Math.floor((t-last)/16.67)));F.command(b,{type:'run',dir,jump,frames});last=t;if(t-lastSave>700){onChange(b);lastSave=t;}if(b.over&&!notified){notified=true;onChange(b);onFinish('trail',b);}}else if(paused||document.hidden)last=t;paint();}
  paint();raf=requestAnimationFrame(tick);root.WitchPlayLayout?.schedule();return{getState:()=>b,destroy(){alive=false;cancelAnimationFrame(raf);wrap.removeEventListener('keydown',keys);wrap.removeEventListener('keyup',keys);window.removeEventListener('blur',release);document.removeEventListener('visibilitychange',release);host.replaceChildren();}};
 }
 root.WitchFestivalUI={mount};
})(globalThis);
