(function(root){
 'use strict';const G=root.WitchGames;
 const el=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
 const btn=(text,fn,cls='soft-button')=>{const e=el('button',text,cls);e.type='button';e.addEventListener('click',fn);return e;};
 function frame(host,state,options){let active=true;const status=el('p','','game-message');status.setAttribute('role','status');const body=el('div',undefined,'mini-game'),tools=el('div',undefined,'game-toolbar');host.replaceChildren(body);return{body,status,tools,get active(){return active;},save(){options.onChange?.(G.clone(state));},finish(done,text){if(done){status.textContent=text;if(!state.celebrated){state.celebrated=true;options.onFinish?.(state.kind,G.clone(state));this.save();}}},end(render){body.append(status,tools);tools.append(btn('换一局',()=>{const q=el('div',undefined,'game-confirm');q.append(el('p','换一局会收起当前这局的进度。'),btn('确认换一局',()=>options.onNew?.()),btn('继续这局',()=>q.remove()));tools.after(q);}),btn('先收好',()=>options.onExit?.(G.clone(state))));render();},destroy(){active=false;host.replaceChildren();},getState(){return G.clone(state);}};}
 function mountSudoku(host,{saved,...options}){
  const s=G.cleanSudoku(saved),f=frame(host,s,options);let selected=s.givens.findIndex(v=>!v),notes=false,errors=new Set();const intro=el('p','「这道数独我出好了。每行、每列和每个九宫格里，1 到 9 都只出现一次。慢慢来，我陪你。」','thought');const board=el('div',undefined,'sudoku-board');board.setAttribute('role','grid');board.setAttribute('aria-label','九宫数独');const pad=el('div',undefined,'number-pad'),progress=el('p','','game-progress');f.body.append(intro,progress,board,pad);
  function entry(v){if(G.enterSudoku(s,selected,v,notes)){errors=new Set(G.conflicts(s));f.save();render();}}
  for(let v=1;v<=9;v++)pad.append(btn(String(v),()=>entry(v),'number-key'));
  const note=btn('笔记：关',()=>{notes=!notes;render();}),clear=btn('擦掉这格',()=>entry(0)),hint=btn('给一点提示',()=>{const h=G.hintSudoku(s,selected);if(h){selected=h.index;errors.clear();f.status.textContent=h.text;f.save();render();}}),check=btn('帮我看看',()=>{const answer=G.solve(s.givens,1)[0];errors=new Set(s.values.flatMap((v,i)=>v&&v!==answer[i]?[i]:[]));f.status.textContent=errors.size?'有 '+errors.size+' 格可以再想想，已经轻轻标出来了。':'已填的数字都对得上，继续慢慢来。';render();});f.tools.append(note,clear,hint,check);
  function render(){if(!f.active)return;const done=G.isSudokuDone(s),blank=s.givens.filter(v=>!v).length,filled=s.values.filter((v,i)=>v&&!s.givens[i]).length;progress.textContent=(s.difficulty==='easy'?'轻松题':'标准题')+' · 已填 '+filled+' / '+blank+' 格';board.replaceChildren();note.textContent='笔记：'+(notes?'开':'关');note.setAttribute('aria-pressed',String(notes));[clear,hint,check,...pad.children].forEach(e=>e.disabled=done);s.values.forEach((v,i)=>{const r=Math.floor(i/9),c=i%9,e=btn('',()=>{selected=i;render();},'sudoku-cell');e.setAttribute('role','gridcell');e.setAttribute('aria-label',`第 ${r+1} 行第 ${c+1} 列，${v||'空格'}${s.givens[i]?'，题目给定':''}`);e.setAttribute('aria-selected',String(selected===i));e.tabIndex=selected===i?0:-1;e.classList.toggle('given',!!s.givens[i]);e.classList.toggle('chosen',selected===i);e.classList.toggle('related',Math.floor(selected/9)===r||selected%9===c);e.classList.toggle('wrong',errors.has(i));if(c===2||c===5)e.classList.add('box-right');if(r===2||r===5)e.classList.add('box-bottom');if(v)e.textContent=v;else if(s.notes[i]){const small=el('span',undefined,'sudoku-notes');for(let n=1;n<=9;n++)small.append(el('span',s.notes[i]&(1<<(n-1))?String(n):''));e.append(small);}e.addEventListener('keydown',event=>{if(/^[1-9]$/.test(event.key)){event.preventDefault();entry(Number(event.key));}else if(['Backspace','Delete','0'].includes(event.key)){event.preventDefault();entry(0);}else{const d={ArrowLeft:-1,ArrowRight:1,ArrowUp:-9,ArrowDown:9}[event.key];if(d){event.preventDefault();selected=(selected+d+81)%81;render();board.children[selected].focus();}}});board.append(e);});f.finish(done,'「你解出来了！这张小小的题纸，今天属于我们。」');}
  f.end(render);return f;
 }
 function mountPuzzle(host,{saved,...options}){
  const s=G.cleanPuzzle(saved),f=frame(host,s,options);let selected=-1,showPreview=false;const picture=new Image();picture.src='assets/'+(s.image==='courtyard'?'courtyard-v1.png':'cottage-empty-v1.png');const intro=el('p','「照片被风吹散了。点一块，再点另一块，就能交换位置。把我们的地方慢慢拼回来吧。」','thought'),board=el('div',undefined,'puzzle-board'),preview=el('canvas',undefined,'puzzle-preview');preview.width=preview.height=600;preview.hidden=true;board.style.setProperty('--pieces',s.size);board.setAttribute('aria-label','交换拼片拼图');const progress=el('p','','game-progress');f.body.append(intro,progress,board,preview);f.tools.append(btn('看看原图',()=>{showPreview=!showPreview;preview.hidden=!showPreview;draw(preview,0,1);}));
  function draw(canvas,tile,n){if(!picture.complete||!picture.naturalWidth)return;const c=canvas.getContext('2d'),w=picture.naturalWidth,top=picture.naturalHeight*.16;c.imageSmoothingEnabled=false;c.drawImage(picture,(tile%n)*w/n,top+Math.floor(tile/n)*w/n,w/n,w/n,0,0,canvas.width,canvas.height);}
  function render(){if(!f.active)return;const done=G.isPuzzleDone(s),correct=s.tiles.filter((v,i)=>v===i).length;progress.textContent=`${s.size} × ${s.size} · ${correct} / ${s.tiles.length} 块归位 · 交换 ${s.moves} 次`;board.replaceChildren();s.tiles.forEach((tile,i)=>{const e=btn('',()=>{if(done)return;if(selected<0){selected=i;render();return;}G.swapPuzzle(s,selected,i);selected=-1;f.save();render();},'puzzle-piece');e.setAttribute('aria-label',`第 ${i+1} 个位置，照片碎片 ${tile+1}`);e.classList.toggle('chosen',selected===i);e.classList.toggle('correct',done);const canvas=el('canvas');canvas.width=canvas.height=200;e.append(canvas);draw(canvas,tile,s.size);board.append(e);});f.finish(done,'「是这里！你看，灯和叶子都回到原来的位置了。」');}
  picture.addEventListener('load',()=>{render();draw(preview,0,1);});picture.addEventListener('error',()=>{if(f.active)f.status.textContent='照片暂时没有加载好，联网后再打开这幅拼图。';});f.end(render);return f;
 }
 function mountPairs(host,{saved,...options}){
  const s=G.cleanPairs(saved),f=frame(host,s,options);const symbols=['☾','✦','❀','♧','♬','♡'],names=['月亮','星星','小花','叶子','歌声','爱心'];let timer=null;const board=el('div',undefined,'pairs-board'),progress=el('p','','game-progress');f.body.append(el('p','「我把六对小图案藏起来了。一次翻两张，找找谁和谁是一对。」','thought'),progress,board);
  function schedule(){if(s.open.length===2&&timer===null)timer=setTimeout(()=>{timer=null;if(!f.active)return;const matched=G.resolvePair(s);f.status.textContent=matched?'「找到了，它们是一对！」':'「我记住那张的位置了，再试试。」';f.save();render();},800);}
  function render(){if(!f.active)return;progress.textContent=`找到 ${s.matched.length/2} / 6 对 · 翻过 ${s.moves} 轮`;board.replaceChildren();s.deck.forEach((v,i)=>{const visible=s.matched.includes(i)||s.open.includes(i),e=btn(visible?symbols[v]:'✧',()=>{if(G.flipPair(s,i)){f.save();render();}},'pair-card');e.disabled=s.matched.includes(i);e.classList.toggle('face-up',visible);e.classList.toggle('matched',s.matched.includes(i));e.setAttribute('aria-label',visible?`第 ${i+1} 张，${names[v]}${s.matched.includes(i)?'，已配对':''}`:`翻开第 ${i+1} 张卡片`);board.append(e);});f.finish(G.isPairsDone(s),'「都找齐啦。你的记性比我帽子里的小星星还好。」');schedule();}
  const destroy=f.destroy.bind(f);f.destroy=()=>{clearTimeout(timer);timer=null;destroy();};f.end(render);return f;
 }
 root.WitchGamesUI={mountSudoku,mountPuzzle,mountPairs};
})(globalThis);
