/* Small, persistent projects. Facts and material costs belong to the world. */
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.WitchHobbies=api;})(globalThis,function(){
 'use strict';const Letters=globalThis.WitchLetters||(typeof require==='function'?require('./letters.js'):null);
 const PROJECTS={
  sachet:{name:'缝一只香草香包',icon:'🌿',kind:'ornament',cost:'herbs',reward:'香草月亮香包',steps:[['把香草摊在窗台晾干','window','挑走折断的小梗，让叶片慢慢散出香气。'],['缝一个月牙小袋','desk','沿着画好的月牙缝针脚，留一个装叶子的小口。'],['装好香草，系上红绳','shelf','轻轻揉开干叶，装进去，再把最后的线头藏好。']]},
  birds:{name:'做一本鸟声手帐',icon:'🪶',kind:'book',reward:'小院鸟声手帐',steps:[['在窗边记录鸟声','window','听到什么就记什么。白天留意枝头，晚上也可以听夜鸟。'],['画下刚才的声音','desk','长长的叫声画成线，短短的叫声画成点。'],['装订鸟声小册子','desk','把观察的天气、时间与小小的声音一起订进书页。']]},
  pressed:{name:'收一本压花小册',icon:'🍀',kind:'book',cost:'herbs',reward:'香草压花小册',steps:[['挑选适合压平的叶子','desk','一份香草里，挑一片叶脉最清楚的，夹进吸水纸。'],['给叶片画一张图鉴','desk','顺着叶脉画线，在旁边记下它的气味。'],['把压好的叶片装入册中','shelf','在叶片下面写上这一天，让它保留小院的样子。']]},
  starlamp:{name:'折一盏纸星灯',icon:'⭐',kind:'ornament',reward:'窗边纸星灯',steps:[['沿着折痕做纸星星','desk','从手工纸盒里挑一张纸，先把五个角折出来。'],['给星星描上花纹','desk','添上细细的月牙和圆点，每一面都不太一样。'],['把纸星灯挂到窗边','window','穿好棉线，放入魔法小光点，看看影子落在哪里。']]},
  postcard:{name:'写张留给你的明信片',icon:'💌',kind:'book',reward:'留给你的明信片',steps:[['给今天画一张小插画','desk','从刚经历的小事、天气和梦种中，挑一件想画给你看的。'],['在插画背面写两句话','desk','不必写得很厉害。把今天真正在这里的事情留下就好。'],['贴上纸星邮票，收进信匣','shelf','这封信留在你们的收藏里，等你有空的时候打开。']]},
  jam:{name:'熬一小罐浆果酱',icon:'🍓',kind:'food',cost:'berries',reward:'手写标签的浆果酱',steps:[['清洗浆果，去掉小梗','fire','一份浆果倒进碗里，洗净后慢慢压碎。'],['小火熬一锅果酱','fire','沿着锅边慢慢搅，等颜色深下来，气味也甜起来。'],['装罐，画一张果酱标签','shelf','给罐子写好日期；留两份茶点，之后可以带到院里。']]}
 };
 const ids=Object.keys(PROJECTS),fresh=()=>({focus:null,projects:Object.fromEntries(ids.map(k=>[k,{stage:0,editions:0,paid:false,startedAt:null,completedAt:null,context:'',sourceIds:[],steps:[],draft:null}])),works:[]});
 function integer(v,min,max){if(!Number.isInteger(v)||v<min||v>max)throw Error('兴趣手册数值不正确');return v;}
 function text(v,max){if(typeof v!=='string'||v.length>max)throw Error('兴趣手册文字不正确');return v;}
 function refs(v){if(!Array.isArray(v)||v.length>8||v.some(x=>typeof x!=='string'||! /^[a-z]+-\d{1,10}$/.test(x)))throw Error('兴趣手册来历不正确');return [...v];}
 function clean(v){if(v===undefined||v===null)return fresh();const h=fresh();if(v.focus!==null&&!ids.includes(v.focus))throw Error('兴趣手册选择不正确');h.focus=v.focus;
  for(const k of ids){const p=v.projects?.[k];if(!p)throw Error('兴趣手册进度缺失');h.projects[k]={stage:integer(p.stage,0,2),editions:integer(p.editions,0,1000000),paid:p.paid===true,startedAt:p.startedAt===null?null:integer(p.startedAt,0,8640000000000000),completedAt:p.completedAt===null?null:integer(p.completedAt,0,8640000000000000),context:text(p.context,300),sourceIds:refs(p.sourceIds),steps:refs(p.steps),draft:Letters.cleanDraft(p.draft)};if(p.steps.length!==p.stage||(p.stage>0&&!p.paid))throw Error('兴趣步骤不一致');}
  if(!Array.isArray(v.works)||v.works.length>36)throw Error('兴趣收藏不正确');h.works=v.works.map(w=>{if(!ids.includes(w.project)||!/^keepsake-\d{1,10}$/.test(w.id))throw Error('兴趣作品不正确');return{id:w.id,project:w.project,edition:integer(w.edition,1,1000000),name:text(w.name,120),kind:PROJECTS[w.project].kind,text:text(w.text,700),at:integer(w.at,0,8640000000000000),sourceIds:refs(w.sourceIds),steps:refs(w.steps),...(w.project==='postcard'?{read:w.read===true}:{}),...(w.project==='postcard'&&w.letter?{letter:{from:text(w.letter.from,80),heading:text(w.letter.heading,120),body:text(w.letter.body,700),theme:['day','night','rain','fish','garden','kitchen','book','forest','neighbors','birds'].includes(w.letter.theme)?w.letter.theme:'day',sourceQuote:text(w.letter.sourceQuote||'',600),...(w.letter.sourceType?{sourceType:['life','dream','weather'].includes(w.letter.sourceType)?w.letter.sourceType:'weather',sourceAt:integer(w.letter.sourceAt,0,8640000000000000),sourceFact:text(w.letter.sourceFact||'',600),variant:integer(w.letter.variant||0,0,5)}:{})}}:{})};});if(new Set(h.works.map(w=>w.id)).size!==h.works.length)throw Error('兴趣作品重复');return h;
 }
 function available(s,k){const p=s.hobbies.projects[k],d=PROJECTS[k];return p.paid||!d.cost||s.home.pantry[d.cost]>0;}
 function rows(s,at){return ids.map(kind=>{const p=s.hobbies.projects[kind],d=PROJECTS[kind],unfinished=p.paid||p.stage>0,focused=s.hobbies.focus===kind;const reasons=[unfinished?'上次做到第 '+(p.stage+1)+' 步，想接着'+d.steps[p.stage][0]:focused?'你们把「'+d.name+'」写在近期的小愿望里':'想试试'+d.name];if(!available(s,kind))reasons.push('需要先从小院带回一份'+(d.cost==='herbs'?'香草':'浆果'));if(p.completedAt!==null&&at-p.completedAt<12*3600000)reasons.push('刚完成一件，先换个兴趣再回来');return{kind,score:(unfinished?42:16)+(focused?35:0)+(s.preferences.curiosity*10)-(p.completedAt!==null&&at-p.completedAt<12*3600000?15:0),eligible:available(s,kind)&&s.world.energy>=22,reasons};});}
 function spec(s,k){const d=PROJECTS[k],p=s.hobbies.projects[k],step=d.steps[p.stage];return{kind:k,title:step[0],detail:step[2]+' · '+d.name+'，第 '+(p.stage+1)+' / 3 步。',place:step[1],durationMs:([25,40,20][p.stage])*60000,projectStage:p.stage,projectEdition:p.editions+1};}
 function begin(s,a,now){const p=s.hobbies.projects[a.kind],d=PROJECTS[a.kind];if(a.projectStage!==p.stage||a.projectEdition!==p.editions+1)throw Error('兴趣计划已经变化，请重新打开手册');if(!available(s,a.kind))throw Error('材料不够，先去小院采一点吧');if(!p.paid){if(d.cost)s.home.pantry[d.cost]--;p.paid=true;p.startedAt=now;p.draft=a.kind==='postcard'?Letters.choose(s,now):null;p.sourceIds=p.draft?.sourceId?[p.draft.sourceId]:[];p.context='开始于'+s.world.weather+'的'+(s.world.hour>=19||s.world.hour<6?'夜晚':'白天');}a.decision.sourceIds=[...p.sourceIds,...p.steps];}
 function finish(s,a,at,id){const p=s.hobbies.projects[a.kind],d=PROJECTS[a.kind];if(p.stage!==a.projectStage||p.editions+1!==a.projectEdition)return null;p.steps.push(a.id);p.stage++;if(p.stage<3)return{done:false,text:'「'+d.name+'」完成第 '+p.stage+' 步，下一步是'+d.steps[p.stage][0]+'。',sources:[...p.sourceIds,a.id]};
  const w={id,project:a.kind,edition:p.editions+1,name:d.reward+' · 第 '+(p.editions+1)+' 件',kind:d.kind,text:p.context+'。她先'+d.steps[0][0]+'，接着'+d.steps[1][0]+'，最后'+d.steps[2][0]+'。'+(a.kind==='postcard'?'「把今天留在这里，等你慢慢来看。」':''),at,sourceIds:[...p.sourceIds],steps:[...p.steps]};if(a.kind==='postcard'){w.read=false;w.letter=Letters.build(s,p.draft,p.editions+1);}s.hobbies.works.push(w);s.hobbies.works=s.hobbies.works.slice(-36);p.editions++;p.stage=0;p.paid=false;p.completedAt=at;p.steps=[];p.draft=null;p.sourceIds=[];if(a.kind==='jam')s.home.pantry.snacks=Math.min(24,s.home.pantry.snacks+2);return{done:true,work:w,text:'她完成了「'+w.name+'」，把过程和来历收进兴趣手册。'+(a.kind==='jam'?'还留下两份可以带去野餐的茶点。':''),sources:[...w.sourceIds,...w.steps,w.id]};
 }
 return{PROJECTS,ids,fresh,clean,available,rows,spec,begin,finish};
});
