(function(root){'use strict';let registration=null,initializing=null,lastError='',reloadAfterUpdate=false;
 function init(){if(initializing)return initializing;if(!('serviceWorker'in navigator)||!root.isSecureContext){lastError='此入口无法安装离线版，请使用 HTTPS 游戏网址。';return Promise.resolve(null);}initializing=navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'}).then(r=>{registration=r;return r;}).catch(()=>{lastError='下载没有完成，请联网后重试。';initializing=null;return null;});return initializing;}
 navigator.serviceWorker?.addEventListener('controllerchange',()=>{if(reloadAfterUpdate)location.reload();});
 async function status(){await init();if(registration?.waiting)return{complete:false,message:'新版已下载。点“检查游戏更新”，保存进度后切换。'};const worker=registration?.active;if(!worker)return{complete:false,message:lastError||'正在下载游戏素材，首次打开请保持联网。'};return new Promise(resolve=>{const channel=new MessageChannel(),timer=setTimeout(()=>{channel.port1.close();resolve({complete:false,message:'缓存检查尚未完成，请稍后再试。'});},4000);channel.port1.onmessage=e=>{clearTimeout(timer);channel.port1.close();resolve(e.data);};worker.postMessage({type:'STATUS'},[channel.port2]);});}
 function panel(host,{save,exportSave}){host.className='offline-panel';const heading=document.createElement('h3');heading.textContent='iPhone 主屏幕离线版';const state=document.createElement('p');state.className='offline-state';state.setAttribute('role','status');const intro=document.createElement('p');intro.textContent='联网打开游戏 → Safari 分享 → 添加到主屏幕（打开为网页 App）→ 从新图标进入。等这里显示“离线已就绪”，就可以开飞行模式试玩。';const note=document.createElement('p');note.textContent='生活和棋局存在本机。关闭后，下次打开会结算经过的时间。Safari 与主屏幕入口可能使用不同存储，已有进度请先导出，再到新入口导入。';host.append(heading,state,intro,note);let busy=false;
 const button=(name,fn)=>{const e=document.createElement('button');e.textContent=name;e.onclick=fn;host.append(e);return e;};
 async function refresh(){const s=await status();if(!host.isConnected)return;state.textContent=s.complete?'离线已就绪 · v'+s.version+' · '+s.count+' 项素材':s.message||'下载中 · '+s.count+' / '+s.total;}
 button('检查离线下载',async()=>{await init();await refresh();});
 const update=button('检查游戏更新',async()=>{if(busy)return;busy=true;update.disabled=true;try{await init();if(!registration)throw Error(lastError);await registration.update();const installing=registration.installing;if(installing)await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('更新仍在下载，稍后再检查一次。')),60000);function done(){if(installing.state==='installed'||installing.state==='redundant'){clearTimeout(timer);installing.removeEventListener('statechange',done);installing.state==='installed'?resolve():reject(Error('更新下载失败，当前版本仍可继续玩。'));}}installing.addEventListener('statechange',done);done();});if(registration.waiting){if(await save()===false)throw Error('存档未保存成功，请先导出备份。');reloadAfterUpdate=true;registration.waiting.postMessage({type:'ACTIVATE'});}else{await refresh();state.textContent+=' · 当前已是最新版';}}catch(e){state.textContent=e.message;}finally{busy=false;update.disabled=false;}});
 button('保护本机存储',async()=>{try{const ok=await navigator.storage?.persist?.();state.textContent=ok?'已获得持久存储。清理网站数据前仍请导出备份。':'浏览器暂未授予持久存储。请保留一份导出存档。';}catch{state.textContent='暂不支持持久存储，请用导出备份保存进度。';}});
 button('导出存档备份',exportSave);refresh();let checks=0;function poll(){if(!host.isConnected||checks++>30||busy)return;refresh();setTimeout(poll,2000);}setTimeout(poll,2000);
 }
 root.WitchOffline={init,status,panel};
})(globalThis);
