(function(root){'use strict';
 const P=root.WitchPocket,el=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
 function mount(host,options){let b=options.saved.kind==='nonogram'?P.cleanNonogram(options.saved):P.cleanMerge(options.saved),tool=1,finished=false,start=null;const nono=b.kind==='nonogram',wrap=el('div',undefined,'mini-game pocket-game'),board=el('div',undefined,'pocket-board '+(nono?'nonogram-board':'merge-board')),toolbar=el('div',undefined,'mini-toolbar'),status=el('p','','pocket-status'),help=el('p',nono?'每行、每列的数字表示连续涂色的格数。两组之间至少空一格。先看最大的数字，确定空格后标 ×。':'向一个方向滑动，相同数字碰面就会合并。每次有效移动添一颗星砂，试着合出 2048。也可以用方向键。','hint');board.tabIndex=0;board.setAttribute('aria-label',nono?'数织棋盘':'星砂合成棋盘');board.style.setProperty('--n',nono?b.size+1:4);
 const button=(text,fn)=>{const e=el('button',text);e.onclick=fn;toolbar.append(e);return e;};
 function changed(){options.onChange(b);const done=nono?P.nonogramDone(b):b.won;if(done&&!finished){finished=true;options.onFinish(b.kind,b);}render();}
 let fill,cross,erase;if(nono){fill=button('涂色',()=>{tool=1;render();});cross=button('标 ×',()=>{tool=-1;render();});erase=button('擦除',()=>{tool=0;render();});button('提示一格',()=>{P.hint(b);changed();});}else{for(const[d,text]of [['U','↑'],['L','←'],['D','↓'],['R','→']]){const e=button(text,()=>{P.move(b,d);changed();});e.setAttribute('aria-label','向'+({U:'上',L:'左',D:'下',R:'右'})[d]+'合成');}}
 button('撤销一步',()=>{(nono?P.undoNonogram:P.undoMerge)(b);changed();});button('换一局',options.onNew);button('收起，稍后继续',options.onExit);
 function render(){board.replaceChildren();if(nono){[fill,cross,erase].forEach((e,i)=>e.setAttribute('aria-pressed',tool===[1,-1,0][i]?'true':'false'));const clues=P.lines(b.solution,b.size);board.append(el('span','','nono-corner'));for(let c=0;c<b.size;c++){const e=el('span',clues.cols[c].join('\n'),'nono-clue vertical');e.setAttribute('aria-label','第 '+(c+1)+' 列：'+clues.cols[c].join('，'));board.append(e);}for(let r=0;r<b.size;r++){const e=el('span',clues.rows[r].join(' '),'nono-clue');board.append(e);for(let c=0;c<b.size;c++){const i=r*b.size+c,v=b.cells[i],fixed=b.givens.includes(i),cell=el('button',v===-1?'×':fixed?'·':'','nono-cell'+(v===1?' ink':'')+(fixed?' fixed':''));cell.setAttribute('aria-label',`${r+1} 行 ${c+1} 列，${v===1?'已涂色':v===-1?'空格':'未填'}${fixed?'，已知格':''}`);cell.disabled=fixed;cell.onclick=()=>{P.mark(b,i,v===tool?0:tool);changed();};board.append(cell);}}status.textContent=P.nonogramDone(b)?'图案出现了！这张小图收进了共同经历。':`${b.size} × ${b.size} · 已用 ${b.hints} 次提示`;}
 else{b.cells.forEach(v=>{const e=el('div',v?String(v):'','merge-cell');e.dataset.power=v?Math.min(11,Math.log2(v)):0;board.append(e);});status.textContent=`${b.score} 分 · ${b.moves.length} 步`+(b.won?' · 合出 2048 了！可以继续。':b.over?' · 棋盘满了，可以撤销或换一局。':'');}}
 function key(e){if(nono)return;const d={ArrowUp:'U',ArrowDown:'D',ArrowLeft:'L',ArrowRight:'R',w:'U',s:'D',a:'L',d:'R'}[e.key];if(d){e.preventDefault();e.stopPropagation();P.move(b,d);changed();}}
 function down(e){start={x:e.clientX,y:e.clientY};board.setPointerCapture?.(e.pointerId);}
 function up(e){if(!start)return;const dx=e.clientX-start.x,dy=e.clientY-start.y;start=null;if(Math.max(Math.abs(dx),Math.abs(dy))<20)return;P.move(b,Math.abs(dx)>Math.abs(dy)?dx>0?'R':'L':dy>0?'D':'U');changed();}
 if(!nono){board.addEventListener('pointerdown',down);board.addEventListener('pointerup',up);board.addEventListener('pointercancel',()=>start=null);wrap.addEventListener('keydown',key);}wrap.append(help,status,board,toolbar);host.append(wrap);render();root.WitchPlayLayout?.schedule();return{getState:()=>b,destroy(){wrap.removeEventListener('keydown',key);board.removeEventListener('pointerdown',down);board.removeEventListener('pointerup',up);}};
 }
 root.WitchPocketUI={mount};
})(globalThis);
