/* Small offline games. Their RNG and undo history never consume world time or rewards. */
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.WitchPocket=api;})(globalThis,function(){
 'use strict';
 const copy=x=>JSON.parse(JSON.stringify(x));
 function seed(v){if(!Number.isSafeInteger(v)||v<0)throw Error('小游戏种子无效');return v;}
 function random(s){s.rng=(Math.imul(s.rng,1664525)+1013904223)>>>0;return s.rng/4294967296;}
 const pictures=[['01110','11011','11111','01110','00100'],['00100','01110','11111','00100','00100'],['00100','01110','11111','11011','11011'],['11110','10011','10011','11110','01100'],['00110','01111','11110','11100','01000'],['10101','11111','01110','01110','00100']];
 const large=[['00011000','00111100','01111110','11111111','00111100','00111100','01111110','00011000'],['00111100','01111110','11100111','11000011','11000011','11100111','01111110','00111100'],['00011000','00111100','01111110','11111111','01111110','01100110','01100110','01111110'],['01111110','11111111','11111111','00111100','00111100','00111100','00111100','01111110']];
 function clues(line){const out=[];let n=0;for(const a of [...line,0]){if(a)n++;else if(n){out.push(n);n=0;}}return out.length?out:[0];}
 function lines(solution,n){return{rows:Array.from({length:n},(_,r)=>clues(solution.slice(r*n,r*n+n))),cols:Array.from({length:n},(_,c)=>clues(Array.from({length:n},(_,r)=>solution[r*n+c])))};}
 function patterns(n,clue){const out=[];for(let bits=0;bits<2**n;bits++){const row=Array.from({length:n},(_,i)=>(bits>>i)&1);if(clues(row).join()==clue.join())out.push(row);}return out;}
 // Count up to two solutions, so a generated puzzle can add a fixed clue when needed.
 function solutions(solution,n,givens){const c=lines(solution,n),rs=c.rows.map((v,r)=>patterns(n,v).filter(p=>p.every((v,col)=>!givens.includes(r*n+col)||v===solution[r*n+col]))),cs=c.cols.map(v=>patterns(n,v));let total=0;const grid=[];function visit(r,cols){if(total>1)return;if(r===n){total++;return;}for(const row of rs[r]){const next=cols.map((col,j)=>col.filter(p=>p[r]===row[j]));if(next.some(x=>!x.length))continue;grid.push(row);visit(r+1,next);grid.pop();}}visit(0,cs);return total;}
 function nonogram(s=Date.now(),size=5){seed(s);if(![5,8].includes(size))throw Error('数织尺寸无效');const bank=size===5?pictures:large,which=s%bank.length;let solution=bank[which].join('').split('').map(Number);if(Math.floor(s/bank.length)%2)solution=Array.from({length:size*size},(_,i)=>solution[Math.floor(i/size)*size+size-1-i%size]);if(Math.floor(s/(bank.length*2))%2)solution=Array.from({length:size*size},(_,i)=>solution[(i%size)*size+Math.floor(i/size)]);const givens=[];for(let i=0;solutions(solution,size,givens)>1&&i<solution.length;i++)givens.push(i);const b={id:'nonogram-'+s,kind:'nonogram',seed:s,size,solution,givens,cells:Array(size*size).fill(0),undo:[],hints:0};for(const i of givens)b.cells[i]=solution[i]?1:-1;return b;}
 function nonogramDone(b){return b.cells.every((v,i)=>(v===1)===(b.solution[i]===1));}
 function mark(b,i,value){if(!Number.isInteger(i)||i<0||i>=b.cells.length||b.givens.includes(i)||![-1,0,1].includes(value)||b.cells[i]===value)return false;b.undo.push([i,b.cells[i]]);b.undo=b.undo.slice(-300);b.cells[i]=value;return true;}
 function hint(b){const i=b.cells.findIndex((v,i)=>(v===1)!==(b.solution[i]===1));if(i<0)return false;mark(b,i,b.solution[i]?1:-1);b.hints++;return true;}
 function undoNonogram(b){const item=b.undo.pop();if(item)b.cells[item[0]]=item[1];return !!item;}
 function cleanNonogram(v){if(!v)return null;const b=nonogram(seed(v.seed),v.size);if(v.id!==b.id||!Array.isArray(v.cells)||v.cells.length!==b.cells.length||v.cells.some(x=>![-1,0,1].includes(x)))throw Error('数织存档无效');b.cells=[...v.cells];if(b.givens.some(i=>b.cells[i]!== (b.solution[i]?1:-1)))throw Error('数织固定格被改动');if(!Number.isInteger(v.hints)||v.hints<0||v.hints>100000)throw Error('数织提示次数无效');b.hints=v.hints;if(!Array.isArray(v.undo)||v.undo.length>300||v.undo.some(x=>!Array.isArray(x)||x.length!==2||!Number.isInteger(x[0])||x[0]<0||x[0]>=b.cells.length||b.givens.includes(x[0])||![-1,0,1].includes(x[1])))throw Error('数织撤销记录无效');b.undo=copy(v.undo);return b;}
 function spawn(b){const empty=b.cells.map((v,i)=>v?null:i).filter(i=>i!==null);if(!empty.length)return;const i=empty[Math.floor(random(b)*empty.length)];b.cells[i]=random(b)<.9?2:4;}
 function merge(s=Date.now()){seed(s);const b={id:'merge-'+s,kind:'merge',seed:s,rng:s>>>0,cells:Array(16).fill(0),score:0,moves:'',won:false,over:false};spawn(b);spawn(b);return b;}
 function slide(cells,direction){if(!'LRUD'.includes(direction)||direction.length!==1)throw Error('合成方向无效');const out=[...cells];let score=0;for(let row=0;row<4;row++){const ids=Array.from({length:4},(_,j)=>direction==='L'?row*4+j:direction==='R'?row*4+3-j:direction==='U'?j*4+row:(3-j)*4+row);const nums=ids.map(i=>cells[i]).filter(Boolean),values=[];for(let j=0;j<nums.length;j++){if(nums[j]===nums[j+1]){values.push(nums[j]*2);score+=nums[j]*2;j++;}else values.push(nums[j]);}ids.forEach((i,j)=>out[i]=values[j]||0);}return{cells:out,score,changed:out.some((v,i)=>v!==cells[i])};}
 function move(b,direction){if(b.moves.length>=12000)return false;const r=slide(b.cells,direction);if(!r.changed)return false;b.cells=r.cells;b.score+=r.score;b.moves+=direction;spawn(b);b.won=b.cells.some(v=>v>=2048);b.over=!'LRUD'.split('').some(d=>slide(b.cells,d).changed);return true;}
 function replay(s,moves){const b=merge(s);for(const d of moves)if(!move(b,d))throw Error('合成记录不连续');return b;}
 function cleanMerge(v){if(!v)return null;if(typeof v.moves!=='string'||v.moves.length>12000||/[^LRUD]/.test(v.moves))throw Error('合成记录无效');const b=replay(seed(v.seed),v.moves);if(v.id!==b.id||!Array.isArray(v.cells)||v.cells.join()!==b.cells.join()||v.score!==b.score)throw Error('合成棋盘与记录不符');return b;}
 function undoMerge(b){if(!b.moves.length)return false;Object.assign(b,replay(b.seed,b.moves.slice(0,-1)));return true;}
 return{nonogram,nonogramDone,clues,lines,solutions,mark,hint,undoNonogram,cleanNonogram,merge,move,slide,cleanMerge,undoMerge};
});
