(function(root){'use strict';const el=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
 function mount(host,{state,save,onWrite,onExit,selected}){const cards=state.hobbies.works.filter(w=>w.project==='postcard').reverse();let index=Math.max(0,cards.findIndex(w=>w.id===selected)),back=false;const view=el('div'),list=el('div',undefined,'mail-list');host.append(view,list);
 function button(text,fn){const b=el('button',text);b.onclick=fn;return b;}
 function render(){view.replaceChildren();list.replaceChildren();if(!cards.length){view.append(el('p','信匣还空着。陪她画插画、写信、贴邮票，三步完成后，第一张明信片就会送到这里。'),button('一起写一张',onWrite),button('先收好信匣',onExit));return;}const w=cards[index],letter=w.letter||{from:'你的伙伴',heading:'留在这一天',body:w.text,theme:'day'},date=new Date(w.at).toLocaleDateString('zh-CN');view.append(el('p',`${index+1} / ${cards.length} · ${date}`,'eyebrow'));if(back){const paper=el('article',undefined,'postcard-paper');paper.append(el('span','☾ ✦','stamp'),el('h3','给你：'),el('p',letter.body),el('p',letter.from+'\n'+date));view.append(paper);if(letter.sourceQuote){const quote=el('details',undefined,'mail-source');quote.append(el('summary','这张信里的梦种'),el('p',letter.sourceQuote));view.append(quote);}if(!w.read){w.read=true;save();}}else{const canvas=el('canvas',undefined,'postcard-art');canvas.width=720;canvas.height=432;canvas.setAttribute('aria-label',letter.heading+'，明信片插画');draw(canvas,letter,w.edition);view.append(canvas,el('h3',letter.heading));}
 const controls=el('div',undefined,'postcard-controls');controls.append(button(back?'看看插画':'翻到背面',()=>{back=!back;render();}),button('保存明信片图片',()=>download(w,letter)));view.append(controls,button('一起写下一张',onWrite));cards.forEach((card,i)=>{const b=button((card.read?'':'● ')+new Date(card.at).toLocaleDateString('zh-CN')+'\n'+(card.letter?.heading||'留给你的明信片'),()=>{index=i;back=false;render();});b.setAttribute('aria-pressed',String(i===index));list.append(b);});host.dataset.cards=cards.length;}
 render();}
 function draw(canvas,letter,edition){const c=canvas.getContext('2d'),w=canvas.width,h=canvas.height,night=letter.theme==='night',rain=letter.theme==='rain';c.fillStyle=night?'#263d4d':'#b8c8a0';c.fillRect(0,0,w,h);c.fillStyle=night?'#d8c27a':'#f7e4a5';c.beginPath();c.arc(w*.76,h*.2,32,0,Math.PI*2);c.fill();if(night){c.fillStyle='#263d4d';c.beginPath();c.arc(w*.78,h*.18,28,0,Math.PI*2);c.fill();}c.fillStyle=night?'#344b48':'#809d72';for(let i=0;i<7;i++){c.beginPath();c.arc(i*140-40,h,140+((i+edition)%3)*20,Math.PI,0);c.fill();}c.fillStyle='#a98a60';c.fillRect(w*.29,h*.43,w*.38,h*.39);c.fillStyle='#5a6b58';c.beginPath();c.moveTo(w*.23,h*.46);c.lineTo(w*.47,h*.18);c.lineTo(w*.72,h*.46);c.fill();c.fillStyle='#5b493b';c.fillRect(w*.43,h*.59,w*.1,h*.23);c.fillStyle='#f6d489';c.fillRect(w*.34,h*.54,40,40);c.fillRect(w*.57,h*.54,40,40);c.strokeStyle='#c9aa72';c.lineWidth=3;c.strokeRect(15,15,w-30,h-30);c.fillStyle='#f3dea1';for(let i=0;i<14;i++){const x=(i*113+edition*47)%(w-40)+20,y=(i*71+edition*17)%(h-50)+20;if(rain){c.fillStyle='#d8e5d8';c.fillRect(x,y,2,13);}else if(night){c.fillRect(x,y,3,3);}}c.fillStyle='#edf0c3';for(let i=0;i<18;i++){const x=30+(i*73+edition*19)%(w-60),y=h-24-(i%3)*9;c.fillRect(x,y,4,4);}c.fillStyle='#f8e8bd';c.font='20px serif';c.fillText('梦乡 · '+(night?'夜里的灯':rain?'窗边听雨':'风从小院来'),30,h-30);}
 function download(w,letter){const canvas=document.createElement('canvas');canvas.width=900;canvas.height=1100;const c=canvas.getContext('2d');c.fillStyle='#f7ecd1';c.fillRect(0,0,900,1100);const art=document.createElement('canvas');art.width=720;art.height=432;draw(art,letter,w.edition);c.drawImage(art,40,40,820,492);c.fillStyle='#354635';c.font='28px serif';c.fillText(letter.heading,45,585);c.font='23px sans-serif';let y=635,line='';for(const ch of letter.body){if(ch==='\n'||c.measureText(line+ch).width>800){c.fillText(line,45,y);y+=34;line=ch==='\n'?'':ch;}else line+=ch;}if(line)c.fillText(line,45,y);c.font='21px serif';c.fillText(letter.from+' · '+new Date(w.at).toLocaleDateString('zh-CN'),45,1060);canvas.toBlob(blob=>{if(!blob)return;const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download='梦乡-明信片-'+w.id+'.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);},'image/png');}
 root.WitchPostcards={mount,draw};
})(globalThis);
