/* Phaser owns world pixels and input; WitchLife owns every lasting fact. */
(function(root){'use strict';const V=root.WitchVillage;
 function mount(host,api){
  let scene=null,area=null,overview=false,focused=true,ready=false,pending=null,lastArea=null,lastPose='down',lastKey=0,lastStep=0,audio=null,gain=null;
  const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,actorHeight=82;
  let residentFrame=0,residentCache=[];function residents(){const at=Date.now();if(at-residentFrame>300){residentFrame=at;residentCache=api.residents();}return residentCache;}const state=()=>api.getState(),modal=()=>!document.getElementById('sheet').hidden;
  function sound(type){if(!state().village.sound)return;try{if(!audio){audio=new(window.AudioContext||window.webkitAudioContext)();gain=audio.createGain();gain.gain.value=.15;gain.connect(audio.destination);}if(audio.state==='suspended')audio.resume();const o=audio.createOscillator(),g=audio.createGain(),t=audio.currentTime;o.type=type==='step'?'triangle':'sine';o.frequency.setValueAtTime(type==='step'?130:610,t);o.frequency.exponentialRampToValueAtTime(type==='step'?65:390,t+.065);g.gain.setValueAtTime(type==='step'?.035:.12,t);g.gain.exponentialRampToValueAtTime(.0001,t+.1);o.connect(g);g.connect(gain);o.start(t);o.stop(t+.11);}catch{}}
  function walk(p,action){try{api.onWalk(p);pending=action||null;focused=true;sound('tap');}catch(e){api.onError(e.message);}}
  function cutAtlas(sc,key,columns,rows){
   const image=sc.textures.get(key).getSourceImage(),c=document.createElement('canvas');c.width=image.width;c.height=image.height;const cx=c.getContext('2d',{willReadFrequently:true});cx.drawImage(image,0,0);const data=cx.getImageData(0,0,c.width,c.height).data,frames=[];
   for(let row=0;row<rows;row++)for(let col=0;col<columns;col++){
    const propRects=[[0,0,382,550],[387,0,774,550],[776,0,1162,550],[1163,0,1536,550],[0,552,406,1024],[411,626,793,970],[799,612,1235,979],[1240,557,1536,1024]],rect=propRects[row*columns+col];const x0=key==='props'?rect[0]:(key==='witch'?[110,455,840][col]:Math.floor(col*c.width/columns))+(key==='actions'&&row===0&&col===3?44:0),x1=key==='props'?rect[2]:(key==='witch'?[450,835,c.width][col]:Math.floor((col+1)*c.width/columns))-(key==='actions'&&row===0&&col===2?36:0),y0=key==='witch'?[0,313,627,932][row]:key==='props'?rect[1]:Math.floor(row*c.height/rows),y1=key==='witch'?[311,625,930,c.height][row]:key==='props'?rect[3]:Math.floor((row+1)*c.height/rows);let left=x1,right=x0,top=y1,bottom=y0;
    for(let y=y0;y<y1;y++)for(let x=x0;x<x1;x++)if(data[(y*c.width+x)*4+3]>95){left=Math.min(left,x);right=Math.max(right,x);top=Math.min(top,y);bottom=Math.max(bottom,y);}
    const name=String(row*columns+col);sc.textures.get(key).add(name,0,left,top,Math.max(1,right-left+1),Math.max(1,bottom-top+1));frames.push({name,w:right-left+1,h:bottom-top+1});
   }return frames;
  }
  function makeRig(sc){
   const source=sc.textures.get('witch').getSourceImage(),out=[];
   function bounds(c,y){const w=c.canvas.width,h=c.canvas.height,pixels=c.getImageData(0,y,w,h-y).data;let left=w,right=0;for(let row=0;row<h-y;row++)for(let x=0;x<w;x++)if(pixels[(row*w+x)*4+3]>130){left=Math.min(left,x);right=Math.max(right,x);}return{left,right};}
   for(let row=0;row<4;row++){
    const f=sc.textures.getFrame('witch',String(row*3)),w=f.cutWidth,h=f.cutHeight,hem=Math.floor(h*.845),crop=document.createElement('canvas');crop.width=w;crop.height=h;const c=crop.getContext('2d',{willReadFrequently:true});c.drawImage(source,f.cutX,f.cutY,w,h,0,0,w,h);
    const neutral=bounds(c,hem+12),anchor=(neutral.left+neutral.right)/2,parts=[];
    const body=sc.textures.createCanvas('rig-'+row+'-0',w,hem+12);body.context.drawImage(crop,0,0,w,hem+12,0,0,w,hem+12);body.refresh();parts.push({key:'rig-'+row+'-0',x:0,y:0,w,h:hem+12});
    // Side-on idle art has overlapping boots. Take the two complete boots from
    // the open-stride frame, then animate them around the same standing hips.
    let legs=crop,context=c;if(row===1||row===2){const sf=sc.textures.getFrame('witch',String(row*3+1));legs=document.createElement('canvas');legs.width=Math.round(sf.cutWidth*h/sf.cutHeight);legs.height=h;context=legs.getContext('2d',{willReadFrequently:true});context.imageSmoothingEnabled=false;context.drawImage(source,sf.cutX,sf.cutY,sf.cutWidth,sf.cutHeight,0,0,legs.width,h);}
    const bb=bounds(context,hem+12),split=Math.round((bb.left+bb.right)/2);
    [[bb.left,split],[split,bb.right+1]].forEach(([x,end],i)=>{const width=end-x,key='rig-'+row+'-'+(i+1),tex=sc.textures.createCanvas(key,width,h-hem);tex.context.drawImage(legs,x,hem,width,h-hem,0,0,width,h-hem);tex.refresh();const side=row===1||row===2,center=side?anchor+(i?1:-1)*(neutral.right-neutral.left)*.18:x+width/2;parts.push({key,x:center-width/2,y:hem,w:width,h:h-hem});});out.push({w,h,hem,anchor,parts});
   }return out;
  }
  class World extends Phaser.Scene{
   preload(){this.load.image('terrain','assets/terrain-v2.png');this.load.image('props','assets/village-props-v1.png');this.load.image('witch','assets/witch-directions-v1.png');this.load.image('actions','assets/village-actions-v1.png');this.load.image('room','assets/cottage-map-v1.png');this.load.on('loaderror',file=>api.onError('地图素材暂时没载入：'+file.key+'。请联网刷新重试。'));}
   create(){scene=this;this.propFrames=cutAtlas(this,'props',4,2);this.witchFrames=cutAtlas(this,'witch',3,4);this.actionFrames=cutAtlas(this,'actions',4,2);root.WitchTerrain.paint(this,V);root.WitchTerrain.paintForest(this,V);this.rigFrames=makeRig(this);this.ground=this.add.image(0,0,'ground').setOrigin(0).setDepth(-2000);this.room=this.add.image(0,0,'room').setOrigin(0).setDisplaySize(1024,768).setDepth(-2000);this.outside=[];this.hotspots=[];this.inside=[];this.forestGround=this.add.image(0,0,'forest-ground').setOrigin(0).setDepth(-2000);this.forestProps=[];for(const p of V.FOREST_PROPS)this.forestProps.push(this.add.image(p.x,p.y,'props',String(p.frame)).setOrigin(.5,1).setDisplaySize(p.w,p.h).setDepth(p.y));for(let i=0;i<17;i++){const x=40+i*94,y=180+(i%4)*22,h=210+(i%3)*30;this.forestProps.push(this.add.image(x,y,'props',i%3?'3':'4').setOrigin(.5,1).setDisplaySize(h*.8,h).setDepth(y));}
    for(const p of V.PROPS){const img=this.add.image(p.x,p.y,'props',String(p.frame)).setOrigin(.5,1).setDisplaySize(p.w,p.h).setDepth(p.y);this.outside.push(img);const spot=({cottage:'home',shop:'shop',neighbor:'neighbor',bench:'bench',bush1:'berries',bush2:'herbs'})[p.id];if(spot){img.setInteractive({pixelPerfect:true,alphaTolerance:100,useHandCursor:true});img.on('pointerup',()=>{if(!modal())select(spot);});}}
    for(let i=0;i<16;i++){const x=25+i*138+(i%3)*13,y=210+(i%4)*9,h=240+(i%5)*17;this.outside.push(this.add.image(x,y,'props',i%5===0?'4':'3').setOrigin(.5,1).setDisplaySize(h*.83,h).setDepth(y));}
    this.shadow=this.add.ellipse(0,0,38,12,0x22382a,.23);this.actor=this.add.image(0,0,'witch','0').setOrigin(.5,1);this.actor.setInteractive({useHandCursor:true});this.actor.on('pointerup',()=>{if(!modal())api.onNow();});this.rigLegs=[this.add.image(0,0,'rig-0-1').setOrigin(.5,0),this.add.image(0,0,'rig-0-2').setOrigin(.5,0)];this.rigBody=this.add.image(0,0,'rig-0-0').setOrigin(.5,0).setInteractive({useHandCursor:true});this.rigBody.on('pointerup',()=>{if(!modal())api.onNow();});this.walkPhase=0;this.lastFoot=null;
    this.npcs={};for(const[id,n]of Object.entries(V.NPCS)){const index=id==='moss'?6:7,f=this.actionFrames[index],image=this.add.image(0,0,'actions',String(index)).setOrigin(.5,1).setDisplaySize(74*f.w/f.h,74),label=this.add.text(0,0,n.name,{fontFamily:'Microsoft YaHei, sans-serif',fontSize:'13px',color:'#fff3cf',stroke:'#344834',strokeThickness:4}).setOrigin(.5).setResolution(2);if(!['moss','chestnut'].includes(id)){const tex=this.textures.createCanvas('npc-'+id,140,160);root.WitchCompanions.draw(tex.context,{kind:'creature',form:n.form,body:n.body,accent:n.accent},70,152,136,0,false,false);tex.refresh();image.setTexture('npc-'+id).setDisplaySize(65,74);}image.setInteractive({useHandCursor:true});image.on('pointerup',()=>{if(modal())return;const n=api.residents().find(n=>n.id===id);walk(n,'npc:'+id);});this.npcs[id]={image,label};}
    for(const[id,p]of Object.entries(V.SPOTS)){const marker=this.add.text(p.x,p.y+5,'◇',{fontSize:'24px',color:'#fff1b8',stroke:'#4e6946',strokeThickness:2}).setOrigin(.5).setDepth(3000);const label=this.add.text(p.x,p.y+24,p.name,{fontFamily:'Microsoft YaHei, sans-serif',fontSize:'12px',color:'#fff4d3',backgroundColor:'#344c38bb',padding:{x:7,y:4}}).setOrigin(.5).setDepth(3000).setResolution(2);marker.setInteractive({useHandCursor:true});label.setInteractive({useHandCursor:true});const fn=()=>{if(!modal())select(id);};marker.on('pointerup',fn);label.on('pointerup',fn);this.hotspots.push({id,p,marker,label});}
    this.lifeDetails=this.add.graphics();this.effects=this.add.graphics().setDepth(2600);this.night=this.add.rectangle(0,0,V.WIDTH,V.HEIGHT,0x142b42,0).setOrigin(0).setDepth(2500);this.marker=this.add.ellipse(0,0,27,12,0xebd394,.1).setStrokeStyle(2,0xefdda0,.75).setDepth(2000).setVisible(false);
    this.speech=this.add.text(0,0,'',{fontFamily:'Microsoft YaHei, sans-serif',fontSize:'14px',color:'#354833',backgroundColor:'#fff2d8',padding:{x:12,y:9},wordWrap:{width:230}}).setOrigin(.5,1).setDepth(3100).setVisible(false);
    this.input.on('pointerup',(pointer,objects)=>{if(modal()||objects.length||!ready)return;const p=this.cameras.main.getWorldPoint(pointer.x,pointer.y);if(area==='village'){const plot=V.PLOTS.findIndex(t=>p.x>=t.x-5&&p.x<=t.x+t.w+5&&p.y>=t.y-5&&p.y<=t.y+t.h+5);if(plot>=0){const t=V.PLOTS[plot];walk(V.nearest({area,x:t.x+t.w/2,y:t.y+t.h+10}),'plot:'+plot);return;}}const q=V.nearest({area,x:p.x,y:p.y});if(Math.hypot(q.x-p.x,q.y-p.y)<120){walk(q);this.marker.setPosition(q.x,q.y).setVisible(true);this.markerUntil=performance.now()+700;}});
    this.input.keyboard?.on('keydown',e=>{if(!modal()&&['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','w','a','s','d','W','A','S','D'].includes(e.key))e.preventDefault();});this.keys=this.input.keyboard?.addKeys('W,A,S,D,UP,DOWN,LEFT,RIGHT',false);
    this.scale.on('resize',()=>this.resizeView(true));this.cameras.main.setBackgroundColor('#263d30');this.resizeView(true);ready=true;api.onReady?.();
   }
   resizeView(snap=false){if(!state())return;const p=V.position(state(),Date.now()),cam=this.cameras.main,changed=area!==p.area;area=p.area;host.dataset.area=area;const inside=area==='inside';this.ground.setVisible(area==='village');this.forestGround.setVisible(area==='forest');this.room.setVisible(inside);for(const o of this.outside)o.setVisible(area==='village');for(const o of this.forestProps)o.setVisible(area==='forest');for(const h of this.hotspots){h.marker.setVisible(h.p.area===area);h.label.setVisible(h.p.area===area);}for(const o of Object.values(this.npcs)){o.image.setVisible(!inside);o.label.setVisible(!inside);}const w=inside?1024:area==='forest'?1536:V.WIDTH,h=inside?768:area==='forest'?1152:V.HEIGHT;cam.useBounds=false;
    const fit=Math.min(this.scale.width/w,(this.scale.height-70)/h),normal=inside?(this.scale.width<600?.85:Math.max(fit,Math.min(this.scale.width/w,this.scale.height/600))):(this.scale.width<600?.85:1);const z=overview?fit*.96:normal*state().village.zoom;cam.setZoom(z);
    const focus=this.cameraPoint(p);if(snap||changed){cam.centerOn(focus.x,focus.y);this.effects.clear();if(changed&&!reduced)cam.fadeIn(150,24,41,30);}this.actor.setVisible(true);this.shadow.setVisible(true);
   }
   cameraPoint(p){const cam=this.cameras.main,w=area==='inside'?1024:area==='forest'?1536:V.WIDTH,h=area==='inside'?768:area==='forest'?1152:V.HEIGHT,halfW=this.scale.width/(2*cam.zoom),halfH=this.scale.height/(2*cam.zoom);if(overview)return{x:w/2,y:h/2};return{x:halfW>=w/2?w/2:Phaser.Math.Clamp(p.x,halfW,w-halfW),y:halfH>=h/2?h/2:Phaser.Math.Clamp(p.y-20,halfH,h-halfH)};}
   setAvatar(s){const signature=s.avatar.kind+':'+s.avatar.form+':'+s.avatar.body+':'+s.avatar.accent+':'+(s.avatar.portrait||'');if(signature===this.signature)return;this.signature=signature;if(s.avatar.kind==='original'){this.actor.setTexture('witch','0');return;}const key='player-custom';const tex=this.textures.exists(key)?this.textures.get(key):this.textures.createCanvas(key,140,160);const paint=img=>{if(this.signature!==signature||!this.sys?.isActive())return;tex.context.clearRect(0,0,140,160);root.WitchCompanions.draw(tex.context,s.avatar,70,151,140,0,false,false,img);tex.refresh();this.actor.setTexture(key).setDisplaySize(74,84);};if(s.avatar.kind==='portrait'){const image=new Image();image.onload=()=>paint(image);image.src=s.avatar.portrait;}else paint();}
   update(time,dt){if(!ready||!state())return;const s=state(),at=Date.now(),p=V.position(s,at);if(area!==p.area)this.resizeView(true);this.setAvatar(s);host.dataset.x=p.x.toFixed(1);host.dataset.y=p.y.toFixed(1);host.dataset.moving=String(p.moving);host.dataset.ready='true';
    if(p.moving){if(Math.abs(p.dx)>Math.abs(p.dy)*1.2)lastPose=p.dx>0?'right':'left';else if(Math.abs(p.dy)>Math.abs(p.dx)*1.2)lastPose=p.dy>0?'down':'up';}
    const pose={down:0,right:1,left:2,up:3}[lastPose],col=p.moving&&!reduced?([1,0,2,0][Math.floor(time/140)%4]):0;
    if(s.avatar.kind==='original'){
     const kind=s.activity.kind,action=!p.moving&&({read:0,tea:1,picnic:1,fish:2,garden:3,research:4,craft:4,postcard:4,sachet:4,pressed:4,starlamp:4,birds:5,jam:1,rest:5,birdwatch:5,game:5,cook:1,tidy:4,forage:3,sketch:4,help:4,deliver:5,recipe:1})[kind];
     if(action!==undefined&&action!==false){const f=this.actionFrames[action],h=[0,1,2,5].includes(action)?74:82;this.actor.setTexture('actions',String(action)).setFlipX(false).setDisplaySize(h*f.w/f.h,h);}else{const index=pose*3+col,f=this.witchFrames[index];this.actor.setTexture('witch',String(index)).setFlipX(false).setDisplaySize(actorHeight*f.w/f.h,actorHeight);}
    }else this.actor.setFlipX(lastPose==='left');
    const travelled=this.lastFoot&&this.lastFoot.area===p.area?Math.hypot(p.x-this.lastFoot.x,p.y-this.lastFoot.y):0;this.lastFoot={...p};if(p.moving)this.walkPhase+=Math.min(travelled,15)/24;const gait=Math.sin(this.walkPhase),bob=p.moving&&!reduced?Math.abs(gait)*.6:0;const working=!p.moving&&!reduced&&!s.village.journey,breath=working?Math.sin(time/820)*.45:0;this.actor.setPosition(p.x,p.y+bob+breath).setAngle(working?Math.sin(time/1400)*.45:0).setDepth(p.y);this.shadow.setPosition(p.x,p.y-2).setDepth(p.y-.1);
    if(!p.moving&&['read','birdwatch','rest','game','fish'].includes(s.activity.kind)){this.actor.y+=2;}

    const rig=s.avatar.kind==='original'&&(p.moving||s.village.journey||s.activity.kind==='walk');this.rigBody.setVisible(rig);this.rigLegs.forEach(l=>l.setVisible(rig));if(rig){this.actor.setVisible(false);const frame=this.rigFrames[pose],scale=actorHeight/frame.h,top=p.y-actorHeight,phase=p.moving&&!reduced?gait:0;
     this.rigBody.setTexture(frame.parts[0].key).setScale(scale).setPosition(p.x+(frame.w/2-frame.anchor)*scale,top+bob).setDepth(p.y+.04);this.rigLegs.forEach((leg,i)=>{const part=frame.parts[i+1],v=i===0?phase:-phase,side=pose===1||pose===2;leg.setTexture(part.key).setScale(scale,scale*(side?1:1+v*.16)).setPosition(p.x+(part.x+part.w/2-frame.anchor)*scale+(side?v*4:0),top+part.y*scale+(side?Math.max(0,-v)*-2:v*2)).setRotation(side?v*.22:0).setDepth(p.y-.02+i*.005);});
    }else this.actor.setVisible(true);
    this.lifeDetails.clear().setDepth(p.y+1);if(!p.moving&&!s.village.journey&&!reduced){const g=this.lifeDetails,k=s.activity.kind,phase=(time%4800)/4800;if(['tea','picnic','cook','jam'].includes(k)){g.lineStyle(1,0xf8e7bd,.35);for(let i=0;i<2;i++){const y=p.y-35-((time/100+i*5)%13);g.beginPath();g.moveTo(p.x-4+i*6,y);g.lineTo(p.x-2+i*6+Math.sin(time/370),y-5);g.strokePath();}}if(['postcard','research','craft','sachet','pressed','starlamp','tidy'].includes(k)&&phase<.7){g.lineStyle(1.5,0xf0d5a2,.8);g.beginPath();g.moveTo(p.x+10,p.y-21);g.lineTo(p.x+14+Math.sin(time/100)*2,p.y-28);g.strokePath();}if(k==='read'&&phase>.87){g.fillStyle(0xf9eac7,.8);g.fillTriangle(p.x-8,p.y-21,p.x+1,p.y-29-(phase-.87)*20,p.x+7,p.y-20);}if(['rest','birdwatch'].includes(k)){g.fillStyle(0xe9deb5,.55);g.fillCircle(p.x+17,p.y-56-Math.sin(time/700)*2,1.5);}}
    if(p.moving&&time-lastStep>290&&!document.hidden){lastStep=time;sound('step');}
    const cam=this.cameras.main;if(focused){const desired=this.cameraPoint(p),desiredX=desired.x,desiredY=desired.y;cam.centerOn(cam.midPoint.x+(desiredX-cam.midPoint.x)*(reduced?1:Math.min(1,dt/160)),cam.midPoint.y+(desiredY-cam.midPoint.y)*(reduced?1:Math.min(1,dt/160)));}
    for(const n of residents()){const o=this.npcs[n.id];o.image.setPosition(n.x,n.y+(n.moving&&!reduced?Math.sin(time/100)*1.2:0)).setFlipX(n.dx<0).setDepth(n.y);o.label.setPosition(n.x,n.y-83).setDepth(n.y+1);o.image.setVisible(area===n.area);o.label.setVisible(area===n.area&&!overview);o.label.setScale(1/cam.zoom);}
    for(const h of this.hotspots){const distance=V.dist(p,h.p),near=h.p.area===p.area&&distance<145;h.label.setVisible(h.p.area===area&&(near||overview)&&distance>45);h.label.setScale(1/cam.zoom);h.marker.setVisible(h.p.area===area&&!overview&&near&&distance>30);h.marker.setScale(.7/cam.zoom);h.marker.setAlpha(.7);}
    this.night.setSize(area==='inside'?1024:V.WIDTH,area==='inside'?768:V.HEIGHT).setAlpha(s.world.hour>=19||s.world.hour<6?(area==='inside'?.06:.25):0);
    this.effects.clear();const g=this.effects;

    if(area==='village'){
     if(s.world.weather==='小雨'&&!reduced){g.lineStyle(1,0xc9dfdb,.35);for(let i=0;i<110;i++){const x=(i*193+time*.02)%V.WIDTH,y=(i*271+time*.25)%V.HEIGHT;g.lineBetween(x,y,x-5,y+13);}}
     for(let i=0;i<12;i++){const plot=s.country.plots[i],spot=V.PLOTS[i];if(i>=s.country.unlocked){g.fillStyle(0x61744b,.8);g.fillRect(spot.x,spot.y,spot.w,spot.h);g.lineStyle(2,0xc4bd89,.7);g.strokeRect(spot.x+3,spot.y+3,spot.w-6,spot.h-6);continue;}if(plot.waterUntil>at){g.fillStyle(0x493c2c,.32);g.fillRect(spot.x,spot.y,spot.w,spot.h);}if(!plot.crop)continue;const progress=plot.workMs/(root.WitchCountry.CROPS[plot.crop].minutes*60000);for(let j=0;j<4;j++){const x=spot.x+17+(j%2)*30,y=spot.y+18+Math.floor(j/2)*26;g.fillStyle(0x43693c);g.fillRect(x-1,y-8-progress*9,3,13+progress*5);g.fillStyle(progress>=1?0xc5b573:0x779657);g.fillEllipse(x-4,y-7-progress*9,10+progress*4,6);g.fillEllipse(x+5,y-10-progress*8,11+progress*4,7);if(progress>=1){g.fillStyle(parseInt(root.WitchCountry.CROPS[plot.crop].color.slice(1),16));g.fillCircle(x,y-8,5);}}}
     s.plants.slice(-5).forEach((plant,i)=>{const creation=s.creations.find(c=>c.id===plant.creationId),x=1718+(i%3)*39,y=1051+Math.floor(i/3)*30;g.fillStyle(0x718a50);g.fillRect(x,y-12-plant.growth*17,4,30);g.fillEllipse(x-5,y-8-plant.growth*12,15,8);g.fillEllipse(x+7,y-16-plant.growth*12,16,8);g.fillStyle(parseInt((creation?.color||'#d4b177').slice(1),16));g.fillCircle(x+2,y-12-plant.growth*17,plant.bloomed?9:4);});
     if(s.world.hour>=19||s.world.hour<6)for(const lamp of V.PROPS.filter(p=>p.frame===7)){g.fillStyle(0xf6d285,.10);g.fillCircle(lamp.x+15,lamp.y-65,44);g.fillStyle(0xfbe7a3,.17);g.fillCircle(lamp.x+15,lamp.y-65,22);}
    }
    // Hands and a small object visibly connect the current action to the world.
    if(!p.moving&&s.avatar.kind!=='original'){const x=p.x,y=p.y-24;g.setDepth(p.y+1);if(s.activity.kind==='read'||s.activity.studyFragmentId){g.fillStyle(0xc5b07c);g.fillRect(x-12,y-8,24,14);g.lineStyle(1,0x66573b);g.lineBetween(x,y-8,x,y+6);}else if(s.activity.kind==='fish'||s.activity.title.includes('钓鱼')){g.lineStyle(2,0x785837);g.lineBetween(x+9,y,x+36,y-45);g.lineStyle(1,0xd8d6bb);g.lineBetween(x+36,y-45,x+66,y+22);}else if(['tea','cook','picnic'].includes(s.activity.kind)){g.fillStyle(0xddc796);g.fillRoundedRect(x-6,y-2,12,12,3);}}
    if(pending&&!s.village.journey){const action=pending;pending=null;this.marker.setVisible(false);api.onSpot(action);}
    if(this.markerUntil&&performance.now()>this.markerUntil)this.marker.setVisible(false);
    const speech=document.getElementById('speech');if(!speech.hidden&&speech.textContent){this.speech.setText(speech.textContent).setPosition(p.x,p.y-96).setVisible(true);}else this.speech.setVisible(false);
    if(!modal()&&this.keys&&time-lastKey>110){const k=this.keys,dx=Number(k.D.isDown||k.RIGHT.isDown)-Number(k.A.isDown||k.LEFT.isDown),dy=Number(k.S.isDown||k.DOWN.isDown)-Number(k.W.isDown||k.UP.isDown);if(dx||dy){lastKey=time;const target=V.steer(p,dx,dy);if(V.dist(p,target)>3)walk(target);}}
   }
  }
  function select(id){const p=V.SPOTS[id];if(!p)return;if(id==='exit')walk(V.HOME);else if(id==='home')walk(V.SPOTS.bed);else if(id==='forestGate')walk(V.FOREST_ENTRY);else if(id==='forestExit')walk(V.FOREST_GATE);else walk(p,p.action);}
  const game=new Phaser.Game({type:Phaser.AUTO,parent:host,backgroundColor:'#263d30',pixelArt:true,antialias:false,roundPixels:true,resolution:Math.min(2,window.devicePixelRatio||1),scale:{mode:Phaser.Scale.RESIZE,width:host.clientWidth,height:host.clientHeight},scene:World,render:{powerPreference:'low-power'},fps:{target:60,forceSetTimeOut:false},audio:{noAudio:true}});
  return{select,walk,follow(){focused=true;overview=false;scene?.resizeView(true);},overview(){overview=!overview;focused=true;scene?.resizeView(true);return overview;},zoom(){const s=state();s.village.zoom=s.village.zoom===1?1.3:s.village.zoom===1.3?.65:1;overview=false;scene?.resizeView();return s.village.zoom;},refresh(){scene?.resizeView(true);},toggleSound(){state().village.sound=!state().village.sound;sound('tap');return state().village.sound;},cancelPending(){pending=null;},destroy(){game.destroy(true);audio?.close();},get ready(){return ready;}};
 }
 root.WitchVillageView={mount};
})(globalThis);
