'use strict';
const assert=require('node:assert/strict'),A=require('../game/arcade.js'),L=require('../game/life.js'),H=require('../game/hobbies.js'),G=require('../game/games.js');
const clone=G.clone,at=Date.UTC(2026,8,29,3),results=[];
function test(name,fn){try{fn();results.push({name,pass:true});}catch(e){results.push({name,pass:false,error:e.stack});}}
test('连线遵守同图案、石头阻挡、两次转弯与棋盘外沿规则',()=>{
 const s={cols:4,rows:3,board:[1,2,2,1,2,2,2,2,2,2,2,2]};const p=A.linkPath(s,0,3);assert.ok(p&&p.some(p=>p.y===0));assert.equal(A.linkPath(s,0,1),null);assert.equal(A.linkPath(s,0,0),null);
 const trapped={cols:4,rows:4,board:[2,2,2,2,2,1,-1,2,2,-1,1,2,2,2,2,2]};assert.equal(A.linkPath(trapped,5,10),null);
 const corner={cols:3,rows:3,board:[1,0,0,2,2,0,2,2,1]};assert.ok(A.linkPath(corner,0,8));
});
test('36关各三个种子均可配对至完成，重排保留剩余图案和地形',()=>{
 for(let level=1;level<=36;level++)for(let seed=1;seed<=3;seed++){const s=A.link(1300+seed,level);assert.deepEqual(A.cleanLink(s).board,s.board);let n=0;while(!A.isLinkDone(s)){assert.ok(++n<100);let h=A.linkHint(s);if(!h){const before=s.board.filter(v=>v>0).sort();A.shuffleLink(s);assert.deepEqual(s.board.filter(v=>v>0).sort(),before);h=A.linkHint(s);}assert.ok(h);assert.ok(A.removeLink(s,h.a,h.b));A.cleanLink(s);}assert.ok(s.moves>=6);}
});
test('连连看拒绝奇数图案、篡改地形和伪造步数',()=>{const a=A.link(10,3);a.board[0]=0;assert.throws(()=>A.cleanLink(a));const b=A.link(7,3);b.board[b.board.indexOf(-1)]=1;assert.throws(()=>A.cleanLink(b));const c=A.link(3);c.moves++;assert.throws(()=>A.cleanLink(c));});
test('消消乐非法交换不扣步不消耗随机数；合法交换消除并结算落子',()=>{const s=A.match3(42);const old=clone(s);assert.equal(A.swapMatch(s,0,48).valid,false);assert.deepEqual(s,old);let invalid=false;for(let i=0;i<48&&!invalid;i++)if(i%7<6){const tmp=clone(s),r=A.swapMatch(tmp,i,i+1);if(!r.valid){assert.deepEqual(tmp,s);invalid=true;}}assert.ok(invalid);const h=A.matchHint(s),r=A.swapMatch(s,h.a,h.b);assert.ok(r.valid&&r.chain>=1);assert.ok(s.score>=30);assert.equal(A.matches(s.board).indices.length,0);assert.deepEqual(A.cleanMatch(s).board,s.board);});
test('20关各二十个种子都能形成合法局面，连消、加步、过关与步数耗尽都可发生',()=>{let cascades=0,bonuses=0,wins=0,losses=0;const won=new Set();for(let level=1;level<=20;level++)for(let seed=1;seed<=20;seed++){const s=A.match3(seed*333,level);for(let t=0;t<150&&s.movesLeft&&!A.isMatchDone(s);t++){assert.equal(A.matches(s.board).indices.length,0);const h=A.matchHint(s);assert.ok(h);const r=A.swapMatch(s,h.a,h.b);assert.ok(r.valid);if(r.chain>1)cascades++;if(r.bonus)bonuses++;A.cleanMatch(s);}if(A.isMatchDone(s)){wins++;won.add(level);}else{losses++;assert.equal(s.movesLeft,0);}}assert.ok(cascades>50&&bonuses>50&&wins>50&&losses>0);assert.equal(won.size,20,'每关在测试种子中都应可以过关');});
test('消消乐及关卡册拒绝坏盘、负数与未结算三连',()=>{const s=A.match3(90);s.board[0]=s.board[1]=s.board[2]=1;assert.throws(()=>A.cleanMatch(s));assert.throws(()=>A.cleanProgress({link:[1]}));const p=A.cleanProgress(null);p.match3[0]=-1;assert.throws(()=>A.cleanProgress(p));});
test('v3存档保留梦种、旧小游戏与性格，迁移添加手册和关卡册',()=>{const s=L.create(at);s.playbox.sudoku=G.sudoku(21);L.addFragment(s,'测试梦种：桂花茶',at);s.version=3;delete s.hobbies;delete s.arcadeProgress;delete s.playbox.link;delete s.playbox.match3;const r=L.validate(s,at);assert.equal(r.version,4);assert.equal(r.fragments[0].text,s.fragments[0].text);assert.deepEqual(r.preferences,s.preferences);assert.deepEqual(r.playbox.sudoku,s.playbox.sudoku);assert.equal(r.hobbies.works.length,0);assert.equal(r.arcadeProgress.link.length,36);});
test('六项兴趣分别走完三步留下有过程的收藏，消耗材料并产生果酱茶点',()=>{for(const k of H.ids){const s=L.create(at),d=H.PROJECTS[k],original=s.home.pantry[d.cost],snacks=s.home.pantry.snacks;for(let i=0;i<3;i++){L.invite(s,k,{},s.lastAdvancedAt);assert.equal(s.activity.projectStage,i);L.advance(s,s.activity.endsAt);assert.equal(s.hobbies.works.length,i===2?1:0);L.validate(s,s.lastAdvancedAt);}const w=s.hobbies.works[0];assert.equal(w.steps.length,3);assert.equal(w.project,k);assert.ok(w.text.includes(d.steps[0][0]));if(d.cost)assert.equal(s.home.pantry[d.cost],original-1);if(k==='jam')assert.equal(s.home.pantry.snacks,snacks+2);assert.equal(s.hobbies.projects[k].editions,1);const before=clone(s);L.advance(s,s.lastAdvancedAt);assert.deepEqual(s,before);}});
test('材料不足不会凭空开始；暂停、加入同一计划和重新载入不重复扣材料',()=>{const s=L.create(at);s.home.pantry.herbs=0;const id=s.activity.id;assert.throws(()=>L.invite(s,'sachet',{},at));assert.equal(s.activity.id,id);s.home.pantry.herbs=2;L.invite(s,'sachet',{},at);const aid=s.activity.id;L.invite(s,'sachet',{},at+1000);assert.equal(s.activity.id,aid);assert.equal(s.home.pantry.herbs,1);L.interrupt(s,'game',at+10000);L.holdGame(s,at+50000);const restored=L.validate(clone(s),at+50000);assert.equal(restored.activity.id,aid);assert.equal(restored.home.pantry.herbs,1);assert.ok(restored.activity.endsAt>at+90000);L.advance(restored,restored.activity.endsAt);assert.equal(restored.hobbies.projects.sachet.stage,1);assert.equal(restored.home.pantry.herbs,1);});
test('明信片记住开工时的梦种，而不是完成时重新抽素材',()=>{const s=L.create(at),f=L.addFragment(s,'测试梦境：天上的鲸鱼',at);L.invite(s,'postcard',{},at);L.addFragment(s,'测试梦境：后来的雨',at+1000);for(let i=0;i<3;i++){if(i)L.invite(s,'postcard',{},s.lastAdvancedAt);L.advance(s,s.activity.endsAt);}assert.deepEqual(s.hobbies.works[0].sourceIds,[f.id]);assert.ok(s.hobbies.works[0].text.includes('天上的鲸鱼'));});
test('在线与离线七天结算一致，兴趣有多样性、去重记忆和累计件数',()=>{const s=L.create(at),t=clone(s);L.advance(s,at+7*24*3600000);for(let i=1;i<=7*24;i++)L.advance(t,at+i*3600000);assert.deepEqual(s,t);assert.ok(Object.values(s.hobbies.projects).filter(p=>p.editions>0).length>=4);assert.ok(s.hobbies.works.length<=36);assert.ok(s.memories.length<=80);assert.equal(new Set(s.memories.map(m=>m.key)).size,s.memories.length);assert.deepEqual(L.validate(clone(s),s.lastAdvancedAt),s);});
test('关卡成绩与棋盘存档往返；过关记忆去重，未过关不得领奖',()=>{const s=L.create(at),b=A.link(571,5);assert.throws(()=>L.recordMiniGame(s,'link',b,at));while(!A.isLinkDone(b)){let h=A.linkHint(b);if(!h){A.shuffleLink(b);h=A.linkHint(b);}A.removeLink(b,h.a,h.b);}s.playbox.link=b;L.recordMiniGame(s,'link',b,at);L.recordMiniGame(s,'link',b,at);assert.ok(s.arcadeProgress.link[4]>0);assert.equal(s.memories.filter(m=>m.key===b.id).length,1);assert.deepEqual(L.validate(clone(s),at).arcadeProgress,s.arcadeProgress);});
for(const r of results)console.log((r.pass?'PASS ':'FAIL ')+r.name+(r.error?'\n'+r.error:''));console.log(results.filter(r=>r.pass).length+'/'+results.length+' arcade and hobby tests passed');process.exitCode=results.every(r=>r.pass)?0:1;
