'use strict';
const assert=require('node:assert/strict'),G=require('../game/games.js'),L=require('../game/life.js');
const at=Date.UTC(2026,8,21,3),M=60000,H=60*M,clone=G.clone,results=[];
function test(name,fn){try{fn();results.push({name,pass:true});}catch(e){results.push({name,pass:false,error:e.stack});}}
test('四十道不同数独都只有一个解，轻松与标准给定数不同',()=>{const fingerprints=new Set();for(let i=1;i<=20;i++)for(const level of ['easy','standard']){const s=G.sudoku(i,level);assert.equal(G.solve(s.givens).length,1);assert.ok(s.givens.filter(Boolean).length<=(level==='easy'?45:40));G.cleanSudoku(s);fingerprints.add(s.givens.join(''));}assert.equal(fingerprints.size,40);});
test('数独笔记、改错、提示、完成与只读题面',()=>{const s=G.sudoku(71);const fixed=s.givens.findIndex(Boolean),blank=s.givens.findIndex(v=>!v);assert.equal(G.enterSudoku(s,fixed,2),false);G.enterSudoku(s,blank,3,true);assert.equal(s.notes[blank],4);G.enterSudoku(s,blank,0);assert.equal(s.notes[blank],0);const solution=G.solve(s.givens,1)[0];G.enterSudoku(s,blank,solution[blank]%9+1);assert.ok(G.conflicts(s).length);const h=G.hintSudoku(s,blank);assert.equal(h.value,solution[blank]);s.values=solution;assert.equal(G.isSudokuDone(s),true);assert.equal(G.hintSudoku(s,blank),null);});
test('坏题、篡改给定、重复拼片、伪造配对均拒绝导入',()=>{const s=G.sudoku(8);s.givens.fill(0);assert.throws(()=>G.cleanSudoku(s));const fixed=G.sudoku(7);fixed.values[fixed.givens.findIndex(Boolean)]=0;assert.throws(()=>G.cleanSudoku(fixed));const p=G.puzzle(4);p.tiles[0]=p.tiles[1];assert.throws(()=>G.cleanPuzzle(p));const cards=G.pairs(7);cards.matched=[0];assert.throws(()=>G.cleanPairs(cards));});
test('两种照片两种块数都可通过交换复原，并保存步数',()=>{for(const image of ['cottage','courtyard'])for(const size of [3,4]){const s=G.puzzle(777,size,image);assert.equal(G.isPuzzleDone(s),false);for(let i=0;i<s.tiles.length;i++)if(s.tiles[i]!==i)G.swapPuzzle(s,i,s.tiles.indexOf(i));assert.equal(G.isPuzzleDone(s),true);assert.ok(s.moves>0);assert.deepEqual(G.cleanPuzzle(s),s);}});
test('翻牌限制两张、未配对收回、配对只计一次，存档能续翻',()=>{let s=G.pairs(89);const a=0,b=s.deck.findIndex(v=>v!==s.deck[a]);G.flipPair(s,a);G.flipPair(s,b);assert.equal(G.flipPair(s,11),false);s=G.cleanPairs(clone(s));assert.equal(G.resolvePair(s),false);for(let v=0;v<6;v++){const pos=s.deck.flatMap((n,i)=>n===v?[i]:[]);G.flipPair(s,pos[0]);G.flipPair(s,pos[1]);assert.equal(G.resolvePair(s),true);assert.equal(G.flipPair(s,pos[0]),false);}assert.equal(G.isPairsDone(s),true);});
test('v2存档迁移保留梦种与阅读，补充小院和题纸字段',()=>{const s=L.create(at);const f=L.addFragment(s,'迁移测试的花草',at);const old=clone(s);old.version=2;delete old.home;delete old.playbox;delete old.preferences.utcOffsetMinutes;const after=L.validate(old,at);assert.equal(after.version,3);assert.equal(after.fragments[0].id,f.id);assert.equal(after.activity.id,s.activity.id);assert.equal(after.home.pantry.herbs,2);assert.deepEqual(after.playbox,{sudoku:null,puzzle:null,pairs:null});});
test('小游戏随世界存档往返，未完成不能凭空记为胜利',()=>{const s=L.create(at);s.playbox.sudoku=G.sudoku(93);s.playbox.puzzle=G.puzzle(23,4,'courtyard');s.playbox.pairs=G.pairs(5);const loaded=L.validate(clone(s),at);assert.deepEqual(loaded.playbox,s.playbox);assert.throws(()=>L.recordMiniGame(s,'sudoku',s.playbox.sudoku,at));s.playbox.sudoku.values=G.solve(s.playbox.sudoku.givens,1)[0];L.recordMiniGame(s,'sudoku',s.playbox.sudoku,at);L.recordMiniGame(s,'sudoku',s.playbox.sudoku,at);assert.equal(s.memories.filter(m=>m.key===s.playbox.sudoku.id).length,1);});
test('采集到厨房形成资源因果，做完回到同一本书',()=>{const s=L.create(at),book=s.activity.id;L.invite(s,'gather',{material:'herbs'},at);assert.equal(L.currentView(s,at).scene,'courtyard');L.advance(s,at+90000);assert.equal(s.home.pantry.herbs,4);assert.equal(s.activity.id,book);L.invite(s,'cook',{material:'herbs'},at+90000);assert.equal(s.home.pantry.herbs,3);L.advance(s,at+180000);assert.equal(s.home.pantry.snacks,3);assert.equal(s.home.counts.cook,1);});
test('做饭中暂停玩游戏、存档恢复不重复扣材料',()=>{const s=L.create(at);L.invite(s,'cook',{material:'berries'},at);L.interrupt(s,'game',at+30000);L.holdGame(s,at+10*M);let r=L.validate(clone(s),at+10*M);assert.equal(r.home.pantry.berries,1);assert.equal(r.activity.kind,'cook');L.advance(r,r.activity.endsAt);assert.equal(r.home.pantry.berries,1);assert.equal(r.home.pantry.snacks,3);});
test('缺材料不能做饭，白天不能观星，没茶点不能野餐',()=>{const s=L.create(at);s.home.pantry.herbs=0;s.home.pantry.berries=0;const active=s.activity.id;assert.throws(()=>L.invite(s,'cook',{},at));assert.equal(s.activity.id,active);assert.throws(()=>L.invite(s,'stargaze',{},at));s.home.pantry.snacks=0;assert.throws(()=>L.invite(s,'picnic',{},at));});
test('添水后看鸟产生来访；摆放与灯光状态可保存',()=>{const s=L.create(at);L.homeAction(s,'birdwater',at);L.invite(s,'birdwatch',{},at);L.advance(s,at+90000);assert.equal(s.home.birdVisits,1);assert.equal(s.home.birdWater,2);L.homeAction(s,'display',at+90000);L.homeAction(s,'lamp',at+90000);const r=L.validate(clone(s),at+90000);assert.equal(r.home.displayMode,'window');assert.equal(r.home.lamp,false);});
test('设备时区决定昼夜，天气是同一世界同一时间的事实',()=>{const s=L.create(at);const weather=s.world.weather;L.setClockOffset(s,-300,at);assert.equal(s.world.hour,22);assert.equal(s.world.weather,weather);L.setClockOffset(s,480,at);assert.equal(s.world.hour,11);const r=L.validate(clone(s),at);assert.equal(r.world.hour,11);assert.equal(r.world.weather,s.world.weather);});
test('两场景寻路不会越过各自可行走区域',()=>{require('../game/navigation.js');require('../game/scenes.js');for(const scene of Object.values(global.WitchScenes.scenes)){const n=scene.nav;for(let i=0;i<n.cells.length;i+=31){const path=n.findPath(scene.entry,n.cells[i]);assert.ok(path.length>0);for(let j=1;j<path.length;j++)assert.ok(n.clear(path[j-1],path[j]));}}});
for(const r of results)console.log((r.pass?'PASS ':'FAIL ')+r.name+(r.error?'\n'+r.error:''));console.log(results.filter(r=>r.pass).length+'/'+results.length+' expansion tests passed');process.exitCode=results.every(r=>r.pass)?0:1;
