(function (root) {
  'use strict';
  const L = typeof module === 'object' && module.exports ? require('../game/life.js') : root.WitchLife;
  const START = Date.UTC(2026, 8, 20, 3, 0, 0), M = 60000, H = 60 * M;
  const results = [];
  function assert(v, message) { if (!v) throw new Error(message || 'assertion failed'); }
  function stable(v) { return v && typeof v === 'object' ? Array.isArray(v) ? v.map(stable) : Object.fromEntries(Object.keys(v).sort().map(k=>[k,stable(v[k])])) : v; }
  function eq(a, b, m) { assert(JSON.stringify(stable(a)) === JSON.stringify(stable(b)), m || 'State mismatch (values, not object-key order)'); }
  function clone(a) { return JSON.parse(JSON.stringify(a)); }
  function throws(fn) { let threw = false; try { fn(); } catch (_) { threw = true; } assert(threw, 'must reject'); }
  function test(name, fn) { try { fn(); results.push({ name, pass: true }); } catch (e) { results.push({ name, pass: false, error: e.stack || e.message }); } }
  function planted() { const s = L.create(START), f = L.addFragment(s, '今天梦见鲸鱼飞过桂花树，窗外有雨。', START); L.acceptFragment(s, f.id, START); return { s, f }; }
  test('初见时已在读书，章节随真实时间推进', () => {
    const s = L.create(START), v = L.currentView(s, START); assert(v.kind === 'read'); assert(v.excerpt.text.length > 20);
    const page = v.excerpt.chapter; L.advance(s, START + 40 * M); assert(L.currentView(s, START + 40 * M).excerpt.chapter !== page);
    assert(s.activity.bookId === 'moss'); assert(s.memories.length === 1);
  });
  test('离线仍继续同一本书，不因打开页面换活动', () => { const s = L.create(START), original = s.activity.id; L.advance(s, START + H); const saved = L.validate(clone(s), START + H); assert(saved.activity.id === original); eq(L.currentView(saved, START + H), L.currentView(s, START + H)); });
  test('中断五子棋后从同一页继续，游戏不吞掉阅读时间', () => { const s = L.create(START), before = L.currentView(s, START).progress; L.interrupt(s, 'game', START); L.advance(s, START + 20 * M); L.resume(s, START + 20 * M); assert(s.activity.kind === 'read'); assert(Math.abs(L.currentView(s, START + 20 * M).progress - before) < 1e-12); });
  test('时间回拨不会撤回已发生的进度', () => { const s = L.create(START); L.advance(s, START + H); const x = clone(s); L.advance(s, START - H); eq(s, x); });
  test('连续查看不会产生手记或改变随机状态', () => { const s = L.create(START), before = clone(s); for (let i = 0; i < 100; i++) L.currentView(s, START); eq(s, before); });
  test('梦种先研究，再掌握知识，再种植', () => { const {s, f} = planted(); assert(s.activity.studyFragmentId === f.id); assert(s.creations.length === 0); L.advance(s, START + 44999); assert(s.knowledge.length === 0); L.advance(s, START + 45000); assert(s.knowledge.some(k => k.key === 'seed:' + f.id)); assert(s.activity.plantFragmentId === f.id); L.advance(s, START + 90000); assert(s.creations.length === 1 && s.plants.length === 1); assert(s.activity.kind === 'read'); });
  test('离线生成植物和邀请，重复结算不重复发放', () => { const {s} = planted(); L.advance(s, START + 5 * M); assert(s.creations.length === 1); assert(s.discoveries.length === 1); const before = clone(s); L.advance(s, START + 5 * M); eq(s, before); L.advance(s, START + H); assert(s.discoveries.length === 1); });
  test('种植链在线与离线结算完全一致', () => { const {s} = planted(); const one = clone(s), many = clone(s); L.advance(one, START + 20 * M); for (let t = START + 1000; t <= START + 20 * M; t += 1000) L.advance(many, t); eq(one, many); });
  test('七天自主生活按事件时间结算，与逐小时相同', () => { const one = L.create(START), many = clone(one); L.advance(one, START + 7 * 24 * H); for (let i = 1; i <= 7 * 24; i++) L.advance(many, START + i * H); eq(one, many); assert(one.memories.length <= 4); });
  test('权重来自精神、天气、偏好，选择有变化且可重现', () => { const counts = new Set(); for (let i = 0; i < 24; i++) { const s = L.create(START + i * H); L.advance(s, s.activity.endsAt); counts.add(s.activity.kind); assert(s.activity.decision.reason.length > 0); } assert(counts.size >= 3); const s = L.create(START); s.world.energy = 10; const rows = L.decisionView(s, START); assert(rows.find(r => r.kind === 'rest').score > rows.find(r => r.kind === 'read').score); });
  test('硬前置：没有鱼竿不能钓鱼，没有知识不能种植', () => { const s = L.create(START), rows = L.decisionView(s, START); assert(!rows.find(r => r.kind === 'fish').eligible); assert(!rows.find(r => r.kind === 'plant').eligible); const {s: other} = planted(); other.activity = {...other.queue.find(a => a.kind === 'craft'), id:'activity-999', startedAt:START, endsAt:START + 45000, progressBase:0}; throws(() => L.validate(other, START)); });
  test('第二颗梦种保留与旧物的因果来源', () => { const {s,f} = planted(); L.advance(s, START + 5*M); const g = L.addFragment(s, '今天喝了暖暖的茶', START + 5*M); assert(g.proposal.sourceIds.includes(f.id)); assert(g.proposal.sourceIds.includes(g.id)); assert(g.proposal.relatedCreationId === s.creations[0].id); const provenance = L.inspectCreation(s, s.creations[0].id); assert(provenance.sources[0].text === f.text); assert(provenance.knowledge.length > 0); });
  test('GPT提案只修改表现字段，不能注入状态与来历', () => { const s = L.create(START), f = L.addFragment(s, '做了一个梦', START); const source = [...f.proposal.sourceIds]; L.applyProposal(s,f.id,{name:'浮游书',description:'一本长出叶子的书。',kind:'book',color:'#aabbcc',thought:'想翻开看看。',sourceIds:['fragment-999'],energy:999,script:'alert(1)'},START); eq(f.proposal.sourceIds,source); assert(f.isDreamSeed); assert(s.world.energy <= 100); assert(!Object.hasOwn(f.proposal,'script')); throws(() => L.applyProposal(s,f.id,{name:'x',description:'x',kind:'danger',color:'#aabbcc'},START)); });
  test('输入与导入保持文字为数据，拒绝超长和非法颜色', () => { const s = L.create(START); const text='<img src=x onerror=alert(1)>我梦见一棵树'; const f=L.addFragment(s,text,START); assert(f.text===text); const safe=L.validate(clone(s),START); assert(safe.fragments[0].text===text); throws(()=>L.addFragment(s,'x'.repeat(601),START)); const bad=clone(s); bad.fragments[0].proposal.color='url(javascript:alert(1))'; throws(()=>L.validate(bad,START)); const proto=JSON.parse(JSON.stringify(s).slice(0,-1)+',"__proto__":{"polluted":true}}'); L.validate(proto,START); assert(!({}).polluted); });
  test('导入后重播完成活动也不重复奖励', () => { const {s}=planted(); L.advance(s,START+45000); const old=clone(s.activity); L.advance(s,START+5*M); s.activity=old; s.lastAdvancedAt=START+45000; const restored=L.validate(s,START+5*M); assert(restored.creations.length===1); assert(restored.discoveries.length===1); });
  test('导入拒绝伪造的重复物品、损坏来源与成长状态', () => { const {s}=planted(); L.advance(s,START+5*M); const a=clone(s); a.creations.push(clone(a.creations[0])); throws(()=>L.validate(a,START+5*M)); const b=clone(s); b.fragments[0].proposal.sourceIds=['fragment-999']; throws(()=>L.validate(b,START+5*M)); const c=clone(s); c.discoveries=[]; throws(()=>L.validate(c,START+5*M)); });
  test('排队多颗梦种时每颗先学习，再按自己的种类制作', () => { const {s}=planted(); const second=L.addFragment(s,'今天的小蛋糕像月亮',START); L.acceptFragment(s,second.id,START); L.advance(s,START+10*M); assert(s.creations.length===2); assert(s.plants.length===1); assert(s.knowledge.filter(k=>k.key.startsWith('seed:')).length===2); assert(s.discoveries.length===1); assert(s.creations.some(c=>c.kind==='food')); });
  test('完整存档往返保留梦种、因果知识、成长和棋局', () => { const {s}=planted(); L.advance(s,START+5*M); s.board={version:1,size:15,board:Array(225).fill(0),turn:'human',winner:null,lastMove:null,history:[],outcomeNotified:false}; const recovered=L.validate(JSON.parse(L.exportState(s)),START+5*M); eq(recovered,s); });
  test('雨天确实影响植物生长速度与水分', () => { let rainy, dry; for(let i=0;i<80;i++){const at=START+i*M,s=L.create(at);const f=L.addFragment(s,'梦见一株星星花',at);L.acceptFragment(s,f.id,at);L.advance(s,at+90000);if(s.world.weather==='小雨'&&!rainy)rainy={s,at};if(s.world.weather==='晴朗'&&!dry)dry={s,at};if(rainy&&dry)break;} assert(rainy&&dry);L.advance(rainy.s,rainy.at+90000+70000);L.advance(dry.s,dry.at+90000+70000);assert(rainy.s.plants[0].bloomed);assert(!dry.s.plants[0].bloomed);assert(rainy.s.plants[0].hydration>dry.s.plants[0].hydration); });
  test('在研究中退出并导入能继续，导入的AI种类不能绕过知识', () => {const {s,f}=planted(); const resumed=L.validate(clone(s),START+20000); assert(resumed.activity.studyFragmentId===f.id); assert(L.currentView(resumed,START+20000).excerpt.chapter.includes('附页')); L.advance(resumed,START+90000);assert(resumed.plants.length===1);});
  test('梦种是记忆材料：鲸鱼梦成瓶，饮食成食物，花草才种成植物', () => {for(const [text,kind] of [['梦见鲸鱼在天空飞','bottle'],['吃了草莓小蛋糕','food'],['吃了一碗热面','food'],['桂花开了','plant']]){const s=L.create(START),f=L.addFragment(s,text,START);assert(f.proposal.kind===kind);L.acceptFragment(s,f.id,START);assert(s.activity.kind==='research');L.advance(s,START+90000);assert(s.creations[0].kind===kind);assert(s.plants.length===(kind==='plant'?1:0));}});
  test('外部书本提案仍须学习，成品保持书本，不能伪造跳过前置', () => {const s=L.create(START),f=L.addFragment(s,'今天想到一段故事',START);L.applyProposal(s,f.id,{name:'雨天故事书',description:'收着这一天故事的小书。',kind:'book',color:'#aabbcc'},START);L.acceptFragment(s,f.id,START);assert(s.activity.studyFragmentId===f.id);const corrupt=clone(s);corrupt.activity={...corrupt.queue.find(a=>a.kind==='craft'),id:'activity-999',startedAt:START,endsAt:START+45000,progressBase:0};delete corrupt.activity.knowledgeFragmentId;throws(()=>L.validate(corrupt,START));L.advance(s,START+90000);assert(s.creations[0].kind==='book');assert(s.plants.length===0&&s.discoveries.length===0);assert(s.knowledge.some(k=>k.key==='seed:'+f.id));});
  test('棋盘保持打开六小时，阅读书签不动且世界时间继续', () => {const s=L.create(START),before=L.currentView(s,START).progress;L.interrupt(s,'game',START);L.holdGame(s,START+6*H);assert(s.activity.kind==='game');assert(s.lastAdvancedAt===START+6*H);L.validate(clone(s),START+6*H);L.resume(s,START+6*H);assert(s.activity.kind==='read');assert(Math.abs(L.currentView(s,START+6*H).progress-before)<1e-12);});
  test('退出时留下棋局，重新打开先恢复日常再结算离线时间', () => {const s=L.create(START);L.interrupt(s,'game',START);L.holdGame(s,START+10*M);const restored=L.validate(clone(s),START+6*H);L.resume(restored,restored.lastAdvancedAt);L.advance(restored,START+6*H);assert(restored.activity.kind!=='game');assert(restored.books.some(b=>b.readCount>0));});
  root.WitchLifeTestResults = results;
  if (typeof module === 'object' && module.exports) { for(const r of results) console.log((r.pass?'PASS ':'FAIL ')+r.name+(r.error?'\n'+r.error:'')); console.log(results.filter(r=>r.pass).length+'/'+results.length+' tests passed'); process.exitCode=results.every(r=>r.pass)?0:1; }
})(typeof globalThis !== 'undefined' ? globalThis : this);
