'use strict';
const assert=require('node:assert/strict'),V=require('../game/village.js'),L=require('../game/life.js');
const at=Date.UTC(2026,8,30,3),M=60000,H=60*M,clone=x=>JSON.parse(JSON.stringify(x));let pass=0,fail=0;
function test(name,fn){try{fn();console.log('PASS',name);pass++;}catch(e){console.error('FAIL',name,e.stack);fail++;}}
test('全部地点相互可达，路径避开建筑和家具，只从桥上过河',()=>{for(const a of Object.values(V.SPOTS))for(const b of Object.values(V.SPOTS)){const path=V.route(a,b);for(let i=1;i<path.length;i++){const p=path[i-1],q=path[i];if(p.area===q.area)assert.ok(V.lineClear(p,q),a.name+' -> '+b.name);else{assert([[V.DOOR,V.HOME],[V.HOME,V.DOOR],[V.FOREST_GATE,V.FOREST_ENTRY],[V.FOREST_ENTRY,V.FOREST_GATE]].some(([x,y])=>p.area===x.area&&q.area===y.area&&V.dist(p,x)===0&&V.dist(q,y)===0));}}}});
test('v2—v5迁移保留旧档身份、梦种、阅读进度，新增空间位置',()=>{for(const v of [2,3,4,5]){const s=L.create(at);s.avatar.kind='original';s.preferences.name='小罗';L.addFragment(s,'测试梦种：会飞的小叶子',at);const old=clone(s);old.version=v;delete old.village;const got=L.validate(old,at);assert.equal(got.version,7);assert.equal(got.avatar.kind,'original');assert.equal(got.preferences.name,'小罗');assert.equal(got.fragments[0].text,s.fragments[0].text);assert.equal(got.activity.id,s.activity.id);assert.deepEqual(got.village.location,V.destination(got.activity));}});
test('前往活动需要真实路程，途中不增加工作进度或提前收获',()=>{const s=L.create(at);L.invite(s,'garden',{},at);assert.ok(s.activity.startedAt>at);assert.ok(s.village.journey);assert.equal(L.currentView(s,at+1000).progress,0);assert.equal(s.country.harvests,0);const end=s.activity.endsAt;L.advance(s,end-1);assert.ok(s.village.journey===null);assert.equal(s.country.plots.filter(p=>p.crop).length,0);L.advance(s,end);assert.equal(s.country.plots.filter(p=>p.crop).length,1);});
test('途中保存再导入，坐标与剩余路程连续',()=>{const s=L.create(at);L.walkTo(s,'farm',at);const now=at+4500;L.advance(s,now);const before=V.position(s,now),loaded=L.validate(clone(s),now);assert.deepEqual(V.position(loaded,now),before);assert.equal(loaded.village.journey.endsAt,s.village.journey.endsAt);L.advance(loaded,s.village.journey.endsAt);assert.equal(loaded.village.location.area,'village');assert.equal(loaded.village.location.x,V.SPOTS.farm.x);});
test('散步多次改方向不会刷日志、重扣资源或堆积书签',()=>{const s=L.create(at);L.walkTo(s,'farm',at);const serial=s.serial,events=s.events.length,paused=s.paused.length;for(let i=1;i<20;i++)L.walkTo(s,i%2?'shop':'bench',at+i*200);assert.equal(s.serial,serial);assert.equal(s.events.length,events);assert.equal(s.paused.length,paused);assert.equal(s.home.pantry.herbs,2);});
test('路上加入棋局会停在脚下，收棋后重新走向原目的地',()=>{const s=L.create(at);L.walkTo(s,'farm',at);L.advance(s,at+3000);const p=V.position(s,at+3000);L.interrupt(s,'game',at+3000);assert.equal(s.village.journey,null);assert.equal(V.dist(p,V.position(s,at+3000)),0);L.holdGame(s,at+M);assert.equal(V.dist(p,V.position(s,at+M)),0);const loaded=L.validate(clone(s),at+M);assert.equal(loaded.activity.kind,'walk');assert.ok(loaded.village.journey);assert.equal(V.dist(p,V.position(loaded,at+M)),0);});
test('带路程的七天离线与逐小时推进完全一致',()=>{const one=L.create(at),many=clone(one);L.walkTo(one,'farm',at);L.walkTo(many,'farm',at);L.advance(one,at+7*24*H);for(let t=at+H;t<=at+7*24*H;t+=H)L.advance(many,t);assert.deepEqual(one,many);});
test('梦种制作与路线共用时间线，重复进入不重复产出',()=>{const s=L.create(at),f=L.addFragment(s,'梦见一株开着星星花的小草',at);L.acceptFragment(s,f.id,at);assert.ok(s.village.journey);L.advance(s,s.activity.endsAt);assert.ok(s.knowledge.some(k=>k.key==='seed:'+f.id));L.advance(s,s.activity.endsAt);assert.equal(s.plants.length,1);L.advance(s,at+6*M);const original=clone(s);L.advance(s,at+6*M);assert.deepEqual(s,original);assert.equal(s.creations.length,1);});
test('邻居借还书以实际读完为前提，种子只赠一次',()=>{const s=L.create(at);const near=()=>{const n=L.residents(s,s.lastAdvancedAt).find(n=>n.id==='moss');s.village.location={area:n.area,x:n.x,y:n.y};s.village.journey=null;};near();L.neighborAction(s,'moss','talk',at);L.neighborAction(s,'moss','borrow',at);assert.throws(()=>L.neighborAction(s,'moss','return',at));L.invite(s,'read',{bookId:'stars'},at);const end=s.activity.endsAt;L.advance(s,end);near();const before=s.country.seeds.moonflower;L.neighborAction(s,'moss','return',end);assert.equal(s.country.seeds.moonflower,before+1);assert.throws(()=>L.neighborAction(s,'moss','return',end));assert.equal(s.country.seeds.moonflower,before+1);L.validate(clone(s),end);});
test('分享梦种保留产物和原文来源，反复聊天不刷手记',()=>{const s=L.create(at),f=L.addFragment(s,'桂花落进了梦里的小瓶',at);L.acceptFragment(s,f.id,at);L.advance(s,at+6*M);const n=L.residents(s,at+6*M).find(n=>n.id==='moss');s.village.location={area:n.area,x:n.x,y:n.y};s.village.journey=null;L.neighborAction(s,'moss','show',at+6*M);const e=s.events.at(-1);assert.ok(e.sourceIds.includes(f.id));assert.ok(e.sourceIds.includes(s.creations[0].id));L.neighborAction(s,'moss','talk',at+6*M);const count=s.memories.length;for(let i=0;i<10;i++)L.neighborAction(s,'moss','talk',at+6*M);assert.equal(s.memories.length,count);assert.throws(()=>L.neighborAction(s,'moss','show',at+6*M));});
test('居民位置由日程、天气和已发生经历决定，连续查看无副作用',()=>{const s=L.create(at),before=clone(s),n=L.residents(s,at);assert.deepEqual(L.residents(s,at),n);assert.deepEqual(s,before);for(let t=at;t<at+H;t+=1700)for(const npc of L.residents(s,t)){assert.ok(V.walkable(npc.area,npc.x,npc.y));assert.ok(npc.reason);}});
test('拒绝穿墙路线、未知地点和断开的居民记忆，不覆盖原输入',()=>{const s=L.create(at);L.walkTo(s,'farm',at);for(const change of [s=>s.village.location.x=-1,s=>s.village.journey.points=[V.HOME,{area:'village',x:1500,y:1000}],s=>s.village.contacts.moss.seen=['creation-999'],s=>s.village.journey.purpose='activity-999']){const bad=clone(s);change(bad);assert.throws(()=>L.validate(bad,at));}assert.equal(s.village.location.area,'inside');});
console.log(`${pass}/${pass+fail} v6 tests passed`);if(fail)process.exitCode=1;
