const assert=require('node:assert/strict'),P=require('../game/pocket-games'),L=require('../game/life'),H=require('../game/hobbies');
let passed=0;function test(name,fn){fn();console.log('PASS '+name);passed++;}
const now=Date.UTC(2026,9,3,4),clone=x=>JSON.parse(JSON.stringify(x));
test('数织两种尺寸的每种旋转镜像都只有一个答案',()=>{for(let s=0;s<48;s++)for(const n of [5,8]){const b=P.nonogram(s,n);assert.equal(P.solutions(b.solution,n,b.givens),1);assert.deepEqual(P.cleanNonogram(b),b);}});
test('数织支持标空格、撤销、提示和完成判定',()=>{const b=P.nonogram(10,5),i=b.cells.findIndex((_,i)=>!b.givens.includes(i));P.mark(b,i,1);P.undoNonogram(b);assert.equal(b.cells[i],0);while(!P.nonogramDone(b))assert(P.hint(b));assert(P.nonogramDone(P.cleanNonogram(b)));});
test('合成每块单步只合并一次，无效移动不生成新方块',()=>{const r=P.slide([2,2,2,2,...Array(12).fill(0)],'L');assert.deepEqual(r.cells.slice(0,4),[4,4,0,0]);assert.equal(r.score,8);assert.deepEqual(P.slide([4,4,4,0,...Array(12).fill(0)],'L').cells.slice(0,4),[8,4,0,0]);const b=P.merge(31);b.cells=[2,0,0,0,...Array(12).fill(0)];const before=clone(b);assert.equal(P.move(b,'L'),false);assert.deepEqual(b,before);});
test('合成重播、撤销、保存恢复一致，损坏棋盘被拒绝',()=>{const b=P.merge(now);for(let i=0;i<200;i++)P.move(b,'LURD'[i%4]);assert.deepEqual(P.cleanMerge(b),b);const copy=clone(b);P.undoMerge(b);P.move(b,copy.moves.at(-1));assert.deepEqual(b,copy);const bad=clone(b);bad.score++;assert.throws(()=>P.cleanMerge(bad));});
test('新增游戏随完整世界存档往返，旧档缺字段自动补空',()=>{const s=L.create(now);s.playbox.nonogram=P.nonogram(now,8);s.playbox.merge=P.merge(now);P.move(s.playbox.merge,'L');const t=L.validate(clone(s),now);assert.deepEqual(t.playbox.nonogram,s.playbox.nonogram);assert.deepEqual(t.playbox.merge,s.playbox.merge);delete s.playbox.nonogram;delete s.playbox.merge;assert.equal(L.validate(s,now).playbox.nonogram,null);});
test('邀请明信片连续完成三步，信文保留梦种来源且不重复产出',()=>{const s=L.create(now);L.addFragment(s,'今天看到窗台上有一朵黄色的小花。',now);L.invite(s,'postcard',{},now);for(let i=0;i<3;i++){assert.equal(s.activity.kind,'postcard');L.advance(s,s.activity.endsAt);}const w=s.hobbies.works.find(w=>w.project==='postcard');assert(w);assert.equal(w.steps.length,3);assert.equal(w.sourceIds[0],s.fragments[0].id);assert(w.letter.body.includes('黄色的小花'));assert.equal(w.letter.from,s.preferences.name);assert.equal(w.read,false);w.read=true;const t=L.validate(clone(s),s.lastAdvancedAt);assert.deepEqual(t.hobbies.works,s.hobbies.works);L.advance(t,t.lastAdvancedAt);assert.equal(t.hobbies.works.length,1);});
test('旧明信片收藏保留原文，导入拒绝超长信文',()=>{const s=L.create(now);L.invite(s,'postcard',{},now);for(let i=0;i<3;i++)L.advance(s,s.activity.endsAt);const old=clone(s.hobbies);delete old.works[0].letter;delete old.works[0].read;assert.equal(H.clean(old).works[0].text,old.works[0].text);s.hobbies.works[0].letter.body='x'.repeat(701);assert.throws(()=>L.validate(s,s.lastAdvancedAt));});
test('完成数织留下单条共同经历，反复打开不刷记忆',()=>{const s=L.create(now),b=P.nonogram(now);while(!P.nonogramDone(b))P.hint(b);L.recordMiniGame(s,'nonogram',b,now);L.recordMiniGame(s,'nonogram',b,now);assert.equal(s.memories.filter(m=>m.key===b.id).length,1);L.validate(s,now);});
console.log(passed+'/8 v7 tests passed');
