'use strict';
const A=require('node:assert/strict'),L=require('../game/life'),E=require('../game/country'),D=require('../game/seasons'),F=require('../game/festival-games'),V=require('../game/village'),Letters=require('../game/letters');
const now=Date.UTC(2026,9,4,4),clone=x=>JSON.parse(JSON.stringify(x));let pass=0,fail=0;function test(n,f){try{f();console.log('PASS '+n);pass++;}catch(e){console.error('FAIL '+n+' '+e.stack);fail++;}}
function fresh(){const s=L.create(now);s.preferences.utcOffsetMinutes=480;return s;}
test('四十种作物、二十四种鱼及四季日期与南半球',()=>{A.equal(Object.keys(E.CROPS).length,40);A.equal(Object.keys(E.FISH).length,24);const s=fresh();for(const[m,season]of[[0,'winter'],[2,'spring'],[5,'summer'],[8,'autumn']]){A.equal(D.season(s,Date.UTC(2026,m,5)),season);}s.country.hemisphere='south';A.equal(D.season(s,Date.UTC(2026,8,5)),'spring');});
test('旧版六块田、种子、鱼篓和明信片迁移不丢失',()=>{const s=fresh();s.version=6;s.country.plots=s.country.plots.slice(0,6);delete s.country.version;s.country.seeds.radish=17;s.country.fish.carp=4;s.country.caught.carp=6;for(const k of['unlocked','farmingXp','fishingXp','harvested','best','hemisphere','fishingPlace','jobs','lastJobAt'])delete s.country[k];s.village.version=1;for(const k of['reed','fern','ember'])delete s.village.contacts[k];const t=L.validate(clone(s),now);A.equal(t.version,7);A.equal(t.country.plots.length,12);A.equal(t.country.unlocked,6);A.equal(t.country.seeds.radish,17);A.equal(t.country.fish.carp,4);A.equal(t.country.caught.carp,6);A.equal(t.country.harvested.radish,0);A.equal(Object.keys(t.village.contacts).length,12);A.deepEqual(L.validate(clone(t),now),t);});
test('批量买种子有总价、失败不扣钱，非当季和等级不足不能买',()=>{const s=fresh();s.country.coins=1000;const before=s.country.seeds.herbs;E.action(s,'buySeed',{crop:'herbs',quantity:10},now,()=>.5);A.equal(s.country.seeds.herbs,before+10);A.equal(s.country.coins,1000-E.CROPS.herbs.seedPrice*10);const snapshot=clone(s.country);for(const data of[{crop:'herbs',quantity:100},{crop:'watermelon',quantity:1},{crop:'pumpkin',quantity:99}])A.throws(()=>E.action(s,'buySeed',data,now,()=>.5));A.deepEqual(s.country,snapshot);});
test('种植、浇水、收获、图鉴、经验与开垦遵守资源守恒',()=>{const s=fresh();s.country.seeds.herbs=20;E.action(s,'batch',{tool:'plant',crop:'herbs'},now,()=>.5);A.equal(s.country.seeds.herbs,14);A.equal(s.country.plots.filter(p=>p.crop).length,6);E.action(s,'batch',{tool:'water'},now,()=>.5);const xp=s.country.farmingXp;E.action(s,'water',{plot:0},now,()=>.5);A.equal(s.country.farmingXp,xp);for(const p of s.country.plots)if(p.crop)p.workMs=E.CROPS[p.crop].minutes*60000;const stock=E.stock(s,'herbs');E.action(s,'batch',{tool:'harvest'},now,()=>.5);A.equal(s.country.harvested.herbs,E.stock(s,'herbs')-stock);A(s.country.farmingXp>0);const snap=clone(s.country);A.throws(()=>E.action(s,'harvest',{plot:0},now,()=>.5));A.deepEqual(s.country,snap);s.country.coins=100;s.country.farmingXp=12;E.action(s,'expand',{},now,()=>.5);A.equal(s.country.unlocked,9);A.equal(s.country.coins,70);A.throws(()=>E.action(s,'expand',{},now,()=>.5));s.country.farmingXp=108;E.action(s,'expand',{},now,()=>.5);A.equal(s.country.unlocked,12);});
test('种下的作物跨季保留，在线离线生长相同',()=>{const s=fresh();E.action(s,'plant',{plot:0,crop:'herbs'},now,()=>.5);const t=clone(s),end=now+48*3600000;E.grow(s,end,()=> '小雨');for(let at=now;at<end;at+=3600000)E.grow(t,at+3600000,()=> '小雨');A.deepEqual(s.country.plots,t.country.plots);A(E.ripe(s.country.plots[0]));});
test('每条鱼都有可遇见的季节时段水域，夜鱼不在白天出现',()=>{const seen=new Set(),s=fresh();s.country.fishingXp=1000;for(const month of[0,3,6,9])for(let hour=0;hour<24;hour++)for(const weather of['晴','小雨'])for(const habitat of['river','pond']){const at=Date.UTC(2026,month,4,hour);s.world.hour=hour;s.world.weather=weather;for(const {id} of D.fishPool(s,at,habitat))seen.add(id);}A.equal(seen.size,24);s.world.hour=12;s.world.weather='晴';A(!D.fishPool(s,now,'river').some(p=>p.id==='moonfish'));});
test('钓鱼落袋只结算一次，钓点在一竿中途保持不变',()=>{const s=fresh();s.country.rod=2;E.action(s,'cast',{},now,()=>.2);A.throws(()=>E.action(s,'fishingPlace',{value:'pond'},now,()=>.2));for(let i=0;i<24&&['waiting','hooked'].includes(s.country.session.stage);i++)E.action(s,s.country.session.tension>65?'relax':'reel',{},now+10000,()=>.2);A.equal(s.country.session.stage,'caught');const key=s.country.session.species;A.equal(s.country.caught[key],1);A(s.country.best[key]>0);const xp=s.country.fishingXp;A.throws(()=>E.action(s,'reel',{},now+10000,()=>.2));A.equal(s.country.fishingXp,xp);});
test('自己的真实生活成为明信片来源，草稿跨三步和存档保持',()=>{const s=fresh();L.invite(s,'cook',{},now);L.advance(s,s.activity.endsAt);const fact=s.events.find(e=>e.type==='daily'&&e.text.includes('料理'));A(s.events.some(e=>e.type==='daily'));L.invite(s,'postcard',{},s.lastAdvancedAt);const draft=clone(s.hobbies.projects.postcard.draft);A.equal(draft.sourceType,'life');const restored=L.validate(clone(s),s.lastAdvancedAt);A.deepEqual(restored.hobbies.projects.postcard.draft,draft);for(let i=0;i<3;i++)L.advance(restored,restored.activity.endsAt);const w=restored.hobbies.works.find(w=>w.project==='postcard');A.equal(w.letter.sourceType,'life');A(w.letter.body.includes(draft.sourceText));A.equal(w.letter.theme,'kitchen');A.deepEqual(L.validate(clone(restored),restored.lastAdvancedAt).hobbies.works,restored.hobbies.works);});
test('新生活计划完成后才获得草叶或报酬，不可重复结算',()=>{for(const kind of['forage','sketch','help','deliver']){const s=fresh(),coins=s.country.coins;let start=now;for(let h=0;h<72;h++){if(L.decisionView(s,start).find(r=>r.kind===kind)?.eligible)break;start+=3600000;}L.invite(s,kind,{},start);A.equal(s.country.coins,coins);L.advance(s,s.activity.endsAt);if(kind==='help')A.equal(s.country.coins,coins+12);if(kind==='deliver')A.equal(s.country.coins,coins+8);A(s.events.some(e=>e.text.includes(kind==='sketch'?'速写':kind==='forage'?'香草':kind==='help'?'12':'8')));const count=s.events.length,money=s.country.coins;L.advance(s,s.lastAdvancedAt);A.equal(s.events.length,count);A.equal(s.country.coins,money);L.validate(clone(s),s.lastAdvancedAt);}});
test('三张地图的所有地点可达且仅从门口换区，居民路线可恢复',()=>{const portals=[[V.DOOR,V.HOME],[V.HOME,V.DOOR],[V.FOREST_GATE,V.FOREST_ENTRY],[V.FOREST_ENTRY,V.FOREST_GATE]];for(const a of Object.values(V.SPOTS))for(const b of Object.values(V.SPOTS)){const points=V.route(a,b);A.equal(V.dist(points[0],V.nearest(a)),0);A.equal(V.dist(points.at(-1),V.nearest(b)),0);for(let i=1;i<points.length;i++){const p=points[i-1],q=points[i];if(p.area===q.area)A(V.lineClear(p,q),a.name+' → '+b.name);else A(portals.some(([x,y])=>x.area===p.area&&y.area===q.area&&V.dist(p,x)===0&&V.dist(q,y)===0));}}const s=fresh();for(let i=0;i<12;i++){const n=L.residents(s,now+i*90000);A.equal(n.length,12);for(const p of n)A(V.walkable(p.area,p.x,p.y));}L.walkTo(s,'pond',now);L.advance(s,s.village.journey.endsAt);A.equal(s.village.location.area,'forest');L.validate(clone(s),s.lastAdvancedAt);});
test('十二种游戏各档初始棋盘完整保存，并拒绝篡改状态',()=>{const s=fresh();for(const kind of F.ids){for(let level=1;level<=F.CATALOG[kind][2];level++){const b=F.create(kind,1234,level);A.deepEqual(F.clean(clone(b)),b);const bad=clone(b);bad.score++;A.throws(()=>F.clean(bad));}s.playbox[kind]=F.create(kind,999);}A.deepEqual(L.validate(clone(s),now).playbox,s.playbox);});
test('十二关推箱子均存在合法解，操作可重播',()=>{for(let level=1;level<=12;level++){const original=F.create('sokoban',18,level),key=b=>b.player+':'+[...b.crates].sort((a,b)=>a-b).join(','),queue=[original],seen=new Set([key(original)]);let solution=null;for(let q=0;q<queue.length&&q<70000;q++){const b=queue[q];if(b.won){solution=b;break;}for(const dir of['U','D','L','R']){const n=clone(b);if(F.command(n,{type:'move',dir})&&!seen.has(key(n))){seen.add(key(n));queue.push(n);}}}A(solution,'推箱子第 '+level+' 关不可解');A.deepEqual(F.clean(solution),solution);}});
test('汉诺塔3到6环能用最少步数完成；撤销回到未完成状态',()=>{for(let lv=1;lv<=4;lv++){const b=F.create('hanoi',45,lv);function solve(n,from,to,via){if(!n)return;solve(n-1,from,via,to);A(F.command(b,{type:'ring',from,to}));solve(n-1,via,to,from);}solve(lv+2,0,2,1);A(b.won);A.equal(b.moves.length,2**(lv+2)-1);A.deepEqual(F.clean(b),b);F.undo(b);A(!b.over);}});
test('迷宫钥匙和出口相互可达，抵达出口前必须集齐',()=>{for(let lv=1;lv<=5;lv++){const b=F.create('maze',55,lv);for(const target of[...b.keys,b.exit]){const queue=[[b.player,[]]],seen=new Set([b.player]);let steps;for(let q=0;q<queue.length;q++){const [i,m]=queue[q];if(i===target){steps=m;break;}for(const dir of['U','D','L','R']){const n=F.direction({...b,player:i},dir);if(n>=0&&!b.cells[n]&&!seen.has(n)){seen.add(n);queue.push([n,[...m,dir]]);}}}A(steps);steps.forEach(dir=>A(F.command(b,{type:'move',dir})));}A(b.won);A.deepEqual(F.clean(b),b);}});
test('扫雷所有首点周围安全；完整翻开安全格胜利',()=>{for(let lv=1;lv<=3;lv++)for(let seed=0;seed<5;seed++){const b=F.create('mines',seed,lv);F.command(b,{type:'open',i:seed});for(const i of[seed,...F.adjacent(b,seed,true)])A.notEqual(b.cells[i],-1);for(let i=0;i<b.cells.length&&!b.over;i++)if(b.cells[i]!==-1&&!b.open[i])F.command(b,{type:'open',i});A(b.won);A.deepEqual(F.clean(b),b);}});
test('猜色珠正确计算重复颜色，孔明棋仅允许合法跳跃',()=>{A.deepEqual(F.feedback([1,1,2,2],[1,2,1,3]),{exact:1,near:2});const b=F.create('code',74);F.command(b,{type:'guess',colors:b.secret});A(b.won);A.deepEqual(F.clean(b),b);const p=F.create('peg',9),[from,to]=F.pegMoves(p)[0];A(!F.command(p,{type:'jump',from:0,to:1}));F.command(p,{type:'jump',from,to});A.equal(p.cells.filter(v=>v===1).length,31);F.undo(p);A.equal(p.cells.filter(v=>v===1).length,32);});
test('对弈AI只下合法步，黑白棋自动跳过无子可下方直至结局',()=>{for(const kind of['connect','reversi'])for(let lv=1;lv<=F.CATALOG[kind][2];lv++){const b=F.create(kind,44,lv);for(let i=0;i<90&&!b.over;i++){const a=kind==='connect'?{type:'column',col:b.cells.slice(0,7).findIndex(x=>!x)}:{type:'cell',i:F.legal(b,1)[0]};A(F.command(b,a));}A(b.over);A.deepEqual(F.clean(b),b);}});
test('点灯由合法翻转生成可解棋局；滑块排列保持可解奇偶性',()=>{for(let seed=0;seed<30;seed++)for(let level=1;level<=3;level++){const b=F.create('slide',seed,level),cells=b.cells.filter(Boolean);let inv=0;for(let i=0;i<cells.length;i++)for(let j=i+1;j<cells.length;j++)if(cells[i]>cells[j])inv++;A.equal(b.cols%2?inv%2:(inv+b.rows-Math.floor(b.cells.indexOf(0)/b.cols))%2,b.cols%2?0:1);const l=F.create('lights',seed,level);A(!l.cells.every(Boolean));const saved=clone(l);F.command(l,{type:'cell',i:0});F.undo(l);A.deepEqual(l,saved);}});
console.log(pass+' / '+(pass+fail)+' v8 tests passed');if(fail)process.exitCode=1;
